### DISCUSSION TITLE
Compare with previous commit in a PR

### DISCUSSION THREAD

**Discussion by Pythonic-Rainbow** [tj-actions/changed-files#1099] [Q&A] [answered]
When a commit is pushed to a PR, is there a way to compare it with the previous commit in that PR branch?

**Comment by jackton1** [comment, marked as answer]
Hi @Pythonic-Rainbow, to compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g

```yml
…
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
…
```

For more information consult the usage documentation: https://github.com/tj-actions/changed-files#usage
