### DISCUSSION TITLE
How to get all files changed compared to another branch?

### DISCUSSION THREAD

**Discussion by bearhuglily** [tj-actions/changed-files#1327] [Q&A] [answered]
For example, our main branch is `master` and that is the other branch I want to compare any other feature branch to. Right now, if I make changes to say, 5 files, on my `tf-test-branch`, and one of them fails the lint check I have, any other files left to check after don't get checked because the whole github action stops. So then I fix the one file and re-push, and now the list of changed files is _just_ that one file. How can I change that so that it is all five files again?

Here are my checkout and changed-files steps: 
```
# Checkout the repository and fetch all history for all branches and tags
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
# Get a list of yaml files that have changed in the current branch under templates
    - name: Get changed files
      id: getfiles
      uses: tj-actions/changed-files@v37
      with:
        files: templates/**/*.yaml
```

**Comment by jackton1** [comment]
@bearhuglily Can you also include the GitHub event that triggers the workflow?

**Comment by bearhuglily** [comment]
Trigger: 
```
# The workflow triggers on push and pull request events that change YAML files in the templates/ directory or its subdirectories
on:
  push:
    paths:
      - 'templates/**/*.yaml'
  pull_request:
    paths:
      - 'templates/**/*.yaml'
```

**Comment by jackton1** [comment]
Okay, It appears that the `push` event is also getting triggered by new commits you push to the branch, and what you want in this case is on `pull_request` which would contain all files that have been changed in your branch compared to `master`

```yml
name: CI

on:
  pull_request:
    branches:
      - master
```
