### DISCUSSION TITLE
Get all files changed by PR after squash-merging

### DISCUSSION THREAD

**Discussion by dionhaefner** [tj-actions/changed-files#1379] [Q&A] [answered]
I am using a workflow that triggers after a PR is merged into `main`. My goal is to use `tj-actions/changed-files` to find which files were modified by the PR:

```yaml
on:
  pull_request:
    types:
      # closed could be merged or closed without merging
      # jobs must check if PR was merged
      - closed
    branches:
      - main

jobs:
  get-affected-files:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
```

I noticed that this includes additional files (that are not part of the PR / merge commit) if the PR wasn't up-to-date with `main`. I assume that we need to pass a different base SHA to compare with, but I can't seem to figure it out. Happy for any pointers.

Our repo has mandatory squash-merging in case it's relevant.
