### DISCUSSION TITLE
How to ignore multiple directories with `files_ignore` ?

### DISCUSSION THREAD

**Discussion by vitalii-dubovoi** [tj-actions/changed-files#1398] [Q&A] [answered]
Hello, how can I add  two, or multiple directories to ignore with`files_ignore`
Currently, I have such a wf configuration
```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            scripts/**/*  
            .github/**/*
          dir_names: true # Show only dirs thet were changed
          dir_names_exclude_current_dir: true # Skip to show root (.) dir
          json: true
          dir_names_max_depth: 2
```
But it returns an output like this - `"[\"cloudflare\",\"scripts\",\"azure/dev\"]"` with scripts directory

**Comment by jackton1** [comment, marked as answer]
Hi @vitalii-dubovoy to exclude the directory itself you can use the directory name only `scripts` or use `scripts/**`

```yml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            scripts
            .github/**
          ...
```
