### DISCUSSION TITLE
Remove "root" dir from list

### DISCUSSION THREAD

**Discussion by rsorelli-hedgepoint** [tj-actions/changed-files#1448] [Q&A] [answered]
Hi there,

How can I remove the root dir "." from the list returned by the action ?
I my case, I have a commit that changes the template.yaml file and it keeps showing on the output

```yml
      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v37.0.5
        with:
          json: true
          escape_json: true
          files_ignore: |
            .github/*
            **/.gitignore
            **/readme.md
            **/template*.yaml
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
``` 

**Output: [\"dirA\",\"dirB\",\"\"]**

Thanks in advance,

**Comment by jackton1** [comment, marked as answer]
Hi @rsorelli-hedgepoint to exclude the current working directory denoted by a `.` from the output you can set `dir_names_exclude_current_dir` to `true`

### Example
```yml
...
      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v37.6.0
        with:
          ...
          dir_names_exclude_current_dir: true
          ...
```

Which appears to be set in your workflow file, I'll recommend upgrading to the latest version which should most likely resolve the bug 
 of outputting an empty string.

Let me know if a version upgrade doesn't fix the problem, you can [file an issue](https://github.com/tj-actions/changed-files/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bug_report.yaml&title=%5BBUG%5D+%3Ctitle%3E) and I'll take a look. Thanks
