### DISCUSSION TITLE
Get names of deleted directories in the root folder, but exclude this directory if something was deleted inside it

### DISCUSSION THREAD

**Discussion by AliaksandrRyzhou** [tj-actions/changed-files#1540] [Q&A]
Hi! Please help me. I've been playing around for a few days with tj-actions/changed-files and have one problem.
I have the following catalog structure:
```
── charts
│   ├── folder1
│   │   ├── file1
│   │   ├── file2
│   │   ├── file3
│   │   ├── subfolder1
│   │   │   └── subfile1
│   ├── folder2
│   │   ├── file1
│   │   ├── file2
│   │   ├── file3
│   │   ├── subfolder2
                └── subfile2
```

The idea is to get folder names with were deleted and folder names that have all_modified_files inside of themselves.
It's needed to know if we have to delete the chart or upgrade.
The problem is if I delete a `folder1` I'll see this folder name as the folder for an upgrade.
And if I delete a `subfolder1` or `subfile1/file1` inside of a `folder1` I'll see this folder name as a folder for deletion.

I have the following steps:

```
      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          path: ../charts
          json: true
          files: |
            ?
          files_ignore: |
            ?

      - name: Get deleted directories
        id: deleted-directories
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          path: ../charts
          json: true
          files: |
            ?
          files_ignore: |
            ?
```
I've been playing around with inputs `files` and `files_ignore` and tried a bunch of cases but haven't found yet the best approach. Does it work the same as gitignore? What pattern do I need to make work?
How can I monitor a folder deletion but ignore the deletion inside of it?
It's needed so that I can create two matrices after it. It works if I use all_changed_files but in this case, someone can change files inside `folder1` and `folder2` by deletion files, and the GitHub action won't see that the update is needed.
