### DISCUSSION TITLE
Not listing changed-files-specific

### DISCUSSION THREAD

**Discussion by relkarthi** [tj-actions/changed-files#1641] [Q&A] [answered]
```yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest  
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Get changed files in the mysql folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: mysql/*.{sql}  # Alternatively using: `docs/**` or `docs`

      - name: List all changed specific files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Run step if any file(s) in the mysql folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"

```
 
-- I'm trying the test the above action to verify if there are any .sql files got changed under mysql folder. This is for every PR. It is listing the files for  id: changed-files not for  id: changed-files-specific. 
          

Sample output :

Run for file in ; do
  for file in ; do
    echo "$file was changed"
  done
  shell

**Comment by jackton1** [comment, marked as answer]
HI @relkarthi, I'll suggest just using the `.sql` extension without braces since you aren't filtering multiple extensions.

E.g
```yml
      - name: Get changed files in the mysql folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: mysql/**.sql
```

`mysql/**.sql`: This would include all files and subfolders under the `mysql` folder
`mysql/*.sql`: This would only include files in the  `mysql` folder
