### DISCUSSION TITLE
Getting changes since last successful workflow run?

### DISCUSSION THREAD

**Discussion by depsypher** [tj-actions/changed-files#1735] [Q&A] [answered]
I'd like to get changes pushed since the last successful workflow run on any given branch. Not sure if it's easily achievable?

The general idea is that my app has frontend and backend code in the same repo and I only want to run (the 30+ min long) backend tests if the backend code has changed.

Looking at the examples I'm guessing there'd be a problem if I just took the changes since the last push, since a run could fail or be canceled and then the subsequent run on the next push wouldn't see the changes from the previous push.

**Comment by jackton1** [comment, marked as answer]
Hi @depsypher, I believe this feature is highlighted in the [example](https://github.com/tj-actions/changed-files?tab=readme-ov-file#on-pull_request-)

```yml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
         with:
           since_last_remote_commit: true 
```

In your case however I don’t think you’ll need to use this input because as you mentioned changes from recently pushed commits would not be compared when only comparing the last remote commit to the current one.

You can use the defaults with pull_request events or optionally specify a `base_sha` (supports branch or commit SHA) which would always be the starting point for the comparison.


### Example

```yml
on:
  pull_requests:
     branches:
       - main
       
…
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
```

**Comment by depsypher** [comment]
Thanks, ok yeah. We trigger on push rather than pull_request, not sure if that makes a difference. We deploy to a sandbox environment on pushes to the main branch (with successful workflow run i.e. all ci steps including tests pass). Likewise on pushes to a prod branch we deploy to production. In any case I guess I was hoping for a turn-key way of doing it without changing our workflow too much.

The scenario I'm worrying about is:
1. Dev A pushes bad backend changes to main branch, tests fail, deploy to sandbox (correctly) prevented.
2. Dev B then pushes frontend changes to main branch, changed-files since last push no longer include the backend changes from 1 so tests are not run, workflow succeeds and deploy to sandbox (incorrectly) proceeds.

Seems we'd have to keep track of the sha hash of the last successful workflow run on every branch that gets pushed and saving that state somewhere (external?) to be used as a base for the next comparison? Totally understandable if that's outside the scope of the action to keep track of, but just wanted to check if this was a common usecase and solved already.

**Reply by jackton1** [reply]
Hi, @depsypher based on your description if both the frontend and backend are in different directories that can be used to determine what needs to be deployed i.e deploy frontend changes when changes are made to the frontend directory and the same case applies to the backend.

But if you want to halt all deployments i.e. always diff files from the last successful run of the workflow then you can use this solution.

Search for: "Get all changed files using the last successful commit of the base branch" in the [Examples](https://github.com/tj-actions/changed-files?tab=readme-ov-file#examples-) for a full description.

```yml
...
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: nrwl/nx-set-shas@v3
        id: last_successful_commit_push
        with:
          main-branch-name: ${{ steps.branch-name.outputs.current_branch }} # Get the last successful commit for the current branch.
          workflow-id: 'test.yml'

      - name: Run changed-files with the commit of the last successful test workflow run
        id: changed-files-base-sha-push
        uses: tj-actions/changed-files@v40
        with:
          base_sha: ${{ steps.last_successful_commit_push.outputs.base }}
...
```
