### DISCUSSION TITLE
Execute command for changed flles in folder on push

### DISCUSSION THREAD

**Discussion by agenceKanvas** [tj-actions/changed-files#1776] [Q&A] [answered]
Hi ! 
Sorry if the question seems dumb but I'm new to github actions but still, I'd like to do that.
Right now I have a github action that run a command (staticrypt) in a folder on every push. 
Thats :
- Overkill
- Gives error for pages that doen't need the command to be runned. 

**What I'm trying to do :**
I have a WordPress setup that generates html version of pages and push them on GitHub when I want to. 
Some of these pages, in particular folders (folder1, folder2 and folder3) need to be encrypted.
I already have a working version of an action that does something lie that with staticrypt, but if I have 2 pages in folder1, it will run the staticrypt command for both pages, even if I only need to do that on only one. 
So I'd like to modify it, using changed-files action, to do that : 

When there is a push on the repo, check the files. Run the command "staticrypt .... $file" if the file is in one of those folders. 
Then commit the changes and push it on main. 

Could you help me with that ?

Thanks !

**Comment by agenceKanvas** [comment]
My work in progress would be : 
```
name: Staticrypt

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
     - name: Install Git
        run: |
          apt-get clean && apt-get update -y
          apt-get install -y git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install staticrypt
         run: npm install -g staticrypt@3.*
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            staticrypt $file -p ${{ secrets.DECRYPTION_PASSPHRASE }} -d NEEDTHEPATHOFTHEFILE --short
            --template-title "Connexion"
            --template-instructions "Espace restreint, merci d'entrer le mot de passe."
            --template-button "Ouvrir la page"
            --template-color-primary "#113e9f"
            --template-color-secondary "#e4e4e4"
            echo "$file was changed"
          done
       - name: Commit files
          run: |
            git config user.name github-actions
            git config user.email mathieu@kanvas.fr
            git add .
            git commit -m "encrypted files"
       - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            force: true
```

**Comment by jackton1** [comment, marked as answer]
Hi @agenceKanvas, based on your provided GitHub Actions workflow, here are some modifications you can make to achieve your desired outcome:

- Use [tj-actions/changed-files](https://github.com/tj-actions/changed-files) action to get the list of changed files restricted to only folder1, folder2, and folder3.
- Iterate over the changed files and run the [staticrypt](https://github.com/robinmoisson/staticrypt#installation) command only for the files in the specified folders.
- Commit the changes and push them to the main branch.

Here's an updated version of your workflow:
```yaml
name: Staticrypt

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            folder1/**
            folder2/**
            folder3/**

      - name: Install Git
        run: |
          apt-get clean && apt-get update -y
          apt-get install -y git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install staticrypt
        run: npm install -g staticrypt@3.*

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            staticrypt $file -p ${{ secrets.DECRYPTION_PASSPHRASE }} -d "$(dirname $file)" --short \
               --template-title "Connexion" --template-instructions "Espace restreint, merci d'entrer le mot de passe." \
               --template-button "Ouvrir la page" --template-color-primary "#113e9f" --template-color-secondary "#e4e4e4"
          done

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email mathieu@kanvas.fr
          git add .
          git commit -m "encrypted files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
```

> \[!NOTE]
>
> * Using  `force: true` could potentially overwrite changes made to the `main` branch, You might want to allow new commits to result in a new run instead of force pushing the current checked-out changes (in this case using the `pull_request` event is ideal so changes are pushed to the PR branch before they are merged into the main branch).
