### DISCUSSION TITLE
Check potentially missing files

### DISCUSSION THREAD

**Discussion by ObserverOfTime** [tj-actions/changed-files#1946] [Q&A] [answered]
I want to create a reusable workflow which can be used in repos that may or may not contain file `foo`.
I expect the `check-foo` step to be skipped if the file does not exist or has not been changed. Is this correct?
```yaml
    - uses: tj-actions/changed-files@v42
      id: changed-files
      with:
        files: foo
    - id: check-foo
      if: steps.changed-files.outputs.any_changed == 'true'
      run: ...
```
