### DISCUSSION TITLE
Matching directories with inner directories

### DISCUSSION THREAD

**Discussion by laysauchoa** [tj-actions/changed-files#1947] [Q&A] [answered]
Hi @jackton1 Thank you for this great action. I need some help to understand how to use the action for the following case:

I want to get changes only in a specific level of a directory that has inner directories.
```
├── A1
│   └── B
│       └── C
│           └── D
│               ├── hello.txt
│               └── bye.txt
```
Case 1) For example, if I rename ``B`` to ``new-B``, I'd like to have the output as:

created:
- A/new-B/
                        
deleted:
- A/B/
                        
updated:
- A/new-B

What I tried:
```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          output_renamed_files_as_deleted_and_added: true
          dir_names: true
          dir_names_deleted_files_include_only_deleted_dirs: true
          files: A/**/
```
Case 2) If I rename ``C`` to ``new-C``, I want to have as output:

created:
- A/B/new-C
                        
deleted:
- A/B/C
                        
updated:
- A/B/new-C

What I tried:
```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          output_renamed_files_as_deleted_and_added: true
          dir_names: true
          dir_names_deleted_files_include_only_deleted_dirs: true
          files: A/**/**/
```

I also tried ``dir_names_max_depth`` but this only affects the output not the track so it could track a change on path A/B/C/D and have a shorter output as A/B/ and so on. What would you advise in this case? Does it support regex?
