### DISCUSSION TITLE
Being able to read files

### DISCUSSION THREAD

**Discussion by Aetherinox** [tj-actions/changed-files#1964] [Q&A] [answered]
I'm looking at this action, and the other linked action for https://github.com/tj-actions/verify-changed-files

I haven't been able to find a definite answer between here and Google, but is their a way to get the full path to the raw pull request file so that I can run a script to view the text in that raw file and check for certain key words? I'm not sure if that has to be supported by the action, or if there's a way to pull the raw url through google actions itself.

The paths returned are the full local paths, but when I actually view the modified files in the pull request, the link goes to URLs such as `blob/b1bbe79c51fbaec3bac1bab6859fa2153bb1bff8/file.name.txt`

Right now I've got the basic iteration going

```
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
```

but I'm not sure what the proper way would be to tell the script to read the changed file, and not the target repo file.

**Comment by jackton1** [comment, marked as answer]
Hi @Aetherinox, Unfortunately you don’t get links with either action since the repository is cloned you get the absolute path to the changed file from the project root.

You can read the contents of the file using `cat` or any file reader. Let me know if that helps or if you need more information.

**Reply by Aetherinox** [reply]
Oh, do you mean I'm already in a scope where I can see the modified files for the PR, and not the original master branch.

**Reply by jackton1** [reply]
Yes

```yml
…
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: List all and show file contents of changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            cat $file  # show the file contents
          done
```
