### DISCUSSION TITLE
Get directory changed folders and exclude parent folder

### DISCUSSION THREAD

**Discussion by lays147** [tj-actions/changed-files#1971] [Q&A] [answered]
Hey all, I'm using this action, and I'm configuring it as follows:
```yaml
  filesChanged:
    runs-on: small-runner
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Get changed files in the kong--plugins folder
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: kong-plugins/**
          json: true
          escape_json: false
          dir_names: true
          dir_names_exclude_current_dir: true
``` 
The output is `["kong-plugins", "kong-plugins/foo"]` but I only want the subfolders like ["kong-plugins/foo"]. Already tried `path: kong-plugins` but the pipeline failed because I think that this var tries to find another git repository based on the docs. 
Which config would fit this scenario?

**Comment by jackton1** [comment, marked as answer]
Hi @lays147 there are a couple of approaches you can take 

1. Specify the path input `kong-plugins` but note the patterns would need to be changed to `"**"` or can be omitted since you will detect only changed files within the `kong-plugins` folder.
```yml
...
      - name: Get changed files in the kong-plugins folder
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          path: kong-plugins
          json: true
          escape_json: false
          dir_names: true
          dir_names_exclude_current_dir: true
```

2. Post-process the output from this action and filter out the `kong-plugins` folder
```yml
...
      - name: Filter out parent directory from output
        id: filter-output
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Use jq to filter out the 'kong-plugins' folder, assuming jq is available in your runner environment
          FILTERED_OUTPUT=$(echo $ALL_CHANGED_FILES | jq 'map(select(. != "kong-plugins"))')
          echo "::set-output name=filtered-files::$FILTERED_OUTPUT"
```

> Please provide the log output if you discover any errors with any of the suggested approaches

**Comment by lays147** [comment]
Well, this post-processing appears to be too much of a problem for a thing that should be simple, I found out that I can exclude inputs in a matrix, so I used this: 
```yaml
  tests:
    permissions:
      contents: read
    environment: staging
    needs: filesChanged
    strategy:
      matrix:
        folders: ${{ fromJson(needs.filesChanged.outputs.files) }}
        exclude:
          - folders: kong-plugins
 ```

When using `path: kong-plugins` the "cwd command" of the action failed saying that the path didn't existed :disappointed:
