### DISCUSSION TITLE
It would be possible to make this value a configurable parameter?

### DISCUSSION THREAD

**Discussion by Sandruz** [tj-actions/changed-files#2051] [Q&A] [answered]
![image](https://github.com/tj-actions/changed-files/assets/6418864/ac35efd2-7d7e-4d43-ab75-c94fe374a26c)

The situation happened because of a merge conflict in my PR.
I think in most of the cases just one try is enough. 
What do you think?

**Comment by jackton1** [comment, marked as answer]
Hi @Sandruz, this can be controlled via the `fetch_missing_history_max_retries` input using the latest [v44.2.0](https://github.com/tj-actions/changed-files/releases/tag/v44.2.0) release

```yml
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          fetch_missing_history_max_retries: 1
```
