### DISCUSSION TITLE
Getting changed files on a comment

### DISCUSSION THREAD

**Discussion by jonashoye** [tj-actions/changed-files#2117] [Q&A] [answered]
Hi. I have an action that is supposed to get the changed files in a PR, but also when there is a comment on the pr.
I have the triggers set up all good, but i am seeing some weird behaviour in the changed files output.
When a PR is created, it gets all the changed files. However, on comments, it only gets changed files in the last commit on the pr branch.

On comment:
`Retrieving changes between d82756 (pr_branch) → b0ca36 (pr_branch)`

on pr:
`Retrieving changes between 9d2cac(main) → b0ca36 (pr_branch)`

This is how the job is set up:
```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            dir_names: true
            json: true
            base_sha: ${{ github.event.pull_request.base.sha }}
```

I am really confused as to why i get mixxed results, whether its based on a pr(or commit to the pr branch), and when there's a comment made in the PR.

**Comment by jackton1** [comment]
Hi @jonashoye can you include the event you used to trigger the workflow?

**Comment by jonashoye** [comment]
@jackton1 sure, it looks something like this:

```
on:
  pull_request:
    branches: [main]
  issue_comment:                                     
    types: [created]
```

**Comment by jackton1** [comment, marked as answer]
Hi @jonashoye, I’ll suggest changing

```yml
base_sha: ${{ github.event.pull_request.base.sha }}
```

To

```yml
base_sha: main
```

The GitHub context values for [issue_comment](https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment) doesn’t include the pull_request object. 


Alternatively, you can change the event to [pull_request_review_comment](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request_review_comment) depending your use case.

**Comment by seccobo1** [comment]
Hey, I am facing a similar issue. Setting `base_sha` did not solve it for me. 

What I would like to achieve: compare latest PR commit to staging branch.

What actually happens: compares second last commit to staging to last commit to staging.

My setup looks something like this:
```
on:
  issue_comment:
    types: [created]

jobs:
  check-modified-directories:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run changed-files with dir_names
        id: modified-files-dir-names
        uses: tj-actions/changed-files@v44
        with:
          dir_names: "true"
          dir_names_exclude_current_dir: "true"
          dir_names_max_depth: "2"
          base_sha: staging

      - name: List all modified directories
        env:
          all_modified_files: ${{ steps.modified-files-dir-names.outputs.all_modified_files }}
        run: |
          for file in ${ALL_modified_FILES}; do
            echo "$file was modified"
          done
```

Any clue for me how to resolve @jackton1 ?

Thanks in advance!
