### DISCUSSION TITLE
Difference between any_changed and only_changed

### DISCUSSION THREAD

**Discussion by chadtomkiss** [tj-actions/changed-files#2210] [Q&A] [answered]
I have a step to get a list of changes in a directory:

```
- name: Get changed app files
    id: changed-files-app
    uses: tj-actions/changed-files@v44
    with:
      files: |
        app/**
```

If I change a file in `app` then:

```
any_changed: true
only_changed: false
```

In what scenario would `only_changed` be set to true?

My intention is to only run particular commands when files in `app` have changed but not in a different folder say `docs`

**Comment by jackton1** [comment, marked as answer]
Hi @chadtomkiss, with the following code

```yml
- name: Get changed app files
    id: changed-files-app
    uses: tj-actions/changed-files@v44
    with:
      files: |
        app/**
```

`any_changed`: This would be `true` if the full sets of commits being compared include a change to any files in the `app` folder, including subfolders. If the full sets of commits compared only include changes made to other files and folders outside the `app` folder, then `any_changed` would be `false`.


`only_changed`: On the other hand, this would be `true` only when the full sets of commits compared only include changes to the `app` folder if any other files change, then `only_changed` would be `false`.


You want to use `any_changed` for most use cases if you have a filter.

### Example Scenarios

#### Scenario 1: Changes in `app` Folder Only
- **Files Changed:** `app/main.py`, `app/utils/helper.py`

- **any_changed:** `true`
- **only_changed:** `true`

#### Scenario 2: Changes in `app` Folder and Other Folders
- **Files Changed:** `app/main.py`, `docs/readme.md`

- **any_changed:** `true`
- **only_changed:** `false`

#### Scenario 3: No Changes in `app` Folder
- **Files Changed:** `docs/readme.md`, `tests/test_main.py`

- **any_changed:** `false`
- **only_changed:** `false`

#### Scenario 4: Changes in Subfolders of `app`
- **Files Changed:** `app/subfolder/config.yaml`, `app/subfolder/utils.py`

- **any_changed:** `true`
- **only_changed:** `true`
