### DISCUSSION TITLE
How do I check if a submodule changed commit against the source branch?

### DISCUSSION THREAD

**Discussion by vib-etched** [tj-actions/changed-files#2217] [Q&A] [answered]
I'm using this action to get what files have changed when running a CI job. How does one check if the Submodule commit hash itself has changed?

My PR has the following change:
Submodule sw updated from f8e803 to 932876

I have tried this out by setting "exclude_submodules: false" in the action inputs. The submodule itself does not show up in the all_changed_files output.

Any help would be appreciated!

**Comment by jackton1** [comment, marked as answer]
HI @vib-etched, here’s how you can check for changes in a submodule path. 

```yaml
name: Check Submodule Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-submodule-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
          submodules: true  # Ensure submodules are included=

      - name: Get changed files including submodules
        id: changed-files
        uses: tj-actions/changed-files@v44
        # No need to set `exclude_submodules` as it defaults to `false`

      - name: Check if submodule changed
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q 'submodule-path'; then
            echo "Submodule has changed."
          else
            echo "No changes in submodule."
          fi
```

**Reply by vib-etched** [reply]
Thanks Tonye,

This is what happens when I try out something similar. 

```
- name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MACHINE_USER_TOKEN }}
     
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true
      - name: Determine changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          exclude_submodules: false
```

I see the following error message on checkout

` Error: Failed to fetch pull request branch. Please ensure "persist-credentials" is set to "true" when checking out the repository. See: https://github.com/actions/checkout#usage`


 I suspect this is not using the correct ssh credentials when  git fetching the submodule, is there a way to force ssh-based fetching in the action?
 
 We do something like this in our github workflow to force an ssh checkout on some actions:
 `          sed -rie 's,https://github\.com,ssh://git@github.com,' .gitmodules`
