### DISCUSSION TITLE
How to compare with the main branch when a PR is created, and then with the last commit before a new push if the PR is already there?

### DISCUSSION THREAD

**Discussion by rafrafek** [tj-actions/changed-files#2245] [Q&A] [answered]
I'm using `tj-actions/changed-files@v45` and need some guidance. When a pull request (PR) is created, I want to compare the changes against the main branch. If the PR already exists and a new push is made, I want to compare against the previous commit instead (the last commit from the PR before the push). Additionally, I want to ensure this action only runs within pull requests. How can I achieve this?

My action definition so far:
https://github.com/rafrafek/github-actions-dynamic-matrix/blob/main/.github/workflows/ci.yml

My example PR that should trigger the changes:
https://github.com/rafrafek/github-actions-dynamic-matrix/pull/6/files

Action results - didn't find any changes, but it should as there is a change to a Dockerfile file:
https://github.com/rafrafek/github-actions-dynamic-matrix/actions/runs/10496631750/job/29077718779

**Comment by jackton1** [comment, marked as answer]
Hi, @rafrafek. This is already supported, so you wouldn't need to calculate the `BASE_SHA.`

To accomplish this, you will need to set the input `since_last_remote_commit` to `true`.

```yaml
name: ci

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
      length: ${{ steps.prepare.outputs.length }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          files: |
            **/Dockerfile

      - name: Prepare
        id: prepare
        shell: python
        run: |
           ...
```

Excerpt from the [docs](https://github.com/tj-actions/changed-files?tab=readme-ov-file#on-pull_request-)

```yaml
      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 
```



For more details see the [inputs](https://github.com/tj-actions/changed-files?tab=readme-ov-file#inputs-%EF%B8%8F) section in the documentation.

**Reply by rafrafek** [reply]
Hi @jackton1, thank you for your answer. I updated my action definition to use `since_last_remote_commit: true`.

But the action still doesn't detect any changed files
https://github.com/rafrafek/github-actions-dynamic-matrix/actions/runs/10505503033/job/29103186811

for this PR where I changed a Dockerfile:
https://github.com/rafrafek/github-actions-dynamic-matrix/pull/8/files

Is my files definition correct?
```yaml
          files: |
            **/Dockerfile
```

**Reply by jackton1** [reply]
Hi @rafrafek, it looks like you have a bug in your code [`steps.changed-markdown-files.outputs.all_changed_files`](https://github.com/rafrafek/github-actions-dynamic-matrix/blob/main/.github/workflows/ci.yml#L45) needs to be the id you used for the tj-actions/changed-files action, which in this case would be `steps.changed-files.outputs.all_changed_files`

**Reply by jackton1** [reply]
Also, I'd like to point out that the output is a string separated by spaces and not a list, as implied by the code you have here, you don't need a default since the output defaults to an empty string.

Suggested implementation
```yml
          def discover() -> list[str]:
              for changed in "${{ steps.changed-files.outputs.all_changed_files }}".split(" "):
                  path = Path(changed)
                  if Path(path.parts[0]).is_dir():
                      yield path.parts[0]
```

**Reply by jackton1** [reply]
If you want the directory names, you need to enable the `dir_names` input which returns the parent directory name rather than the full path, including the filename. 

E.g
```yml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
           since_last_remote_commit: true
           dir_names: true
```

**Reply by rafrafek** [reply]
Thank you so much for all your help! I copied this action definition from https://github.com/meysam81/github-actions-dynamic-matrix and I'll try to contact the author to also fix it upstream :)

**Reply by jackton1** [reply]
This action also supports matrix outputs. For more on that, see this [example](https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-example.yml)

**Reply by rafrafek** [reply]
Thank you!!

> the output is a string separated by spaces and not a list

What if some of the paths contain a space? Like `/foo/my dir/Dockerfile`.

**Reply by rafrafek** [reply]
I think I figured it out. I'm using `separator: "\\n"`:

```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          separator: "\\n"
          files: |
            **/Dockerfile
      - name: Prepare
        id: prepare
        shell: python
        run: |
          import json
          import os
          from pathlib import Path
          from typing import Any, Generator


          def discover() -> Generator[str, Any, None]:
              all_changed_files = "${{ steps.changed-files.outputs.all_changed_files }}"
              if not all_changed_files:
                  return
              for changed in all_changed_files.split("\n"):
                  path = Path(changed)
                  if Path(path.parts[0]).is_dir():
                      yield path.parts[0]
```

But if handling spaces in paths is not required, it's better to use `.split()` rather than `.split(" ")` because in Python `.split(" ")` produces `['']` and `.split():` produces `[]`.

I proposed the changes upstream: https://github.com/meysam81/github-actions-dynamic-matrix/pull/1
