### DISCUSSION TITLE
Action doesn't track submodule changes

### DISCUSSION THREAD

**Discussion by Ilyas0Iks** [tj-actions/changed-files#2247] [Q&A] [answered]
Hello,

I try use actions to track changes in submodule

```     
     - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Changed files in pull request
        id: changed_submodule_files
        uses: actions/changed-files@v44
        
    - run: echo "${{ steps.changed_submodule_files.outputs.all_changed_files }}"
  ````
  
  in .gitmodules: 
  ```
  [submodule "subproject"]
	path = subproject
	url = ssh://git@own_github.com/project/subproject.git
```

in pull request diff:

![image](https://github.com/user-attachments/assets/b1a2aef8-4e44-4dec-bd7b-4446ab9694e3)

but action doesn't return path for changed submodule

probably, issue is related with ssh url in .gitmodules, but i don't want change ssh to https in protocol.

   I checked https://github.com/tj-actions/changed-files/discussions/2217 with similar issue,  WA - ok with sed, but i wan't use WA, expect same result by action
