### DISCUSSION TITLE
Get content of deleted files

### DISCUSSION THREAD

**Discussion by aristonlim** [tj-actions/changed-files#2253] [Q&A] [answered]
Hi, I used `deleted_files` variable to get a list of deleted files on merge. Is there a variable to get the content of the deleted files (the latest one before deletion)?

Thank you.

**Comment by jackton1** [comment, marked as answer]
To get the contents of deleted files, you can use these inputs

```yml
    # Recover deleted files.
    # Type: boolean
    # Default: "false"
    recover_deleted_files: ''

    # Recover deleted files to a 
    # new destination directory, defaults to 
    # the original location. 
    # Type: string
    recover_deleted_files_to_destination: ''
```

See the [docs](https://github.com/tj-actions/changed-files?tab=readme-ov-file#inputs-%EF%B8%8F) for more information.

You can view a working example [here](https://github.com/tj-actions/changed-files/blob/8d5497eb10aaffcff15941fd5203c6bef3f516ed/.github/workflows/test.yml#L784-L974)
