### DISCUSSION TITLE
List the file differences between the current branch commit and the common ancestor with another branch.

### DISCUSSION THREAD

**Discussion by CustomEntity** [tj-actions/changed-files#2303] [Q&A] [answered]
Hello, we have a use case where we need to list the file differences of the current commit branch (After a push/pull-request in any branch) with our “Dev” branch and we'd like to know if it's possible to do this with your action.

Currently we're doing a `git merge-base` to find the common ancestor between the branch and the dev branch and we're doing a git diff with that ancestor but we'd like to use your action.

Thanks in advance

**Comment by jackton1** [comment, marked as answer]
Hi @CustomEntity, you can simply use the example provided in the [docs](https://github.com/tj-actions/changed-files#using-local-git-directory-)

```yaml
name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the dev branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
```
