### DISCUSSION TITLE
How do I get the commits SHA of the two compared commits used in the action?

### DISCUSSION THREAD

**Discussion by luciano-buono** [tj-actions/changed-files#2347] [Q&A]
Hi, I'm using the action to check if some files (changelogs) were updated in a specific branch.
If they were, I show the modified/added lines and send them to a Slack channel

This is the general idea of my workflow:

```yaml
name: notify-changelog-update

on:
  push:
    branches:
      - staging

jobs:
  check-changelog:
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed file in folder
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/changelog1.md
            src/changelog2.md

      - name: Diff the changed lines in file
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          {
            echo 'diff_changes_1<<EOF'
            git diff --unified=0 HEAD~1 -- src/changelog1.md | sed '/^diff/,/^@@/ {d}' | sed '/^@@/ {d}' | sed 's/^+//' | sed 's/"/'\''/g'
            echo EOF
          } >> "$GITHUB_ENV"
          {
            echo 'diff_changes_2<<EOF'
            git diff --unified=0 HEAD~1 -- src/changelog2.md | sed '/^diff/,/^@@/ {d}' | sed '/^@@/ {d}' | sed 's/^+//' | sed 's/"/'\''/g'
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Create the Slack Payload
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          SLACK_PAYLOAD: ...

      - name: Slack Notification internal
        uses: rtCamp/action-slack-notify@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          SLACK_CUSTOM_PAYLOAD: ${{ env.SLACK_PLAYLOAD }}
```

As I understand, the `since_last_remote_commit` is set to true by default `on push` workfows.
This means that a FastForward merge onto staging branch would still be checked against the last remote commit in Github, am I right?

The main problem is that my `git diff` implementation is flawed in that case. Since I'm using a 

`git diff --unified=0 HEAD~1`

this means that the `tj-actions/changed-files` will compare using the 2 correct commits, but my git diff won't.
I would need to get `BASE_SHA` but the action does not provide an output with this information.

Ideally, I could use something like:

`git diff --unified=0 ${{ steps.changed-files.outputs.SHA_BASE }} ${{ steps.changed-files.outputs.SHA_REF }}`

How could I achieve this?
