### DISCUSSION TITLE
Get the diff of the changed files

### DISCUSSION THREAD

**Discussion by IchordeDionysos** [tj-actions/changed-files#2381] [Ideas]
### Problem:

We want to check the actual diff of the files changed instead of just checking which files have changed.

e.g. we want to ensure that only specific changes have been made in a PR before continuing an action step.

More concretely, only approve a release-please PR when only the CHANGELOG.md and only the version has been changed in the PR.

This diff should be accepted:
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/f065e355-6ecf-44d6-bdb5-b924934c1acf" />

This should not:
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/2ad9cab2-2de1-4eae-b71d-856bae5c27ae" />

To achieve that it would be cool if the actual diff would be provided as output.

### Solutions explored:

Such checks have been integrated into other actions, though those are often quite restrictive and the checks have been done directly in some NodeJS code, see this example:
https://github.com/googleapis/repo-automation-bots/blob/main/packages/auto-approve/src/process-checks/node/release.ts#L52-L63

There is a different action that does provide the diffs as output which could then be used in a follow-up step to analyse the diffs:
`git-diff-action` does return that information in such a format:
https://github.com/marketplace/actions/git-diff-action#json-diff-output-

e.g.:

```yaml
- uses: GrantBirki/git-diff-action@vX.X.X
  id: git-diff-action
  with:
    json_diff_file_output: diff.json
    file_output_only: "true"
- uses: actions/github-script@v7
  id: changed-only-version
  with:
    script: |
      const data = require('${{steps.git-diff-action.outputs.json-diff-path}}');
      const file = data.files.find(file => file.path === 'package.json');
      const chunk = file.chunks[0];
      const changes = chunk.changes.filter(change => change.type !== 'UnchangedLine');
      const changedVersion = changes[0].content.match(/^\s*"version":\s*"\d+\.\d+\.\d+",?\s*$/)

      return file.chunks.length === 1 && changes.length === 1 && changedVersion !== null;
    result-encoding: string
- id: approve-pr
  # Only approve when the allowed changes have been made
  if: steps.changed-files.outputs.only_changed == 'true' && steps.changed-only-version.outputs.result == 'true'
```

### Possible solution required to solve the problem:

However, it would be nice to only have to use one action, not multiple ones.
And `changed-files` simply provides a lot more features compared to `git-diff-action`.

So having some output of the actual diff would be helpful, that you can do:

```yaml
- name: Get release-please changed files
  id: changed-files
  uses: tj-actions/changed-files@v45
  with:
    files: |
      /.github/release-please-manifest.json
      **/package.json
      **/CHANGELOG.md
- uses: actions/github-script@v7
  id: changed-only-version
  with:
    script: |
      // Only get diffs for the particular type of change (also possible modified_, deleted_, ...)
      const data = JSON.parse('${{steps.changed-files.outputs.changed_file_diff}'); // Or some file path to read this from
      const file = data.files.find(file => file.path === 'package.json');
      const chunk = file.chunks[0];
      const changes = chunk.changes.filter(change => change.type !== 'UnchangedLine');
      const changedVersion = changes[0].content.match(/^\s*"version":\s*"\d+\.\d+\.\d+",?\s*$/)

      return file.chunks.length === 1 && changes.length === 1 && changedVersion !== null;
    result-encoding: string
- id: approve-pr
  # Only approve when the allowed changes have been made
  if: steps.changed-files.outputs.only_changed == 'true' && steps.changed-only-version.outputs.result == 'true'
```
_The syntax can be different_

If alternatively it would be possible to let those checks be done by the action that would be even nicer.

```yaml
- name: Get release-please changed files
  id: changed-files
  uses: tj-actions/changed-files@v45
  with:
    files: |
      /.github/release-please-manifest.json
      **/package.json
      **/CHANGELOG.md
    diff_checks_yaml: |
      package_json_version:
        files:
          - **/package.json
        allowed_changes:
          - ^\s*"version":\s*"\d+\.\d+\.\d+",?\s*$
```
Though for a first version, I think a simple output would be enough. Especially if the types of checks people would want to do is not clear yet.
