### DISCUSSION TITLE
Any way to fetch all changed files in a PR's lifetime?

### DISCUSSION THREAD

**Discussion by danielap-ma** [tj-actions/changed-files#2430] [Q&A] [answered]
Scenario:

Say I have a PR with the following commit history:

Commit #1:
Introduce a change to file a.txt

Commit #2:
Introduce a change to file b.txt

Commit #3:
Revert the change to file b.txt

Commit #4:
Another change (not revert) to file a.txt

The output of _all_changed_files_ will be a.txt, which makes sense, since that's the only current diff from the target branch. But is there a way to detect b.txt had changes along the way too? I know it's possible to compare two specific commit hashes, but that's not really a viable solution.

Thanks in advance!

**Comment by jackton1** [comment, marked as answer]
Hi @danielap-ma, yes that is supported by default for a pull request event.

For more information about the implementation details. See https://github.com/tj-actions/changed-files?tab=readme-ov-file#using-local-git-directory-

**Reply by danielap-ma** [reply]
Hi @jackton1, I must be missing it then since I don't see a flag which accomplishes this.
Can you elaborate please?

Thanks!

**Reply by jackton1** [reply]
Hi @danielap-ma, I recommend creating a workflow file with the following content. After that, you can create a new pull request that triggers the workflow.

```yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
```

Each push to the pull request branch, for example, changing `a.txt` would echo `"a.txt was changed"` and any subsequent push to the pull request branch would now include all files that have changed, for example, `"a.txt was changed"` as well as `"b.txt was changed"` and so on.
