### DISCUSSION TITLE
Resource not accessible by integration - how to force the action to use the local .git?

### DISCUSSION THREAD

**Discussion by dyasny** [tj-actions/changed-files#2447] [Q&A] [answered]
I am trying to use the action, but it is failing with the following error:

```
  Using GitHub's REST API to get changed files
  Getting changed files from GitHub API...
  Error: Resource not accessible by integration - https://docs.github.com/rest/pulls/pulls#list-pull-requests-files
List all changed files
```

Expanded action:

```
Run tj-actions/changed-files@v45
  with:
    separator:  
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:  
    files_from_source_file_separator: 
  
    files_separator: 
  
    files_yaml_from_source_file_separator: 
  
    files_ignore_yaml_from_source_file_separator: 
  
    files_ignore_separator: 
  
    files_ignore_from_source_file_separator: 
  
    path: .
    quotepath: true
    diff_relative: true
    dir_names: false
    dir_names_exclude_current_dir: false
    dir_names_include_files_separator: 
  
    dir_names_deleted_files_include_only_deleted_dirs: false
    json: false
    escape_json: true
    safe_output: true
    fetch_depth: [2](https://github.com/IrreducibleOSS/infra/actions/runs/13593880846/job/38006262070#step:4:2)5
    skip_initial_fetch: false
    fetch_additional_submodule_history: false
    since_last_remote_commit: false
    write_output_files: false
    output_dir: .github/outputs
    output_renamed_files_as_deleted_and_added: false
    recover_deleted_files: false
    recover_files_separator: 
  
    recover_files_ignore_separator: 
  
    token: ***
    api_url: https://api.github.com
    use_rest_api: false
    fail_on_initial_diff_error: false
    fail_on_submodule_diff_error: false
    negation_patterns_first: false
    matrix: false
    exclude_submodules: false
    fetch_missing_history_max_retries: [20](https://github.com/IrreducibleOSS/infra/actions/runs/13593880846/job/38006262070#step:4:20)
    use_posix_path_separator: false
    tags_pattern: *
```

I am calling it in a very simple way:

```
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files in ${{ matrix.paths }}
        id: changed-files
        uses: tj-actions/changed-files@v45

```
