### ISSUE TITLE
[BUG] v35 started failing while fetching remote refs

### ISSUE THREAD

**Issue by planeiii-te** [tj-actions/changed-files#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The action bails after it attempts to fetch remote refs.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/91621767/224164040-7d66fa69-8944-4d30-ad97-e27f641dd8a7.png">

I tried running in debug mode and didn't see any additional information provided.

### To Reproduce

```yaml
jobs:
  deprecations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          files: |
            bases/**/*.yaml
            environments/**/*.yaml
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Should present changed files.

### Relevant log output

```shell
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/fccae68c-f518-4aa7-b5aa-b15b6cf3ffd0.sh
::group::changed-files-diff-sha
changed-files-diff-sha
  ##[debug]Resolving repository path: /home/runner/work/argo-deployment/argo-deployment/.
  Verifying git version...
  Valid git version found: (2.39.2)
  Running on a pull request event...
  Fetching remote refs...
  Error: Process completed with exit code 1.
```

### Anything else?

I've re-run this about 5 hours apart and it's still failing the same way.

[logs_499.zip](https://github.com/tj-actions/changed-files/files/10937958/logs_499.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
