### ISSUE TITLE
[BUG] all_old_new_renamed_files Gets all files renamed files from history

### ISSUE THREAD

**Issue by twcchu** [tj-actions/changed-files#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When getting `all_old_new_renamed_files`, a list of all previous renamed files is listed, even though the changes have been pushed to main. 

### To Reproduce

Beginning File Structure:
```
deploys
    - example.tfvars
    - es.tfvars
    - noceng.tfvars
```
1. Change file name `example.tfvars` to `example2.tfvars`
2. Run github action
```      
- name: Save Changed tfvars Files
   id: files
   uses: tj-actions/changed-files@v35.7.1
   with:
     files: |
       deploys/*.tfvars
     include_all_old_new_renamed_files: 'true'

- name: Print renamed files
  run: |
  echo "all_old_new_renamed_files=${{ steps.files.outputs.all_old_new_renamed_files }}"
  echo "only_renamed_files=${{ steps.files.outputs.renamed_files }}"
```
3. Check output
```
all_old_new_renamed_files=deploys/example.tfvars,deploys/example2.tfvars deploys/es1.tfvars,deploys/es.tfvars deploys/es.tfvars,deploys/es1.tfvars deploys/netops_observability.tfvars,deploys/noceng.tfvars

only_renamed_files=deploys/example2.tfvars
```
4. Change file name back from `example2.tfvars` to `example.tfvars` and run Action
5. Check output 
```
all_old_new_renamed_files=deploys/example.tfvars,deploys/example2.tfvars deploys/example2.tfvars,deploys/example.tfvars deploys/es1.tfvars,deploys/es.tfvars deploys/es.tfvars,deploys/es1.tfvars deploys/netops_observability.tfvars,deploys/noceng.tfvars

only_renamed_files=
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Step 3:
```
all_old_new_renamed_files=deploys/example.tfvars,deploys/example2.tfvars

only_renamed_files=deploys/example2.tfvars
```

Step 5:
```
all_old_new_renamed_files=

only_renamed_files=
```

### Relevant log output

```shell
changed-files
   Retrieving changes between ### (main) → ### (PLAT)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by twcchu** [comment]
My be similar to https://github.com/tj-actions/changed-files/issues/972 but already using latest version.

**Comment by jackton1** [comment]
@twcchu Curious are you making the changes (rename) in a PR that hasn't been merged to the base branch ?

Example 

> Branch (main) ← PR (my-feat) [Rename 1, Rename 2, ...]

**Comment by jackton1** [comment]
From your request, I assume you are trying to get renamed file for the last change 

i.e 
> 4. Change file name back from example2.tfvars to example.tfvars and run Action

Which would output 
> all_old_new_renamed_files=deploys/example.tfvars,deploys/example2.tfvars

To achieve this you can ideally compare the last remote commit to the current commit which included the rename from example2.tfvars back to example.tfvars 

```yml
- name: Get Changed tfvars Files
   id: files
   uses: tj-actions/changed-files@v35.7.1
   with:
     files: deploys/*.tfvars
     include_all_old_new_renamed_files: true
     since_last_remote_commit: true
```
