### ISSUE TITLE
[BUG] invalid format delimiter 'ghadelimiter_1a075742-5378-49bd-baa8-36495976815c' not found before end of file

### ISSUE THREAD

**Issue by MattFaz** [tj-actions/changed-files#1046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have the following step in a Github action:

```yaml
      - name: Get Changed Files
        id: changedFiles
        # uses: tj-actions/changed-files@v11
        uses: tj-actions/changed-files@v35
        with:
          files: force-app/**
          files_ignore: |
            '**/*.md'
            '**/*.yml'
          since_last_remote_commit: true 
```

### To Reproduce

Using the below workflow:

```yml
name: Deploy to salesforce

on:
  push:
    # branches: [develop, uat, main] 
    # TODO: Remove workflows for Deployment
    branches: [workflows, develop, uat, main]
    paths: 'force-app/**'
  workflow_dispatch:
    inputs:
      org:
        description: 'Salesforce Org'
        required: true
        options: [QA, UAT, Production]
      testLevel:
        description: 'Test Level'
        required: true
        options: [RunLocalTests, NoTestRun, RunSpecifiedTests]
        default: NoTestRun
      testClasses:
        description: 'Enter the test classes to run (comma separated)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Ensure testLevel is set and classes provided if RunSpecifiedTests was selected
      - name: Validate Test Level
        run: |
          if [ -z "${{ github.event.inputs.testLevel }}" ]; then
            echo "testLevel input is missing, setting to NoTestRun"
            echo "testLevel=NoTestRun" >> $GITHUB_ENV
          else
            echo "testLevel=${{ github.event.inputs.testLevel }}" >> $GITHUB_ENV
          fi

          if [[ "${{ env.testLevel }}" == "RunSpecifiedTests" && -z "${{ github.event.inputs.TestClasses }}" ]]; then
            echo "Error: testClasses input must be provided when testLevel is 'RunSpecifiedTests'"
            exit 1
          fi

      # TODO: Remove branch workflows for Deployment
      # Determine the SFDX Auth URL
      - name: Determine SFDX Auth URL
        run: |
          if  [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            case ${{ github.event.inputs.org }} in
              "Production")
                echo ${{ secrets.PROD_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              "UAT")
                echo ${{ secrets.UAT_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              "QA")
                echo ${{ secrets.QA_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              *)
                echo "Error: Invalid Org input."
                exit 1 ;;
            esac
          else
            case ${{ github.ref }} in
              "refs/heads/main")
                echo ${{ secrets.PROD_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              "refs/heads/uat")
                echo ${{ secrets.UAT_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              "refs/heads/develop")
                echo ${{ secrets.QA_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              "refs/heads/workflows")
                echo ${{ secrets.QA_SFDX_AUTH_URL }} > ./sfdx_auth.txt ;;
              *)
                echo "Error: Invalid branch."
                exit 1 ;;
            esac
          fi
      
      # Ensure SFDX Auth URL has been set
      - name: Validate SFDX Auth URL
        run: |
          if [ ! -f ./sfdx_auth.txt ] || [ -z "$(cat ./sfdx_auth.txt)" ]; then
            echo "Error: SFDX_AUTH_URL is missing"
            exit 1
          fi

      # Install SFDX CLI
      - name: Install SFDX CLI
        run: npm install sfdx-cli --global --silent    
      
      # Authenticate with SFDX
      - name: Authenticate with SFDX
        run: |
          sfdx auth:sfdxurl:store -f ./sfdx_auth.txt -a sfOrg -d
          
      # Get list of added and modified files excluding .md and .yml files
      - name: Get Changed Files
        id: changedFiles
        # uses: tj-actions/changed-files@v11
        uses: tj-actions/changed-files@v35
        with:
          files: force-app/**
          files_ignore: |
            '**/*.md'
            '**/*.yml'
          since_last_remote_commit: true 
      
      # List out all changed files
      - name: List all changed files
        run: |
          for file in ${{ steps.changedFiles.outputs.all_modified_files }}; do
            echo "$file was changed"
          done
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Successfully complete as it does using `@v11`

### Relevant log output

```shell
~/prod/ap-crm-sf workflows ⇡2 !1 ❯ act push -W .github/workflows/cd.yml --input-file test.input --secret-file test.secrets
[Deploy to salesforce/deploy] 🚀  Start image=catthehacker/ubuntu:act-latest
[Deploy to salesforce/deploy]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Deploy to salesforce/deploy]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Deploy to salesforce/deploy]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Deploy to salesforce/deploy]   ☁  git clone 'https://github.com/tj-actions/changed-files' # ref=v35
[Deploy to salesforce/deploy] ⭐ Run Pre Get Changed Files
[Deploy to salesforce/deploy]   ☁  git clone 'https://github.com/tj-actions/glob' # ref=v16.12
[Deploy to salesforce/deploy]   ☁  git clone 'https://github.com/tj-actions/json2file' # ref=v1.4.0
[Deploy to salesforce/deploy] ⭐ Run Pre Generate output files
[Deploy to salesforce/deploy]   ✅  Success - Pre Generate output files
[Deploy to salesforce/deploy]   ✅  Success - Pre Get Changed Files
[Deploy to salesforce/deploy] ⭐ Run Main Checkout repository
[Deploy to salesforce/deploy]   🐳  docker cp src=/Users/prod/ap-crm-sf/. dst=/Users/prod/ap-crm-sf
[Deploy to salesforce/deploy]   ✅  Success - Main Checkout repository
[Deploy to salesforce/deploy] ⭐ Run Main Validate Test Level
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
[Deploy to salesforce/deploy]   ✅  Success - Main Validate Test Level
[Deploy to salesforce/deploy]   ⚙  ::set-env:: testLevel=NoTestRun
[Deploy to salesforce/deploy] ⭐ Run Main Determine SFDX Auth URL
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=
[Deploy to salesforce/deploy]   ✅  Success - Main Determine SFDX Auth URL
[Deploy to salesforce/deploy] ⭐ Run Main Validate SFDX Auth URL
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=
[Deploy to salesforce/deploy]   ✅  Success - Main Validate SFDX Auth URL
[Deploy to salesforce/deploy] ⭐ Run Main Install SFDX CLI
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=
[Deploy to salesforce/deploy]   ✅  Success - Main Install SFDX CLI
[Deploy to salesforce/deploy] ⭐ Run Main Authenticate with SFDX
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=
| Successfully authorized XXXXX with org ID XXXX
[Deploy to salesforce/deploy]   ✅  Success - Main Authenticate with SFDX
[Deploy to salesforce/deploy] ⭐ Run Main Get Changed Files
[Deploy to salesforce/deploy]   🐳  docker cp src=/Users/.cache/act/tj-actions-changed-files@v35/ dst=/var/run/act/actions/tj-actions-changed-files@v35/
[Deploy to salesforce/deploy] ⭐ Run Main # "Calculating the previous and current SHA..."
bash $GITHUB_ACTION_PATH/diff-sha.sh
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/changedFiles-composite-changed-files-diff-sha.sh] user= workdir=
[Deploy to salesforce/deploy]   ❓  ::group::changed-files-diff-sha
[Deploy to salesforce/deploy]   💬  ::debug::Resolving repository path: /Users/prod/ap-crm-sf/.
| Verifying git version...
| Valid git version found: (2.40.0)
| Running on a push event...
[Deploy to salesforce/deploy]   💬  ::debug::Getting HEAD SHA...
[Deploy to salesforce/deploy]   💬  ::debug::Verifying the current commit SHA: 25918fb52d3d45d8249ed560f3cb3e41c30f2094
[Deploy to salesforce/deploy]   💬  ::debug::Current SHA: 25918fb52d3d45d8249ed560f3cb3e41c30f2094
[Deploy to salesforce/deploy]   💬  ::debug::Target branch workflows...
[Deploy to salesforce/deploy]   💬  ::debug::Current branch workflows...
[Deploy to salesforce/deploy]   💬  ::debug::Verifying the previous commit SHA: 22a44c373bb80d392b06ccb9003427bea9024e3d
[Deploy to salesforce/deploy]   ❓  ::endgroup::
[Deploy to salesforce/deploy]   ✅  Success - Main # "Calculating the previous and current SHA..."
bash $GITHUB_ACTION_PATH/diff-sha.sh
[Deploy to salesforce/deploy]   ⚙  ::set-output:: previous_sha=22a44c373bb80d392b06ccb9003427bea9024e3d
[Deploy to salesforce/deploy]   ⚙  ::set-output:: current_sha=25918fb52d3d45d8249ed560f3cb3e41c30f2094
[Deploy to salesforce/deploy]   ⚙  ::set-output:: diff=..
[Deploy to salesforce/deploy]   ⚙  ::set-output:: target_branch=workflows
[Deploy to salesforce/deploy]   ⚙  ::set-output:: current_branch=workflows
[Deploy to salesforce/deploy] ⭐ Run Main Glob match
[Deploy to salesforce/deploy]   🐳  docker cp src=/Users/.cache/act/tj-actions-glob@v16.12/ dst=/var/run/act/actions/tj-actions-glob@v16.12/
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[node /var/run/act/actions/tj-actions-glob@v16.12/dist/index.js] user= workdir=
[Deploy to salesforce/deploy]   💬  ::debug::file patterns: force-app/**
[Deploy to salesforce/deploy]   💬  ::debug::excluded file patterns: !'**/*.md'%0A!'**/*.yml'
[Deploy to salesforce/deploy]   💬  ::debug::file patterns: /Users/prod/ap-crm-sf/force-app/**%0A!/Users/prod/ap-crm-sf/'**/*.md'%0A!/Users/prod/ap-crm-sf/'**/*.yml'%0A!/Users/prod/ap-crm-sf/.git/**%0A!/Users/prod/ap-crm-sf/**/node_modules/**%0A!/Users/prod/ap-crm-sf/node_modules/**
[Deploy to salesforce/deploy]   💬  ::debug::followSymbolicLinks 'true'
[Deploy to salesforce/deploy]   💬  ::debug::matchDirectories 'true'
[Deploy to salesforce/deploy]   💬  ::debug::followSymbolicLinks 'true'
[Deploy to salesforce/deploy]   💬  ::debug::implicitDescendants 'true'
[Deploy to salesforce/deploy]   💬  ::debug::matchDirectories 'true'
[Deploy to salesforce/deploy]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[Deploy to salesforce/deploy]   💬  ::debug::Search path '/Users/prod/ap-crm-sf/force-app'
[Deploy to salesforce/deploy]   💬  ::debug::gitignore file patterns: /Users/prod/ap-crm-sf/temp.sh%0A/Users/prod/ap-crm-sf/temp.json%0A/Users/prod/ap-crm-sf/.env%0A/Users/prod/ap-crm-sf/test.input%0A/Users/prod/ap-crm-sf/test.secrets%0A/Users/prod/ap-crm-sf/test.env%0A/Users/prod/ap-crm-sf/manifest/**%0A!/Users/prod/ap-crm-sf/manifest/build/destructiveChangesPost.xml%0A!/Users/prod/ap-crm-sf/manifest/build/destructiveChangesPre.xml%0A/Users/prod/ap-crm-sf/orgs/**%0A/Users/prod/ap-crm-sf/report/**%0A/Users/prod/ap-crm-sf/script/**%0A/Users/prod/ap-crm-sf/.classpath%0A/Users/prod/ap-crm-sf/.project%0A/Users/prod/ap-crm-sf/.salesforce%0A/Users/prod/ap-crm-sf/node_modules%0A/Users/prod/ap-crm-sf/.idea%0A/Users/prod/ap-crm-sf/.tern-project%0A/Users/prod/ap-crm-sf/.settings%0A/Users/prod/ap-crm-sf/.history%0A/Users/prod/ap-crm-sf/.history/**%0A/Users/prod/ap-crm-sf/.history*%0A/Users/prod/ap-crm-sf/.sfdx%0A/Users/prod/ap-crm-sf/.localdevserver%0A/Users/prod/ap-crm-sf/.sf%0A/Users/prod/ap-crm-sf/jsconfig.json%0A/Users/prod/ap-crm-sf/logs%0A/Users/prod/ap-crm-sf/*.log%0A/Users/prod/ap-crm-sf/npm-debug.log*%0A/Users/prod/ap-crm-sf/yarn-debug.log*%0A/Users/prod/ap-crm-sf/yarn-error.log*%0A/Users/prod/ap-crm-sf/node_modules%0A/Users/prod/ap-crm-sf/yarn.lock%0A/Users/prod/ap-crm-sf/.eslintcache%0A/Users/prod/ap-crm-sf/.DS_Store%0A/Users/prod/ap-crm-sf/Thumbs.db%0A/Users/prod/ap-crm-sf/ehthumbs.db%0A/Users/prod/ap-crm-sf/[Dd]esktop.ini%0A/Users/prod/ap-crm-sf/$RECYCLE.BIN%0A/Users/prod/ap-crm-sf/.vscode/*%0A!/Users/prod/ap-crm-sf/.vscode/extensions.json%0A!/Users/prod/ap-crm-sf/.vscode/settings.json%0A/Users/prod/ap-crm-sf/.vim-force.com%0A/Users/prod/ap-crm-sf/coverage%0A!/Users/prod/ap-crm-sf/.git/**%0A!/Users/prod/ap-crm-sf/**/node_modules/**%0A!/Users/prod/ap-crm-sf/node_modules/**
[Deploy to salesforce/deploy]   💬  ::debug::followSymbolicLinks 'true'
[Deploy to salesforce/deploy]   💬  ::debug::matchDirectories 'true'
[Deploy to salesforce/deploy]   💬  ::debug::followSymbolicLinks 'true'
[Deploy to salesforce/deploy]   💬  ::debug::implicitDescendants 'true'
[Deploy to salesforce/deploy]   💬  ::debug::matchDirectories 'true'
[Deploy to salesforce/deploy]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[Deploy to salesforce/deploy]   💬  ::debug::Search path '/Users/prod/ap-crm-sf'
| [command]/usr/bin/git rev-parse --show-toplevel
| /Users/prod/ap-crm-sf
[Deploy to salesforce/deploy]   💬  ::debug::top level directory: /Users/prod/ap-crm-sf
| [command]/usr/bin/git diff --diff-filter=D --name-only 22a44c373bb80d392b06ccb9003427bea9024e3d..25918fb52d3d45d8249ed560f3cb3e41c30f2094
[Deploy to salesforce/deploy]   💬  ::debug::deleted files: 
| Successfully created paths-output-file: /tmp/21b7aa49-824c-42e0-9ff1-4d0ce2f7f4c2.txt
[Deploy to salesforce/deploy]   ✅  Success - Main Glob match
[Deploy to salesforce/deploy] invalid format delimiter 'ghadelimiter_14945122-cd08-4f4a-9c9e-8f7a92b1853d' not found before end of file
[Deploy to salesforce/deploy] ⭐ Run Main bash $GITHUB_ACTION_PATH/get-changed-paths.sh
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/changedFiles-composite-changed-files.sh] user= workdir=
[Deploy to salesforce/deploy]   ❓  ::group::changed-files
| Resolving repository path: /Users/prod/ap-crm-sf/.
| Retrieving changes between 22a44c373bb80d392b06ccb9003427bea9024e3d (workflows) → 25918fb52d3d45d8249ed560f3cb3e41c30f2094 (workflows)
[Deploy to salesforce/deploy]   💬  ::debug::Added files: 
[Deploy to salesforce/deploy]   💬  ::debug::Copied files: 
[Deploy to salesforce/deploy]   💬  ::debug::Deleted files: 
[Deploy to salesforce/deploy]   💬  ::debug::Modified files: .github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   💬  ::debug::Renamed files: 
[Deploy to salesforce/deploy]   💬  ::debug::Type Changed files: 
[Deploy to salesforce/deploy]   💬  ::debug::Unmerged files: 
[Deploy to salesforce/deploy]   💬  ::debug::Unknown files: 
[Deploy to salesforce/deploy]   💬  ::debug::All changed and modified files: .github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   💬  ::debug::All changed files: .github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   💬  ::debug::All modified files: .github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ❓  ::endgroup::
[Deploy to salesforce/deploy]   ✅  Success - Main bash $GITHUB_ACTION_PATH/get-changed-paths.sh
[Deploy to salesforce/deploy]   ⚙  ::set-output:: renamed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: type_changed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_changed_and_modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_changed_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: outputs_extension=txt
[Deploy to salesforce/deploy]   ⚙  ::set-output:: copied_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: deleted_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: added_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: unmerged_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: unknown_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_old_new_renamed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: other_modified_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: unmerged_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: added_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: deleted_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: renamed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: unknown_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_changed_and_modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: any_changed=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: only_changed=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: other_changed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: copied_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: type_changed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: other_deleted_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: any_modified=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: only_modified=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: any_deleted=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_changed_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: only_deleted=
[Deploy to salesforce/deploy]   ❌  Failure - Main Get Changed Files
[Deploy to salesforce/deploy]   ⚙  ::set-output:: added_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: deleted_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_changed_and_modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_changed_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: outputs_extension=txt
[Deploy to salesforce/deploy]   ⚙  ::set-output:: copied_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy]   ⚙  ::set-output:: renamed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: type_changed_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: unmerged_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: unknown_files=
[Deploy to salesforce/deploy]   ⚙  ::set-output:: all_modified_files=.github/workflows/README.md .github/workflows/cd.yml force-app/main/default/objects/Case/fields/Script_Check__c.field-meta.xml
[Deploy to salesforce/deploy] invalid format delimiter 'ghadelimiter_14945122-cd08-4f4a-9c9e-8f7a92b1853d' not found before end of file
[Deploy to salesforce/deploy] ⭐ Run Post Get Changed Files
[Deploy to salesforce/deploy]   🐳  docker cp src=/Users/.cache/act/tj-actions-changed-files@v35/ dst=/var/run/act/actions/tj-actions-changed-files@v35/
[Deploy to salesforce/deploy] ⭐ Run Post Glob match
[Deploy to salesforce/deploy]   🐳  docker exec cmd=[node /var/run/act/actions/tj-actions-glob@v16.12/dist/cleanup/index.js] user= workdir=
| deleted paths-output-file: /tmp/21b7aa49-824c-42e0-9ff1-4d0ce2f7f4c2.txt
[Deploy to salesforce/deploy]   ✅  Success - Post Glob match
[Deploy to salesforce/deploy]   ✅  Success - Post Get Changed Files
[Deploy to salesforce/deploy] 🏁  Job failed
Error: Job 'deploy' failed
```

### Anything else?

I am running the workflow locally using Act. It all appears to work successfully when using an older version:

- `uses: tj-actions/changed-files@v11`

However simply changing to `@v35` it breaks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@MattFaz I think the bug is due to using quotes for the `files_ignore` input.

For more information, See the [Usage](https://github.com/tj-actions/changed-files#usage)  documentation.

**Comment by MattFaz** [comment]
@jackton1 thank you for the quick response. I have just tested removing the `files_ingore` completely and still face the same error. Any other ideas?

```yml
# Get list of added and modified files excluding .md and .yml files
- name: Get Changed Files  
  id: changedFiles
  # uses: tj-actions/changed-files@v11
  uses: tj-actions/changed-files@v35
  with:
    files: force-app/**
    since_last_remote_commit: true 
```

In fact I just tried removing the entire `with` block:
```yml
- name: Get Changed Files  
  id: changedFiles
  # uses: tj-actions/changed-files@v11
  uses: tj-actions/changed-files@v35
```

Still I get the error: `invalid format delimiter 'ghadelimiter_b57f7f57-7d5c-47b2-b74b-ce9e970de5a6' not found before end of file`

Note: It works fine if I use `@v11`
