### ISSUE TITLE
[BUG] Fail to use JSON output

### ISSUE THREAD

**Issue by rsorelli-hedgepoint** [tj-actions/changed-files#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

``Hello folks,

I'm facing some ussues to do the basics with this action.
I'm trying to get the changed directories on my project and use it later on a matrix strategy.

I do see on the run step the correct output on JSON format. 
However, when using th output on another job it fails with:

`Error when evaluating 'strategy' for job 'run-build'. .github/workflows/actions.yaml (Line: 37, Col: 18): Error parsing fromJson,.github/workflows/actions.yaml (Line: 37, Col: 18): Unexpected character encountered while parsing value: \. Path '', line 1, position 1.,.github/workflows/actions.yaml (Line: 37, Col: 18): Unexpected value ''`

Can you please advise ?

### To Reproduce

`name: Build MFE

on: push

jobs:

  detect-changed-folders:   
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.get_changed.outputs.all_changed_files }}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Changed Files
        id: get_changed
        uses: tj-actions/changed-files@v35.8.0
        with:
          json: true
          files_ignore: |
            .github/*
            **/gitignore
            **/readme.md
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 2

      - run: echo ${{ steps.get_changed.outputs.all_changed_files }}

  run-build:
    needs: detect-changed-folders
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folders: ${{ fromJSON(needs.detect-changed-folders.outputs.folders) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: cd ${{ matrix.folders }} && npm ci

      - name: Build Project
        run: cd ${{ matrix.folders }} && npm compile`

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Matrix runs for each item of the JSON

### Relevant log output

```shell
Echo of theaction execution showing the correct JSON

Run echo [\"fortress-pre-trade-mfe/fortress-pre-trade-efrp-header\",\"fortress-pre-trade-mfe/fortress-pre-trade-efrp\"]
  echo [\"fortress-pre-trade-mfe/fortress-pre-trade-efrp-header\",\"fortress-pre-trade-mfe/fortress-pre-trade-efrp\"]
  shell: /usr/bin/bash -e {0}
["fortress-pre-trade-mfe/fortress-pre-trade-efrp-header","fortress-pre-trade-mfe/fortress-pre-trade-efrp"]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @rsorelli-hedgepoint it appears you are missing `fromJSON` function call.

See: https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-test.yml for a working example

**Comment by Twipped** [comment]
@rsorelli-hedgepoint The json output is escaped, so you have to shove it through an echo to remove the escapement.

```yaml
  detect-changed-folders:   
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.escape.outputs.changed }}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Changed Files
        id: get_changed
        uses: tj-actions/changed-files@v35.8.0
        with:
          json: true
          files_ignore: |
            .github/*
            **/gitignore
            **/readme.md
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 2

      - name: Remove escapement
        id: escape
        run: |
          echo "changed=${{ steps.changed.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
```

It's not very intuitive, and I spent probably half an hour trying to figure out why perfectly normal seeming json wasn't parsable by fromJson
