### ISSUE TITLE
False positive (true) in changed files

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [tj-actions/changed-files#1165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The condition on changed files returns `true`, however the respective iteration on the changed files does nothing

### To Reproduce

Using the following steps

```yaml
    - name: get all the dirs that have changes
      id: list-dirs-with-changes
      uses: tj-actions/changed-files@v35
      with:
        dir_names: true
        dir_names_exclude_root: true
        files: |
          **/*.{tf,tfvars}

    - name: teraform format and README.md update
      if: steps.list-dirs-with-changes.outputs.any_modified == 'true'
      env:
        PROJECT_ROOT_DIR: /home/runner/work/my-project/my-project
      shell: bash
      run: |
        pwd
        for directory in ${{ steps.list-dirs.outputs.all_changed_and_modified_files }}; do
          cd $directory
          echo "Switching to $directory"
          terraform fmt
          terraform-docs markdown . --output-file README.md
          cd ${{ env.PROJECT_ROOT_DIR }}
        done
```

Despite the fact that the condition `if: steps.list-dirs-with-changes.outputs.any_modified == 'true'` is met the `for` loop does nothing

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Either the ` if: steps.list-dirs-with-changes.outputs.any_modified == 'true'` should not hold, or the `for` loop should iterate over the changed files.

### Relevant log output

```shell
pwd
  for directory in ; do
    cd $directory
    echo "Switching to $directory"
    terraform fmt
    terraform-docs markdown . --output-file README.md
    cd /home/runner/work/my-project/my-project
  done
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TERRAFORM_DOCS_VERSION: v0.16.0
    TERRAFORM_VERSION: 1.4.6
    PROJECT_ROOT_DIR:  /home/runner/work/my-project/my-project
```

i.e. the `for` loop never runs
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
