### ISSUE TITLE
[Feature] Ability to run a workflow if and only if certain file/directory changes

### ISSUE THREAD

**Issue by aleclerc-sonrai** [tj-actions/changed-files#124]
### Is your feature request related to a problem? Please describe.

Use case: 
I want to run a workflow if and only if any file under a certain directory changes.

If any other files have changed I do not want to run the workflow.

In my case, I'm trying to auto-approve a PR using this action https://github.com/marketplace/actions/auto-approve
but only if files under the `dev` directory have been updated, and nothing else.

### Describe the solution you'd like?

Ideally something like this:

```
    steps:
    - uses: actions/checkout@v2
    - name: Get changed files for dev
      id: changed-files-dev
      uses: tj-actions/changed-files@v8.4
      with:
        files: |
          dev
    - uses: hmarr/auto-approve-action@v2
      if: steps.changed-files-dev.outputs.only_changed == 'true'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
```

Where `only_changed` would be true if any file in that directory were present, and ONLY files in that directory were in the diff (i.e no other files)

### Describe alternatives you've considered?

I've tried something like this:

```
    steps:
    - uses: actions/checkout@v2
    - name: Get changed files for dev
      id: changed-files-dev
      uses: tj-actions/changed-files@v8.4
      with:
        files: |
          dev
    - name: Get changed files for all
      id: changed-files-rest
      uses: tj-actions/changed-files@v8.4
      with:
        files: |
          ^(dev)
    - uses: hmarr/auto-approve-action@v2
      if: steps.changed-files-dev.outputs.any_changed == 'true' && steps.changed-files-rest.outputs.any_changed == 'false'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
```

But that doesn't seem to work and feels clunky.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Have you tried listing the specific files you want to watch for changes ??

**Comment by jackton1** [comment]
Have you tried ??

```
  steps:
    - uses: actions/checkout@v2
    - name: Get changed files for dev
      id: changed-files
      uses: tj-actions/changed-files@v8.4
      with:
        files: |
          dev
    - uses: hmarr/auto-approve-action@v2
      if: steps.changed-files-dev.outputs.any_changed == 'true'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
```
