### ISSUE TITLE
[Question] How do I find all files changed between branches `foo` and current commit

### ISSUE THREAD

**Issue by kunaltyagi** [tj-actions/changed-files#1276]
Assuming that `foo` and current branch/commit (say `baz`) have a common ancestor `def`, I wish to find all files changed from `def` -> `foo` as well as `def` -> `baz`

Is it possible to use this action to find the list of files without explicitly mentioning the commit `def`? Is one of your other actions better suited for this?

**Comment by jackton1** [comment]
@kunaltyagi In such a case you’ll have to provide the branch name to the `base_sha`  and the `sha` inputs.

 If the workflow is triggered from branch `foo` you can omit the `sha` input.

## Example
Workflow triggered via a push to branch `foo`
```yml
     - name: Get changed files between def -> baz
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
            base_sha: def
            sha: baz  # Omit the sha input for def -> foo
```

> Note: providing the `base_sha` is not necessary if your workflow is triggered via a pull request. eg `foo` merges in `baz`
