### ISSUE TITLE
[Feature] Ignore delete file

### ISSUE THREAD

**Issue by SamuelMolling** [tj-actions/changed-files#1334]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

today I have a file that needs to be recovered, but I wouldn't want it to enter as a modified file, you know?

My code is like this:

```yml
       - name: Run changed-files with dir_names
         id: changed-files-dir-names
         uses: tj-actions/changed-files@v36
         with:
           dir_names: "true"
           recover_deleted_files: "true"
           files: |
             terraform/mongodb-atlas/clusters/**/
           files_ignore: |
             **/cluster.hcl
```

I want to ignore cluster.hcl so it doesn't go into ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}, but I want it to be retrieved. It's possible?

### Describe the solution you'd like?

Make a different filter

### Describe alternatives you've considered?

Nothing

### Anything else?

https://github.com/tj-actions/changed-files/issues/1134#issuecomment-1614887054

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
