### ISSUE TITLE
[Feature] Exclude directories containing file

### ISSUE THREAD

**Issue by pl4nty** [tj-actions/changed-files#1352]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like?

I use a monorepo to build containers based on file changes. I'd like to get any changes in directories or submodules that contain `Dockerfile.windows`, so they can be built on Windows runners. Ie changes in any folder that has a file matching `**/Dockerfile.windows`.

### Describe alternatives you've considered?

The `files` and `files_ignore` options let me specify individual files, but the parent folder isn't targeted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@pl4nty Can you provide logs or an example of what you mean by "The files and files_ignore options let me specify individual files, but the parent folder isn't targeted." ?

**Comment by pl4nty** [comment]
Here's an example directory structure:

```
* app1
  * Dockerfile.windows
  * app1.js
* app2
  *  Dockerfile
  * app2.js
* app3
  * Dockerfile.windows
  * Dockerfile
  * app3.js
```

Say I make a commit that changes all three .js files. I'd like to setup `tj-actions/changed-files` to detect `app1` and `app3` since their parent folders contain a `Dockerfile.windows`. Then I can build `app1` and `app3` on a Windows runner.

I'd also like to detect `app2` and `app3` since their parent folders contain a `Dockerfile`. And I would build them on a Linux runner.

This concept could also help monorepos with multiple languages (eg detect `package.json` to run `npm build`).

**Comment by jackton1** [comment]
Given the complexity of handling this within this action, I suggest using a third-party Github action or taking a look at using the `files_yaml` input which lets you specify custom-named filters.

**Comment by jackton1** [comment]
Example

```yaml
      - name: Get all app1, app2 and app3 files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            app1: &shared
              - app3/Dockerfile.windows
            app2:
              - app2/Dockerfile
            app3:
              - *shared
```
