### ISSUE TITLE
[Question] correct fetch-depth for pull_request

### ISSUE THREAD

**Issue by mariaines** [tj-actions/changed-files#1357]
Hi there, love this action! 

I'm having trouble understanding the correct setting for `fetch-depth` for a pull_request -- I would prefer `2` instead of `0`, since my repo is huge, but does that mean if I push multiple commits to remote to an open PR, it will only check the latest commit?

For example:
- main branch at commit 1
- open PR with commit 2
- action checks changed files between commits 2 and 1
- push commits 3, 4, 5
- action checks changed files between commits 5 and 4 (?)

How do I configure it to check commit 5 against commit 2?

Edit: actually, just tested this out and it does seem to work as I expect -- is it checking against main branch at commit 1 always? If so, awesome!

**Comment by jackton1** [comment]
Hi @mariaines, in regard to your question

main (1) gets compared to the HEAD of the PR (5) using the merge base (2) i.e 2 -> 5 (retrieves all changes)

Using:
```yml
name: CI

on:
  pull_request:
    branches:
      - main

  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # You can use 0 for all history, 1 for the current commit and 2 for the current and preceding commits.
          #  The changed-files action pulls an initial history of the PR if 1 or 2 is used before performing the diff you can also control the history pulled by the action using the `fetch_depth` input directly passed to the changed-files action.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
```

Say you pushed 3-5 and 5-7 to compare 7 to the last pushed remote commit 5, you'll need to use the same setup as above with a slight difference

```
... # Same as above
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
           since_last_remote_commit: true # This compares 5 -> 7
```

For more usage-related questions you can also take a look at [previous discussion here](https://github.com/tj-actions/changed-files/discussions?discussions_q=is%3Aclosed) and feel free to open a new discussion you have any more questions.

**Comment by vinceRicchiutiPrima** [comment]
Hi @jackton1 , 

sorry to introduce myself into this topic but i'm currently using your github actions and actually i'm stuck in a similar use-case.

Actually what i'm trying to do is to resolve this situation:

- open new feature branch fb1
- commit_1 -> adding file_a and file_b
- push 
- execution_1 of the workflow (that include list-changes action) -> fails due to an error in file_a
- commit_2 -> fix file_a
- push
- exection_2 of the workflow

There is any chance to retrieve with the action in the execution_2 both file_a and file_b?

It is possible to specify the depth in terms of how many commits i want to observe?

**Comment by jackton1** [comment]
> ```yml
> name: CI
> 
> on:
>   pull_request:
>     branches:
>       - main
> 
>   job2:
>     runs-on: ubuntu-latest  # windows-latest | macos-latest
>     name: Test changed-files
>     steps:
>       - uses: actions/checkout@v3
>         with:
>           fetch-depth: 0 # You can use 0 for all history, 1 for the current commit and 2 for the current and preceding commits.
> 
>       - name: Get changed files
>         id: changed-files
>         uses: tj-actions/changed-files@v37
> ```

@vinceRicchiutiPrima  Based on the previous answer, this workflow would list all changed filenames file_a and file_b. You can control the start and end commit by passing in the `base_sha` and `sha` inputs.

For example:
```yml
... # Same as above
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
           base_sha: "HEAD~8"   # Compare the 8th parent of the current commit
           sha: "HEAD"  # Until the current commit. Note this is not needed as this is assumed by default
```
