### ISSUE TITLE
[BUG] dir_names_exclude_current_dir failing to exclude

### ISSUE THREAD

**Issue by pl4nty** [tj-actions/changed-files#1374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

`dir_names` and `dir_names_exclude_current_dir` are set to true, but changes in the current working directory ("/") are still present in the output.

### To Reproduce

Make a root-level change with the following config:

```yaml
- uses: tj-actions/changed-files@v37.1.1
  with:
    fetch_depth: 2
    skip_initial_fetch: true
    dir_names: true
    dir_names_max_depth: 1
    dir_names_exclude_current_dir: true
    files_ignore: |
      .github/**
      archive/**
    json: true
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

No changes to be detected

### Relevant log output

[log.txt](https://github.com/tj-actions/changed-files/files/12038756/log.txt)

### Anything else?

https://github.com/pl4nty/containers/actions/runs/5537616198/jobs/10115639021

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
