### ISSUE TITLE
[Feature] Support for explicitly using the github API

### ISSUE THREAD

**Issue by jceresini** [tj-actions/changed-files#1449]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

We have a large codebase, a checked-out copy is around 4G. We have workflows that run on PRs as well as other events. Because of that, we check out the repo before using this action. We also sometimes fight with how much history to fetch to satisify some complicated PRs with merge commits. I'd love to be able to set an input specifying to use the GitHub API regardless of whether the repo is there. It looks like the action is smart enough to attempt to fetch additional history, but that's what we're trying to avoid.

### Describe the solution you'd like?

An input that, when set to some known value, will result in the github API being used to get changed files. If there are reasons it can't be used (if it's not a PR, permissions issue, etc.) I think I'd prefer the job just fail.

Then we could set the appropriate input on PRs, and not set it on other events, and avoid fetching history to get changed files.

### Describe alternatives you've considered?

It would be pretty cumbersome, but we could probably setup multiple workflows with the changed-files action before the checkout on PRs, and after it for other event types.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi, @jceresini I believe Github API is already supported. To utilize Github API you just need to run on pull_request* events and exclude usage of the checkout action.


For more information on how to set things up [see the docs](https://github.com/tj-actions/changed-files#using-githubs-api).

**Comment by jceresini** [comment]
Right, I understand that. But for example, if we do a shallow clone of the repo we'd like it to use the API for changed files rather than pull down the history.

If that's not a feature you're interested in implementing, though, we can find a solution. Thanks for this really useful action!

**Comment by jackton1** [comment]
Is there a reason you want to do a shallow clone and use GitHub’s API in the same job? 

Have you considered running the shallow clone and the changed-files action in different jobs?


```yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs: 
       changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  
  ci:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    needs: [changed_files]
     ...
```
