### ISSUE TITLE
[BUG] `any_changed` always true with `json` and `dir_names`

### ISSUE THREAD

**Issue by mazay** [tj-actions/changed-files#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The `<prefix>_any_changed` is always `true` with `dir_names: true` and `json: true`.

### To Reproduce

```yaml
- name: Get all files that have changed
  id: changed-files
  uses: tj-actions/changed-files@1c26215f3fbd51eba03bc199e5cbabdfc3584ce3 # v38.1.0
  with:
    dir_names: true
    json: true
    escape_json: false
    files_yaml: |
      qa:
        - 'qa/**/*'
        - '!**/*.md'
      prod:
        - 'prod/**/*'
        - '!**/*.md'
      prod_china:
        - 'prod-china/**/*'
        - '!**/*.md'
      root:
        - 'root/**/*'
        - '!**/*.md'
      base:
        - 'common_vars.yaml'
        - 'terragrunt.hcl'

- name: Print QA changed files
  if: steps.changed-files.outputs.qa_any_changed == 'true'
  run: |
    echo "${{ steps.changed-files.outputs.qa_any_changed }}"
    echo "The following QA modules were changed: ${{ steps.changed-files.outputs.qa_all_changed_files }}"
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

`qa_any_changed` equals `false` when no files was changed.

### Relevant log output

```shell
Run echo "true"
  echo "true"
  echo "The following QA modules were changed: []"
  shell: /usr/bin/bash -e {0}
true
The following QA modules were changed: []
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
