### ISSUE TITLE
[BUG] `files_yaml` + `json` does not support names `/`

### ISSUE THREAD

**Issue by LecrisUT** [tj-actions/changed-files#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

This is quite a niche setup, but I am using `fmf` which basically has a file-structure `yaml` format, e.g.:
```yaml
/javascript/node:
  - Lib/javascript/node/*
/javascript/v8:
  - Lib/javascript/v8/*
```

However, when these are used in `files.yaml`, there is some path normalization because it is trying to access `.github/outputs/javascript/node_added_files.json` (note how `javascript/node` is handled there), but apparently that file is not created in previous steps, probably due to path noarmalization.

### To Reproduce

```yaml
      - name: Check changed files
        uses: tj-actions/changed-files@v39
        id: changed-files
        with:
          files_yaml: |
            foo/bar:
              - foo/*
          json: true
          write_output_files: true
```

[example](https://github.com/swig/swig/actions/runs/6107802127/job/16575553254?pr=2647)

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04, ubuntu-20.04, macos-latest or macos-12, macos-11

### Expected behavior?

Consistent path normalizations

### Relevant log output

```shell
changed-files-yaml-java
  All Done!
changed-files-yaml-javascript/node
  Error: ENOENT: no such file or directory, open '.github/outputs/javascript/node_added_files.json'
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

This is not a blocking thing for me since I can easily fix it, but might be worth building a test for it at some point.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
