### ISSUE TITLE
[BUG] Action only checks files changes in the latest commit.

### ISSUE THREAD

**Issue by Aficionado45** [tj-actions/changed-files#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

On using the action in a workflows triggered on `push`, when multiple commits are present in a PR. Only the files changed in the latest commit is reflected in the output. Tried setting `fetch-depth: 0` `fetch-depth:2` and `since_last_remote_commit: true`, still files changed in earlier commits are not detected.
`Workflow-file:`
```
name: Files Changed

on:
  push:
    branches:
      - 'main'
      - 'rel-*'
      - 'TS-*' 

jobs:
    file-check:
        runs-on: self-hosted
        outputs:
          any-modified: ${{steps.check-file-output.outputs.any-modified}}
        name: Check changed files
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 2
          - name: Changed files
            id: changed-files
            uses: tj-actions/changed-files@v39
            with:
              since_last_remote_commit: true
              files: |
                .github/**

          - name: Set Output
            id: check-file-output
            run: |
              echo "any-modified=${{steps.changed-files.outputs.any_modified}}" >> $GITHUB_OUTPUT

    build:
        runs-on: self-hosted
        needs: file-check
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get branch name
          shell: bash
          run: |
             echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
             echo "${{ needs.file-check.outputs.any-modified }}"

        - name: Echo 
          run: |
            echo "${{ needs.file-check.outputs.any-modified }}"
            echo "${{ env.SOURCE_BRANCH }}"

        - name: Build and push
          if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' && needs.file-check.outputs.any-modified == 'true' }}
          run: |
            echo "On push"
            
        - name: Build and push 
          if: ${{ (startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main') && needs.file-check.outputs.any-modified == 'true' }}
          run: |
            echo "On merge"
```

### To Reproduce

Copy the workflows, file and run on `self-hosted` configuration. Try to make many commits on different files in different commits and check output for each workflows run. 

If files mentioned in `files:` are changed in latest commit, then only action produces desired results.

### What OS are you seeing the problem on?

macos-latest or macos-12

### Expected behavior?

Expected action to fetch all the files changed in the PR irrespective of commit history in the PR when they were changed.

### Relevant log output

```shell
NA
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@Aficionado45 Can you provide logs?

**Comment by jackton1** [comment]
Also, note that 

```
          - name: Changed files
            id: changed-files
            uses: tj-actions/changed-files@v39
            with:
              since_last_remote_commit: true
              files: |
                .github/**
```

This means only considering changes to the `.github` folder not all changed files.

**Comment by Aficionado45** [comment]
> Also, note that
> 
> ```yaml
>           - name: Changed files
>             id: changed-files
>             uses: tj-actions/changed-files@v39
>             with:
>               since_last_remote_commit: true
>               files: |
>                 .github/**
> ```
> 
> This means only considering changes to the `.github` folder not all changed files.

Yes I only want to check changes in `.github` but in case when I made soome changes in `.github` in first commit and some other changes later on not in `.github` then changes made in first commit are not detected

**Comment by jackton1** [comment]
I assume you already pushed the commit with the changes to the `.github` directory in which case the next workflow run would only compare the last commit i.e. as the starting point and run a diff with the new commit which wouldn't contain the `.github` directory. 

The used of `since_last_remote_commit` would only work when you have a number of local commit i.e not pushed to the remote which at least one commit includes changes to the `.github` folder in which case when you push that would detect that since the last remote commit the `.github` directory was changed.

**Comment by Aficionado45** [comment]
<img width="1307" alt="Screenshot 2023-09-15 at 9 12 08 AM" src="https://github.com/tj-actions/changed-files/assets/61295782/986b2084-a3db-4e0e-b8fe-0a607a66e590">
<img width="1728" alt="Screenshot 2023-09-15 at 9 11 45 AM" src="https://github.com/tj-actions/changed-files/assets/61295782/7916e016-b528-40a3-ae81-f7be8a71060e">
<img width="1727" alt="Screenshot 2023-09-15 at 9 10 56 AM" src="https://github.com/tj-actions/changed-files/assets/61295782/baf8ed08-1543-4ebb-b938-eec350d11f11">
<img width="1728" alt="Screenshot 2023-09-15 at 9 14 53 AM" src="https://github.com/tj-actions/changed-files/assets/61295782/9cc9dbff-bc3d-4d20-8e44-cdc13e5bd4d6">


These are the required logs, file-change in `.github` folder is detected only if change is present in the commit not taking in consideration file change across all commits in the PR.

**Comment by jackton1** [comment]
You'll need to change from the push event to the pull_request event see the [docs](https://github.com/tj-actions/changed-files#on-pull_request-) for more information.

Change
```
on:
  push:
    branches:
      - 'main'
      - 'rel-*'
      - 'TS-*' 
```

To

```
on:
  pull_request:
    branches:
      - 'main'
      ... # Any other branches that make sense
```

**Comment by Aficionado45** [comment]
Isn't there any alternative for push based events, seems like that's a restriction. Push based event are generally crucial in case to trigger `build` with each new commit to remote.

**Comment by jackton1** [comment]
An alternative would be explicitly passing the `base_sha` for example

```yml
...
    - name: Changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
      with:
        base_sha: ${{ github.event.pull_request.base.sha }}
...
```
