### ISSUE TITLE
[Feature] Add a way to retrieve main components from `files_yaml` with just one output

### ISSUE THREAD

**Issue by V0lantis** [tj-actions/changed-files#1579]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Taking the example in the [README.md](https://github.com/tj-actions/changed-files/tree/d1e9506b19d9c3a4053191d616b1ac09de1dfa55#using-local-git-history-) on master:

```yaml
...
 # Example 1
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            doc:
              - '**/*.md'
              - docs/**
              - README.md
            test:
              - test/**
              - '!test/**.md'
            src:
              - src/**
          # Optionally set `files_yaml_from_source_file` to read the YAML from a file. e.g `files_yaml_from_source_file: .github/changed-files.yml`
```
From the snippet above, I would like to have all the different components which have any modifed / changed files and to get just the name of the component. For example, 

```yaml
      - name: Return components which have a changed files
        run: |
          echo "Here are all the components which have changed files:"
          echo "List all the components that have changed: ${{ steps.changed-files-yaml.outputs.changed-components }}" # doc, test
```

### Describe the solution you'd like?

If we have some changed files in doc, then the `echo` above would give us just `doc` as a result ect...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
> When using files_yaml* inputs ensure all outputs are prefixed by the key test_{...} e.g. test_added_files, test_any_changed

**Comment by V0lantis** [comment]
Thank you @jackton1, but actually, I need something else. Basically, I need to create a list of components that I will feed to a matrix, and I thought it would be more elegant if they would be such output from `changed-files`, directly re-using the name of the root object from the `yaml` we feed to `changed-files`. Please ask me to reformulate if I am not clear enough

**Comment by jackton1** [comment]
Yeah it's not clear you might have to use a working example

**Comment by jackton1** [comment]
Also note that you can also use the `files` input instead which would not require a key for each path your provide e.g

Instead of
```yml
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            doc:
              - '**/*.md'
              - docs/**
              - README.md
            test:
              - test/**
              - '!test/**.md'
            src:
              - src/**
      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.test_any_changed == 'true' 
        ...
```

You can use 
```yml
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files: |
            test/**
            !test/**.md
      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.any_changed == 'true' 
        ...
```

**Comment by jackton1** [comment]
Actually I just went through your request again I think you mean you want to know which key has changed files?

E.g
```
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            doc:
              - '**/*.md'
              - docs/**
              - README.md
            test:
              - test/**
              - '!test/**.md'
            src:
              - src/**
```

If there are changes to the `test/**` files this should return a list like `test ...`
