### ISSUE TITLE
[Feature]: Add support for returning directory names if all files within the directory has been deleted

### ISSUE THREAD

**Issue by AliaksandrRyzhou** [tj-actions/changed-files#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Inputs `files` and `files_ignore` don't work as expected.  I want to create different matrixes, depending on `all_modified_files` and `deleted_files`.

### To Reproduce

I use the following workflow (Inputs `files` and `files_ignore` I will add bellow):
```yaml
name: 'TEST Helm Charts Deployment'
run-name: 'TEST Deployment by @${{ github.actor }}'

on:
  push:
    branches: ["main"]
    paths:
      - 'charts/**'
      - '!charts/*.md'
      - '!charts/**/*.md'
      - '!charts/repos.txt'
env:
  CHARTS_DIRECTORY: "${{ github.workspace }}/charts"

jobs:
  helm-charts:
    runs-on: ubuntu-latest
    name: 'Getting charts for change'
    outputs:
      matrix_upgrade: ${{ steps.set-matrix-upgrade.outputs.matrix_upgrade }}
      matrix_delete: ${{ steps.set-matrix-delete.outputs.matrix_delete }}
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0

      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          path: ${{ env.CHARTS_DIRECTORY }}
          json: true
          output_renamed_files_as_deleted_and_added: true
          quotepath: false

      - name: Get deleted directories
        id: deleted-directories
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          path: ${{ env.CHARTS_DIRECTORY }}
          json: true
          output_renamed_files_as_deleted_and_added: true
          quotepath: false

      - id: set-matrix-upgrade
        run: |
          echo "matrix_upgrade={\"charts_upgrade\":${{ steps.changed-files.outputs.all_modified_files }}}" >> "$GITHUB_OUTPUT"

      - id: set-matrix-delete
        run: |
          echo "matrix_delete={\"charts_delete\":${{ steps.deleted-directories.outputs.deleted_files }}}" >> "$GITHUB_OUTPUT"
```
With this folder structure, it's a content of charts folder :
```
chart1
chart1/.helmignore
chart1/Chart.yaml
chart1/values.yaml
chart1/charts
chart1/templates
chart1/templates/deployment.yaml
chart1/templates/service.yaml
chart1/templates/serviceaccount.yaml
chart1/templates/ingress.yaml
chart1/templates/NOTES.txt
chart1/templates/_helpers.tpl
chart1/templates/hpa.yaml
chart1/templates/tests
chart1/templates/tests/test-connection.yaml
chart2
chart2/.helmignore
chart2/Chart.yaml
chart2/values.yaml
chart2/charts
chart2/templates
chart2/templates/deployment.yaml
chart2/templates/service.yaml
chart2/templates/serviceaccount.yaml
chart2/templates/ingress.yaml
chart2/templates/NOTES.txt
chart2/templates/_helpers.tpl
chart2/templates/hpa.yaml
chart2/templates/tests
chart2/templates/tests/test-connection.yaml
chart3
chart3/.helmignore
chart3/Chart.yaml
chart3/values.yaml
chart3/charts
chart3/templates
chart3/templates/deployment.yaml
chart3/templates/service.yaml
chart3/templates/serviceaccount.yaml
chart3/templates/ingress.yaml
chart3/templates/NOTES.txt
chart3/templates/_helpers.tpl
chart3/templates/hpa.yaml
chart3/templates/tests
chart3/templates/tests/test-connection.yaml
README.md
repos.txt
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

The idea is to get output `deleted_files` in JSON which contains folders  `[\"chart1\",\"chart2\",\"chart3\"]` only if these folders are deleted at all. It's very important to exclude any deletions and changes inside these folders because if it works wrong my workflow will delete a working chart.

Also, in the second step, I want to get `all_modified_files` in JSON which contains folders inside of which any changes were.  Added, copied, modified, renamed, and deleted files. In this step is very important to not receive a folder if it was deleted at all.

Honestly, I tried about 100 options, with verification at [codepen](https://codepen.io/mrmlnc/pen/OXQjMe) and more successful ones, which are not described bellow because I no longer remember them. The main thing is to get the result so that the deletion matrix contains only folders in the charts directory and only if these folders were deleted themselves. The update matrix received a list of charts in which something was changed but did not receive folders from the root charts directory.

#### 1. This case shows nothing when I change one file within chart1, chart2, and chart3 folders. The same thing if I delete some folder, for example, chart3.
```
      - name: Get changed directories
        ...
          files: |
            */**/*.*
            */**/.*
            */**/*
          files_ignore: |
            *

      - name: Get deleted directories
        ...
          files: |
            *
          files_ignore: |
            */**/*.*
            */**/.*
            */**/*
```
Logs 
"matrix_upgrade={\"charts_upgrade\":[]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[]}" >> "$GITHUB_OUTPUT"

#### 2. This case shows nothing when I change one file within chart1, chart2, and chart3 folders. The same thing if I delete some folder, for example, chart3.

```
      - name: Get changed directories
        ...
          files: |
            **
          files_ignore: |
            *

      - name: Get deleted directories
        ...
          files: |
            **
          files_ignore: |
            *
```
Logs 
"matrix_upgrade={\"charts_upgrade\":[]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[]}" >> "$GITHUB_OUTPUT"

#### 3. This case shows nothing when I change one file within chart1, chart2, and chart3 folders. The same thing if I delete some folder, for example, chart3.

```
      - name: Get changed directories
        ...
          files: |
            */**
          files_ignore: |
            **/

      - name: Get deleted directories
        ...
          files_ignore: |
            */**
```
Logs 
"matrix_upgrade={\"charts_upgrade\":[]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[]}" >> "$GITHUB_OUTPUT"

#### 4. This case shows the correct matrix if we change the files within any folder but if we delete the folder it will show nothing for matrix_delete and will show the changes in matrix_upgrade.

```
      - name: Get changed directories
        ...
          files: |
            */**/{*,*.*,.*}

      - name: Get deleted directories
        ...
          files_ignore: |
            */**/{*,*.*,.*}
```
Logs
Files was changed in chart1, chart2, and chart3 folders (correct!):
"matrix_upgrade={\"charts_upgrade\":[\"chart3\",\"chart1\",\"chart2\"]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[]}" >> "$GITHUB_OUTPUT"

Folder chart3 was deleted (wrong!):
"matrix_upgrade={\"charts_upgrade\":[\"chart3\"]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[]}" >> "$GITHUB_OUTPUT"

#### 5. This case shows the correct matrix if we change the files within any folder and now, if we delete the folder it will show the deleted folder in matrix_delete and will show the changes in matrix_upgrade.

```
      - name: Get changed directories
        ...
          files: |
            */**/{*,*.*,.*}

      - name: Get deleted directories
        ...
          files: |
            *
```
Logs
Files was changed in chart1, chart2, and chart3 folders (correct!):
"matrix_upgrade={\"charts_upgrade\":[\"chart3\",\"chart1\",\"chart2\"]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[]}" >> "$GITHUB_OUTPUT"

Folder chart3 was deleted, now we can see the correct matrix for the deletion but also we still see the wrong result for matrix_upgrade (wrong!):
"matrix_upgrade={\"charts_upgrade\":[\"chart3\"]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[\"chart3\"]}" >> "$GITHUB_OUTPUT"

I deleted one file in folder chart1 (for matrix_delete result is wrong!):
"matrix_upgrade={\"charts_upgrade\":[\"chart1\"]}" >> "$GITHUB_OUTPUT"
"matrix_delete={\"charts_delete\":[\"chart1\"]}" >> "$GITHUB_OUTPUT"

### Relevant log output

Log files:

[case1.zip](https://github.com/tj-actions/changed-files/files/12681539/1.zip)

[case2.zip](https://github.com/tj-actions/changed-files/files/12681625/2.zip)

[case3.zip](https://github.com/tj-actions/changed-files/files/12681661/3.zip)

[case4-changed-files-in-all-folders.zip](https://github.com/tj-actions/changed-files/files/12681725/case4-changed-files-in-all-folders.zip)

[case4-deleted-one folder.zip](https://github.com/tj-actions/changed-files/files/12681815/case4-deleted-one.folder.zip)

[case5-changed-files-in-all-folders.zip](https://github.com/tj-actions/changed-files/files/12681881/case5-changed-files-in-all-folders.zip)

[case5-deleted-one folder.zip](https://github.com/tj-actions/changed-files/files/12681884/case5-deleted-one.folder.zip)

[case5-deleted-one-file-in-chart1-folder.zip](https://github.com/tj-actions/changed-files/files/12681954/case5-deleted-one-file-in-chart1-folder.zip)

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @AliaksandrRyzhou, is there a reason you are changing the default repository location by setting

```yml
path: ${{ env.CHARTS_DIRECTORY }}
```

**Comment by jackton1** [comment]
I’ll also point out that you don’t need two different step to detect deleted and changed files.

```yml
      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          path: ${{ env.CHARTS_DIRECTORY }}
          json: true
          output_renamed_files_as_deleted_and_added: true
          quotepath: false

# Not required
      - name: Get deleted directories
        id: deleted-directories
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          path: ${{ env.CHARTS_DIRECTORY }}
          json: true
          output_renamed_files_as_deleted_and_added: true
          quotepath: false
```
