### ISSUE TITLE
[BUG] Slow calculation when using pull_request_target

### ISSUE THREAD

**Issue by tru** [tj-actions/changed-files#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

On llvm/llvm-project we can see that when the PR is not 100% up-to-date with the base branch (llvm-project/main) it will fetch a lot of extra commits to figure out the diff.

You can see a run like that here: https://github.com/llvm/llvm-project/actions/runs/6272036185

### To Reproduce

* Have a really huge repo
* This is the config: https://github.com/llvm/llvm-project/blob/main/.github/workflows/pr-code-format.yml#L16
* It takes forever if the PR branch is not up-to-date with base

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

Go faster, just fetch what's needed not the whole history.

### Relevant log output

```shell
Log was to big to attach, see the gist here: https://gist.github.com/tru/e1c69b9f6496362668e0dec2edb8e967
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @tru, I believe you can control the size of the git history that is pulled by using the [`fetch_depth`](https://github.com/tj-actions/changed-files#input_fetch_depth) input.
 
 
 ```yml
…
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          separator: ","
          fetch_depth: 10 # Fetches only the last 10 commits
…
```
