### ISSUE TITLE
[Feature] Set correct branch on issue_comment event for PR

### ISSUE THREAD

**Issue by hansarh** [tj-actions/changed-files#1619]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'm using branch deploy which uses `issue_comment: created` to trigger a workflow. For issue_comment event the default branch is where this action looks for commit sha's, even though the checkout action in the workflow checks out the PR branch.

The result is like this where the sha's are from the PR branch but the branch is set to main: 
![image](https://github.com/tj-actions/changed-files/assets/6917956/da8c93d3-5668-49d0-8bd6-0f71eb39f1e2)

### Describe the solution you'd like?

Either add extra checks to understand this is a PR context by using the github.event.issue.pull_request property [described here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only)  

Or add inputs on git ref or setting the PR number to correctly look for the sha 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @hansarh can you provide a more details of your workflow file including actions of the checkout action and the changed-files action

**Comment by hansarh** [comment]
This is the workflow YAML with the checkout action included:

```YAML
on:
  workflow_call:
    inputs:
      srcdir:
        description: 'Directory to build from'
        required: false
        default: './src'
        type: string
      ref:
        description: 'git refence to checkout'
        required: false
        type: string
        default: ${{ github.ref }}
      sha:
        description: 'git sha to checkout'
        required: false
        type: string
        default: ${{ github.sha }}
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_commit_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      # Check if any files in the src/app folder has changed
      - name: Check changes in image source code folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: '${{inputs.srcdir}}/**'
          sha: ${{ inputs.sha }}
```

The workflow is called on by a parent branch sending in inputs looking like this for sha and ref:
![image](https://github.com/tj-actions/changed-files/assets/6917956/14c1c7bb-a195-483f-8e44-b8a5a49f199d)
