### ISSUE TITLE
[BUG] changed-files unable to initialize git repository on custom container image

### ISSUE THREAD

**Issue by shuynh** [tj-actions/changed-files#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

when using a custom container image on ubuntu-latest, `changed-files` is unable to initialize a the git repository 
```
  fatal: not a git repository (or any parent up to mount point /)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  Error: Process completed with exit code 128.
```

### To Reproduce

consider this action -- 
```
  quality-checks:
    runs-on: ubuntu-latest
    container:
      image: 123456789.dkr.ecr.us-west-2.amazonaws.com/my-test-container:latest
      credentials:
        username: AWS
        password: saved-password
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            /__w/my-test-container/my-test-container/*.py
```

during the `Initialize containers` step i see it create my container with a working directory-- 
```
  /usr/bin/docker create --name 123456789amazonawscommytestcontainerklatest_91g223 --label c9e036 --workdir /__w/my-test-container/my-test-container 
```

then during the `actions/checkout` it wipes the correct working dir and checks out the code -- 
```
Syncing repository: MyRepo/my-test-container
Getting Git version info
Deleting the contents of '/__w/my-test-container/my-test-container'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Writing archive to disk
Extracting the archive
```

then `changed-files` seems to fail when getting the HEAD info -- 
```
Run tj-actions/changed-files@v9.3
changed-files
  fatal: not a git repository (or any parent up to mount point /)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  Error: Process completed with exit code 128.
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

is there a way to configure where `changed-files` looks for the git repo? in this case it should initialize in `/__w/my-test-container/my-test-container/`

does it need this `working-directory` option? https://github.community/t/use-working-directory-for-entire-job/16747/2
(seems like this would need some tweaks to the `checkout` action to allow it to check out to a different directory.

### Anything else?

possible dupe of https://github.com/tj-actions/changed-files/issues/100

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
You’ll need to use `actions/checkout@v2`.

See: https://github.com/tj-actions/changed-files#usage

**Comment by shuynh** [comment]
> You’ll need to use `actions/checkout@v2`.
> 
> See: https://github.com/tj-actions/changed-files#usage

i am, i posted my action above -- 

```
  quality-checks:
    runs-on: ubuntu-latest
    container:
      image: 123456789.dkr.ecr.us-west-2.amazonaws.com/my-test-container:latest
      credentials:
        username: AWS
        password: saved-password
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            /__w/my-test-container/my-test-container/*.py
```
