### ISSUE TITLE
[BUG] Deleted files not detected

### ISSUE THREAD

**Issue by gavrichards** [tj-actions/changed-files#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

I am using the action as follows, but when I delete files in "mydir", they are not appearing in the summary.
e.g. I delete mydir/hello.txt
The deleted file is missing from the list "Checking for file changes" and "Deleted files:"
This happens every time.

### To Reproduce

```
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.0.0
        with:
          files: |
            mydir/**
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Deleted files should list the files that were deleted.

### Relevant log output

```shell
Run tj-actions/changed-files@v1.0.0
  with:
    files: mydir/**
  
    token: ***
    separator:  
    sha: XXXXX
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_S3_BUCKET: ***
    AWS_REGION: ***
changed-files
  Getting HEAD info...
  Retrieving changes between XXX (master) → XXXX (master)
  Checking for file changes: "mydir/d"...
  Checking for file changes: "mydir/gulpfile.js"...
  Checking for file changes: "mydir/images"...
  Checking for file changes: "mydir/slider"...
  Checking for file changes: "mydir/style"...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: 
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed files: 
  All modified files: 
  Input files: mydir/**
  Matching modified files: 
  Non Matching modified files: .github/workflows/main.yml
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
