### ISSUE TITLE
[Feature] Add support for `any_deleted` and `only_deleted` boolean output.

### ISSUE THREAD

**Issue by jackton1** [tj-actions/changed-files#166]
### Is your feature request related to a problem? Please describe.

The current changed file detection via `only_deleted` and `any_deleted` doesn't include deleted files which makes it tough to detect files that were deleted.

## Proposes Solution

Adding two new boolean outputs should help with detecting file deletion.

```yaml
      - name: Run step when any listed file has been deleted
        if: steps.changed-files.outputs.any_deleted == "true"
        run: |
          for file in "${{ steps.changed-files.outputs.deleted_files }}"; do
            echo "$file was deleted"
          done

      - name: Run step when all listed files have been deleted
        if: steps.changed-files.outputs.only_deleted == "true"
        run: |
          for file in "${{ steps.changed-files.outputs.deleted_files }}"; do
            echo "$file was deleted"
          done
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
