### ISSUE TITLE
[Support issue comment created trigger] Support issue comment created trigger scenario in pull request

### ISSUE THREAD

**Issue by hansarh** [tj-actions/changed-files#1667]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'm using the [branch deploy](https://github.com/github/branch-deploy) action which is triggered on in Pull requests:
```
# The workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]
```
For this trigger the [github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is the default branch which I'm changing to the PR branch by using the `ref` output of branch-deploy. 
I'm using the `sha` output of branch deploy as input for `sha` in this action, but it seems like it only checks for changes against the previous commit in this scenario. 
```
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      # Check if any files in the src/app folder has changed
      - name: Check changes in source code folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: '${{inputs.srcdir}}/**'
          sha: ${{ inputs.sha }}
```

![image](https://github.com/tj-actions/changed-files/assets/6917956/1a6ce568-e419-4ca2-9c6f-b21de9e7134b)

### Describe the solution you'd like?

I want it to work more like the PR scenario where it checks against the default branch or the base_sha of the PR branch. I guess it would work if I was able to in addition input the `base_sha`, but I only have `base_ref ` as an output from the branch deploy action. 

Is there any way you see I can achieve this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
HI @hansarh you can use the [`base_sha`](https://github.com/tj-actions/changed-files?tab=readme-ov-file#input_base_sha) input in that case passing the `base_ref` output from the [branch-deploy](https://github.com/github/branch-deploy?tab=readme-ov-file#outputs-) action.

Here is an example:
```yaml
- name: Get changed files
  id: changed-files
  uses: tj-actions/changed-files@v39
  with:
    sha: ${{ inputs.sha }}
    base_sha: ${{ steps.branch-deploy.outputs.base_ref }}
    files: '${{inputs.srcdir}}/**'
```
