### ISSUE TITLE
[Feature] Add support for checkout path

### ISSUE THREAD

**Issue by IvanPizhenko** [tj-actions/changed-files#167]
### Is your feature request related to a problem? Please describe.

I am checking out multiple repositories like this:
```yaml
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: this
          fetch-depth: 2

      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: SomeAccount/AnotherRepo
          path: another
          fetch-depth: 2
```
But this action only works for default checkout path.

### Describe the solution you'd like?

Like this:
```yaml
      - name: Get changed files from this repo
        id: changed-files-this
        uses: tj-actions/changed-files@v1.x.y
        with:
          #  Same path as in the "checkout" action
          path: this

      - name: Get changed files from another repo
        id: changed-files-another
        uses: tj-actions/changed-files@v1.x.y
        with:
          #  Same path as in the "checkout" action
          path: another
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
