### ISSUE TITLE
[BUG] `files_ignore` input ignores negation with `!`

### ISSUE THREAD

**Issue by luk-lo** [tj-actions/changed-files#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have a scenario where I want to list all changes but ignore `.txt` files except if those files are below `module3` via the `files_ignore` input:
```yaml
steps:
  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
     with: 
       ref: ${{ github.event.pull_request.head.sha }}
  - name: Non-txt file changes except in module3
     id: diff-non-txt
     uses: tj-actions/changed-files@af292f1e845a0377b596972698a8598734eb2796 # v40.0.0
     with:
       files_ignore: |
         **/*.txt
         !module3/**/*.txt
```
But if I modify e.g. `module3/test/file.txt`, it does not appear in `all_changed_files`. The log output looks to me like the entries in `files_ignore` are prepended with `!` except when they already have a `!` in front?

### To Reproduce

I reproduced the behavior in https://github.com/luk-lo/test-issue/pull/1

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

I would expect the `.txt` files below `module3` to not be ignored.

### Relevant log output

```shell
##[debug]  "filesIgnore": "**/*.txt\n!module3/**/*.txt",
##[debug]  "filesIgnoreSeparator": "\n",
...
##[debug]files ignore patterns: !**/*.txt
##[debug]!module3/**/*.txt
##[debug]Input file patterns: 
##[debug]!**/*.txt
##[debug]!module3/**/*.txt
##[debug]File patterns: !**/*.txt,!module3/**/*.txt
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@luk-lo The `files_ignore` input automatically prepends a `!` in the pattern if it isn't there it doesn't conditionally allow certain patterns to the included.

If you intend to include `module3/**/*.txt` then you should use the `files` input instead.

```yml
...
  - name: Non-txt file changes except in module3
     id: diff-non-txt
     uses: tj-actions/changed-files@af292f1e845a0377b596972698a8598734eb2796 # v40.0.0
     with:
       files: 'module3/**/*.txt'
       files_ignore: '**/*.txt'
```
