### ISSUE TITLE
[Feature] dir_names_include_only

### ISSUE THREAD

**Issue by stefan-matic** [tj-actions/changed-files#1705]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

There's no ability to specify tracking just some directories.

### Describe the solution you'd like?

Consider having the following directory structure:

```
├── other
├── project_a
└── project_b
```

The project folders should be tracked for changes while "other" should be excluded from changes outputs.

This would allow getting outputs for directories that you only want tracked and ignore others.

The job would be set up as:

```
  changed-files:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          dir_names: true
          dir_names_include_only: |         <<--- Suggestion
            project_a
            project_b
          dir_names_exclude_current_dir: true
          json: true
          quotepath: false
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - id: set-matrix
        run: echo "matrix={\"files\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
```

Then you could tie it together with matrix:

```
  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 5
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: do something
        run: |
          <do something in each of the directories where changes are detected>
        working-directory: ${{ matrix.files }}
```

### Describe alternatives you've considered?

I've tried using the [matrix-test](https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-test.yml) along with the [dir_names_include_files](https://github.com/marketplace/actions/changed-files#input_dir_names_include_files) but I never got it to work - getting duplicate jobs for directories and the files matched:

![image](https://github.com/tj-actions/changed-files/assets/48199696/05dd238c-0c48-46f3-b5bf-9e2e5c5625a7)

I ended up using the following workaround to remove the "other" directory from the matrix:

```
      - id: set-matrix
        run: echo "matrix={\"files\":${{ steps.changed-files.outputs.all_changed_files }}}" | sed 's/\"other\",//' >> "$GITHUB_OUTPUT"
```

### Anything else?

The `dir_names_include_only` could also be `dir_names_exclude` and instead of including the directories we could exclude the ones we don't need.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefan-matic** [comment]
After browsing the closed issues I learned that we can use `files_ignore` in this use case:

```
  changed-files:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          files_ignore: |                    << ---- Changed
            other/**                        
          json: true
          quotepath: false
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - id: set-matrix
        run: echo "matrix={\"files\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
```

Now the "other" directory will be excluded.

Closing the issue
