### ISSUE TITLE
[BUG] recovering deleted files from within git submodules is not working

### ISSUE THREAD

**Issue by rodrigorfk** [tj-actions/changed-files#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Recovering deleted files works great when not using git submodules, however if git submodules are in place, the existing logic does not account about the existence of the submodule and the action fails with an error like the following:
```
Error: Error getting file content from git history "my/submodule/folder/somefile.txt": fatal: path 'my/submodule/folder/somefile.txt' does not exist in 'c9e31d8d8b86c2d08e3797cb821640acec87f5cf'
```
where `c9e31d8d8b86c2d08e3797cb821640acec87f5cf` is the previous sha of the parent repository and not the submodule.

### To Reproduce

1. Add the following condition to the `test.yml` workflow:
```yaml
     - name: Run changed-files with recover_deleted_files for an expected git submodule file
        id: changed-files-recover-deleted-files-within-submodule
        uses: ./
        with:
          base_sha: "3be651e99d3d4eae395694f6c6f3b9d18457f6c8"
          sha: "d90c240f2ad4ec04d8f0f48e5ac290ad96ebe850"
          recover_deleted_files: true
          fetch_depth: 60000
```
2. That will to diff the current repository between two commits which correspond to when the [tests/demo](tests/demo) submodule got a file deleted.
3. The action will fail with an error similar with the one mentioned above.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

I would expect the file to be transparently recovery from the git submodule as well.

### Relevant log output

```shell
Error: Error getting file content from git history "my/submodule/folder/somefile.txt": fatal: path 'my/submodule/folder/somefile.txt' does not exist in 'c9e31d8d8b86c2d08e3797cb821640acec87f5cf'
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
