### ISSUE TITLE
files_yaml + json does not write the outputs to a json file

### ISSUE THREAD

**Issue by dkezri** [tj-actions/changed-files#1759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

using the following pattern in files changes:

```
      - name: Github filechanges
        id: files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            metrics:
              - '**/site_files/**'
          json: true
          write_output_files: true
```
It writes the output when i use   steps.files.outputs.metrics_all_changed_files ,  but the list is too long  so that i wanted to write the output to  a json file and read from it later.

### To Reproduce

.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

no json file is created in  .github/outputs

### Relevant log output

```shell
the result in github action :


Run ls -la .github/
total 12
drwxr-xr-x 3 root root 4096 Nov [29]
drwxr-xr-x 5 root root 4096 Nov 29 09:22 ..
drwxr-xr-x 3 root root 4096 Nov 29 09:22 workflows
ls: cannot access '.github/outputs': No such file or directory
Error: Process completed with exit code 2.

```
```


### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
