### ISSUE TITLE
[Feature] Support a list of relative paths por inputs.path

### ISSUE THREAD

**Issue by tuxillo** [tj-actions/changed-files#1760]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Not really. Trying to get certain functionality.

### Describe the solution you'd like?

If possible, a list of relative paths should be allowed for inputs.path:

```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          path:
            - configs/
            - data/
          dir_names: "true
```

### Describe alternatives you've considered?

Nothing really, just removing the extra changed files with some bash-fu :smi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
