### ISSUE TITLE
[Feature] Add option alias for using with Github action matrices

### ISSUE THREAD

**Issue by onedr0p** [tj-actions/changed-files#1812]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Hi 👋🏼 

There's a lot of options you need to set to get this action to work properly with GH matrices, it would be nice if there was an alias to the options needed.

### Describe the solution you'd like?

Create an alias for the following options

```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: apps/**
          escape_json: false
          json: true
          quotepath: false
          safe_output: false
```

It would be nice to have an option that defaulted the above options instead of providing them all

```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: apps/**
          matrix: true
```

### Anything else?

Again, thanks for this awesome action. Happy holiday! ☃️ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
