### ISSUE TITLE
[BUG] `path` input does not work in combination with Github API approach

### ISSUE THREAD

**Issue by gstokkink** [tj-actions/changed-files#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Using the `path` input in combination with the Github API approach (i.e., without a preceding checkout action) does not work. You will receive an error message similar to the following:

```
  Error: The cwd: /home/runner/work/<redacted> does not exist!
```

If you fetch the repo beforehand (which you don't want to, because then it used the .git approach instead of the Github API approach, it works fine. Alternatively if you create the path beforehand using `mkdir`, it will also work.

### To Reproduce

Use the following configuration:

```
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          path: <some_path_that_exists_in_the_repo>
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

I'd expect the `path` input to work correctly with the Github API approach.

### Relevant log output

```shell
##[debug]Working directory: /home/runner/work/<redacted>
  /usr/bin/git rev-parse --is-inside-work-tree
  Error: The cwd: /home/runner/work/<redacted> does not exist!
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Determine changed files
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
