### ISSUE TITLE
[BUG] `warnUnsupportedRESTAPIInputs` failing with composite action & `use_rest_api`

### ISSUE THREAD

**Issue by drewfradette** [tj-actions/changed-files#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The changes in #1853 seem to prevent `tj-actions/changed-files` from being used within a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) while using the new `inputs.use_rest_api: true`.

### Initial Error
```
 Error: EISDIR: illegal operation on a directory, read
```

This is due to the `readFile(actionPath)` in `warnUnsupportedRESTAPIInputs` using `env.GITHUB_ACTION_PATH`. This variable points to a directory, not a file.

Adding `path.join(actionPath, "action.yml")` [around here](https://github.com/tj-actions/changed-files/pull/1853/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R1526) will resolve the `EISDIR` from throwing an error.

### Followup Error
```
Error: Cannot read properties of undefined (reading 'sha')
```

Unfortunately, once I resolved the above error, `warnUnsupportedRESTAPIInputs` still fails to run successfully.

This is due to the contents of `${GITHUB_ACTION_PATH}/action.yml` being the composite action's yaml and not the one associated with `tj-actions/changed-files`. This means there are no `inputs` and `default` cannot be pulled.

### To Reproduce

This composite action, when invoked from a workflow, will cause the issue.

```yaml
# .github/actions/repro/action.yml
name: Repro
description: 'Repro composite action'

runs:
  using: composite
  steps:
    - uses: tj-actions/changed-files@v41
      id: changed-files
      with:
        use_rest_api: true
    - name: Other steps that use changed-files
      shell: bash
      run: echo -e "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
```

```yaml
# .github/workflows/sample.yml
name: Sample Workflow

on:
  workflow_dispatch: {}

jobs:
  sample:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/repro
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

`tj-actions/changed-files` can be used in a composite action with `inputs.use_rest_api: true`.

### Relevant log output

```shell
Relevant logs shown above in the bug description.
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

Sorry this is a bug and not a PR! I was all set to send a fix for the `EISDIR` error but the followup error doesn't have a clear fix as a non-maintainer. Figured an issue would be easier. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
