### ISSUE TITLE
[Feature] Enable `Diff` between Latest PR commit and the Previous one

### ISSUE THREAD

**Issue by ajay-bhargava** [tj-actions/changed-files#1882]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

My GH workflow triggers a ML job every time a commit is pushed 🙍🏾‍♂️ . What I'd like to do is use the `changed-files` GH workflow to make a comparison between the PR HEAD and PR HEAD^ (the current commit and the one preceding it) within a PR for an approved list of files. This is so that any commit willy-nilly doesn't launch a training job. 

This is how I have it setup: 

```
on:
  pull_request:
    branches:
      - master
```

```
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      #----------------------------------------------
      #         setup changed-files@v42 action
      #----------------------------------------------
      - name: Check if files changed
        id: changed_files
        uses: tj-actions/changed-files@v42
        with:
           files_yaml: | 
               - train.py
```

Trouble is, even with this setup the comparison is being made between the master branch and the current commit. Is there functionality to enable `Diff` between two consecutive commits? 

  

### Describe the solution you'd like?

Example of desired functionality is [here](https://stackoverflow.com/questions/75647733/github-action-on-pull-request-process-files-changed-in-the-current-commit). 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CRC-Mismatch** [comment]
@jackton1 I think what OP's looking for is the inverse... `since_last_remote_commit` (at least according to the docs) seems to imply that it would compare the PR's HEAD commit against the PR-target's HEAD commit, instead of comparing to the PR-event's 'HEAD~n' base commit.

I think he wants that each run compares only the PR's latest HEAD commit against the PR's previous commit. I'd guess what he wants could still be solved with a different combination of inputs (if not by simply using `since: HEAD~`, since he mentions `^` but doesn't mention merge-commits, I guess he's just mistook those notations).

**Comment by jackton1** [comment]
Hi @CRC-Mismatch, Yes this is also supported you can achieve this using:

```yml

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
           base_sha: “HEAD~1”
```

**Comment by ruffsl** [comment]
> Yes this is also supported you can achieve this using:

@CRC-Mismatch , could you double check that? As I'm not encountering the expected behavior you describe here:

```yaml
on:
  pull_request:
    paths:
      - 'doc/**'
      - 'src/**'

jobs:
  check_paths:
    name: Check paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changes
        id: get_changes
        uses: tj-actions/changed-files@v45
        with:
          base_sha: 'HEAD~1'
          files_yaml: |
            src:
              - 'src/**'
```

From the debug action's log, I can see that `baseSha` is being set, however I would expect `HEAD~1` should =  `cbcc82c`, and not `2620678` (`HEAD` of `main`), given the `HEAD` of the PR is `efe6313` - with its parent of course being `cbcc82c`.


```
...
  ##[debug]  "sha": "",
  ##[debug]  "baseSha": "HEAD~1",
...
##[debug]Getting current SHA...
  /usr/bin/git rev-parse --verify efe6313d332d9884e578dc50bee32866cc305e2a^{commit}
  efe6313d332d9884e578dc50bee32866cc305e2a
  /usr/bin/git rev-parse --verify efe6313d332d9884e578dc50bee32866cc305e2a^{commit}
  efe6313d332d9884e578dc50bee32866cc305e2a
##[debug]Current SHA: efe6313d332d9884e578dc50bee32866cc305e2a
  /usr/bin/git rev-parse --verify HEAD~1^{commit}
  2620678ac4bd9f531616cac592f1d0fd12dc5880
  /usr/bin/git merge-base 2620678ac4bd9f531616cac592f1d0fd12dc5880 efe6313d332d9884e578dc50bee32866cc305e2a
  18bce5aa56b0e77ef2b357fda6bff046bce486aa
  /usr/bin/git log --format=%H 18bce5aa56b0e77ef2b357fda6bff046bce486aa..efe6313d332d9884e578dc50bee32866cc305e2a
  efe6313d332d9884e578dc50bee32866cc305e2a
  cbcc82cc7a9b02fc7ca336d2fed7910ab34072ed
  86522fda78cab835915114bf63fc59d548ef14e4
  7794df22ac01d98972f0f00f0c4410252b04f844
  fff980fe699d7a7cc8db26b98790f0c88ad8f905
  4ca889d40ba975bd5cd34ffb80073faacb752b51
  3304f4322e45748f12359ca726ba84630e4c0bf8
  df2bcee25b571c2c0c236dfe790950ebf1f3ff80
  /usr/bin/git rev-parse --verify 2620678ac4bd9f531616cac592f1d0fd12dc5880^{commit}
  2620678ac4bd9f531616cac592f1d0fd12dc5880
##[debug]Previous SHA: 2620678ac4bd9f531616cac592f1d0fd12dc5880
  /usr/bin/git merge-base 2620678ac4bd9f531616cac592f1d0fd12dc5880 efe6313d332d9884e578dc50bee32866cc305e2a
  18bce5aa56b0e77ef2b357fda6bff046bce[486](https://github.com/botsandus/auto-sandbox/actions/runs/11132975758/job/30938136508#step:3:487)aa
  /usr/bin/git log --format=%H 18bce5aa56b0e77ef2b357fda6bff046bce486aa..efe6313d332d9884e578dc50bee32866cc305e2a
  efe6313d332d9884e578dc50bee32866cc305e2a
  cbcc82cc7a9b02fc7ca336d2fed7910ab34072ed
  86522fda78cab835915114bf63fc59d548ef14e4
  7794df22ac01d98972f0f00f0c4410252b04f844
  fff980fe699d7a7cc8db26b98790f0c88ad8f905
  4ca889d40ba975bd5cd34ffb80073faacb752b51
  3304f4322e45748f12359ca726ba84630e4c0bf8
  df2bcee25b571c2c0c236dfe790950ebf1f3ff80
...
##[debug]Set output doc_any_changed = true
...
##[debug]Set output src_any_changed = true
...
```

In this case, `${{ steps.get_changes.outputs.src_any_changed }}` is outputting true regardless if the most recent `HEAD` of a PR modifies a source file in `src/` or not, leading me to believe that it's behaving the same way as on action paths, even if the latest PR commit has only modified a document in `doc/`.

Is there something about event ref = PR that is preventing the code path for `baseSha` being interpreted as expected?
