### ISSUE TITLE
Merging issue_comment with pull_request

### ISSUE THREAD

**Issue by Aetherinox** [tj-actions/changed-files#1978]
Sorry, I wasn't sure if I should list this as a bug, or a feature request. 

I am currently trying to have the same job run on two different events
- issue_comment
- pull_request

For issue_comment, the action will run on a certain trigger word.

On `pull_request`, it works great. Obviously on a pull request there are changed files in the mix, and it's able to pull them. However, on `issue_comment`, no files have changed All I'm having it do is simply rescan using the code in my `script` field.

I ran across this issue:
- https://github.com/tj-actions/changed-files/issues/1667

```yml

      # ---------------------------------------------------------------------------------------
      #   Action needed if using 'pull_request' and 'issue_comment'.
      #   To get the pull request, you would normally use ${{ github.event.number }}
      #   however this isnt available for 'issue_comment'
      # ---------------------------------------------------------------------------------------

      - uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Issue number
        run: echo '${{ steps.get_issue_number.outputs.result }}'

      # ---------------------------------------------------------------------------------------
      #   action > checkout
      # ---------------------------------------------------------------------------------------
        
      - uses: actions/checkout@v4
        if: ( github.event_name == 'pull_request' ) || ( github.event_name == 'issue_comment' && contains( github.event.comment.html_url, '/pull/' ) && contains( github.event.comment.body, '/rescan' ) )
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ steps.get_issue_number.outputs.result }}/merge"
          
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: ","
  
      - name: List all modified files
        run: |
          for file in ${MODIFIED_FILES}; do
            echo "$file was modified"
          done
```

Under the step to list all files, the actions console returns
```
Run for file in ${MODIFIED_FILES}; do
  for file in ${MODIFIED_FILES}; do
    echo "$file was modified"
  done
  shell: /usr/bin/bash -e {0}
  env:
```

And then anything in my script field later down fails because it has no files to check.

```
Run actions/github-script@v7
TypeError: Cannot read properties of undefined (reading 'created_at')
```

Not sure how to go about this, and I'm not sure if this is doable according to the issue I linked above.

---

### Describe alternatives you've considered?
NA

### Anything else?
NA

### Code of Conduct
- [x] I agree to follow this project's Code of Conduct
