### ISSUE TITLE
Add support for watching a subset of files.

### ISSUE THREAD

**Issue by jackton1** [tj-actions/changed-files#20]
**Is your feature request related to a problem? Please describe.**
Add support for checking a subset of files that have changed relative to the default branch.

```yaml
   - name: Get all changed files
     id: changed_files
     uses: ...
     with:
       files: ...

   - name: Run step
     if: steps.changed_files.outputs == 'true'
```
