### ISSUE TITLE
[Feature] add previous tag regexp pattern

### ISSUE THREAD

**Issue by aupisarev** [tj-actions/changed-files#2093]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'm triggering the action on the release event. Version tags contain pre-releases, e.g.
```
1.1.0	//current release
1.1.0-2 //pre-release
1.1.0-1 //pre-release
1.0.1	//previous release
1.0.0
```
I want to find files between two release - 1.0.1 and 1.1.0.
Similar problem in #1468.

### Describe the solution you'd like?

Add input `previous_tag_pattern` that is an regexp.
And change method `getPreviousGitTag` of `utils.ts`:
```
export const getPreviousGitTag = async ({
  cwd,
  pattern
}: {
  cwd: string
  pattern: string
}): Promise<{tag: string; sha: string}> => {

  ...

  const tags = stdout.trim().split('\n')
  tags.shift()
  let previousTag = ''

  if (pattern) {
    previousTag = tags.find(value => value.match(pattern)) || ''
  } else if (tags.length > 0) {
    previousTag = tags[0]
  }

  if (!previousTag) {
    core.warning('No previous tag found')
    return {tag: '', sha: ''}
  }

  ...

  return {tag: previousTag, sha}
}
```
I can use it like this
```
        uses: tj-actions/changed-files@v44
        with:
          previous_tag_pattern: ^v[0-9]+.[0-9]+.[0-9]+$
```

### Describe alternatives you've considered?

I can get a similar solution to the problem in the following way, but it's inconvenient and regexp is a more flexible solution
```
- name: Get sha of previous release version
        run: |
          VER=$(git describe --tags --abbrev=0 --match v*.*.* --exclude v*.*.*-* --exclude ${{ github.ref_name }})
          echo "SHA=$(git rev-list --max-count=1 $VER)" >> $GITHUB_ENV

- name: Get changed files by sha
        uses: tj-actions/changed-files@v44
        with:
          base_sha: ${{ env.SHA }}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
