### ISSUE TITLE
[Feature] Allow selecting characteristics about the directories we want to get changes from

### ISSUE THREAD

**Issue by AndresPinerosZen** [tj-actions/changed-files#2096]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I want to run actions on Helm chart folders only. The folders are mixed with other technologies such as kustomize. How can I tell them apart whenever I'm getting the changed files?

### Describe the solution you'd like?

Helm charts have a Chart.yaml in them. Usually when we're dealing with specific technologies, there are certain files that let us know if the folder is relevant or not for that technology. It would be nice if I could say something like "all the directories that changed, only if the directory contains a file with a certain pattern". 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi, @AndresPinerosZen for specific patterns based on different folders you can use the `files_yaml` input.

```yaml
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            doc:
              - '**.md'
              - docs/**
            test:
              - test/**
              - '!test/**.md'
            src:
              - src/**

```
