### ISSUE TITLE
[BUG] added backslash between multiple lines of changes when using separator: '\n' 

### ISSUE THREAD

**Issue by AartsMarco** [tj-actions/changed-files#2148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

We switched from version 37.6.0 to version 44.5.2. When we use a newline separator we get an added backslash between every change, except behind the last change. With version 37.6.0 that didn't happen. 

### To Reproduce

1. linux environment 2 use separator '\n' 3 make multiple changes in the fixture, then run the action 4 the erroneous behavior is added backslash between the changes.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

Expected behaviour is no added backslashes between changes.

### Relevant log output

```shell
List all the files that have changed:
Any:
project-0035B/arn/com/int/bin/arn_prepare.py\
project-0035B/arn/com/int/bin/arn_report.py
Code:
project-0035B/arn/com/int/bin/arn_prepare.py\
project-0035B/arn/com/int/bin/arn_report.py
Python:
project-0035B/arn/com/int/bin/arn_prepare.py\
project-0035B/arn/com/int/bin/arn_report.py
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @AartsMarco to get the same outcome as version 37.6.0 you'll need to disable `safe_output` which doesn't escaped unsafe characters

```yml
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        safe_output: false # set to false because we are using an environment variable to store the output and avoid command injection.

    - name: List all added files
      env:
        ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
      run: |
        for file in ${ADDED_FILES}; do
          echo "$file was added"
        done
```
