### ISSUE TITLE
[BUG] Spaces in file names are not handled correctly

### ISSUE THREAD

**Issue by vertxxyz** [tj-actions/changed-files#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

If you have spaces in your file names and you provide a custom separator (eg. separator: ",") all spaces are replaced by the separator and the results sorted.

### To Reproduce

1. On a repo containing the paths: 
 - `embeds/general 412874536418279426/read-me-1 899830563651854336.json`
 - `Test 1/Test 1.json`
2. Running
```
- id: json_changes
  uses: tj-actions/changed-files@v10.1
  with:
      files: |
        .json$
      separator: ","

- name: List modified files
  run: |
    echo ${{ steps.json_changes.outputs.all_modified_files }}
```
3. Sees the result of:
`1.json,1/Test,412874536418279426/read-me-1,899830563651854336.json,Test,embeds/general`

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expect:
`embeds/general 412874536418279426/read-me-1 899830563651854336.json,Test 2/Test 1.json`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
