### ISSUE TITLE
[Feature] add exclusion(!) support for yaml anchor

### ISSUE THREAD

**Issue by sliu-circle** [tj-actions/changed-files#2186]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Example of `changed-files.yml`

```
part_a: &part_a
  - pattern_a
part_b: &part_b
  - pattern_b
part_c: 
  - !*part_a
  - !*part_b
```

### Describe the solution you'd like?

Add exclusion(!) support for yaml anchor

**Comment by jackton1** [comment]
HI @sliu-circle, YAML anchors and aliases do not directly support exclusion or negation. YAML anchors (&) and aliases (*) are primarily used to reuse and reference nodes within the YAML document. 

You can however define an anchor that includes negation patterns instead

```yml
not_part_a: &not_part_a
  - '!pattern_a'
not_part_b: &not_part_b
  - '!pattern_b'
part_c: 
  - *not_part_a
  - *not_part_b
```
