### ISSUE TITLE
[QUESTION] workflow_dispatch only getting the last 2 

### ISSUE THREAD

**Issue by omri-shilton** [tj-actions/changed-files#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When using workflow dispatch on a branch the diff between commits is only the last two commits in the branch instead of the base branch.
My use case is when im developing in a branch before doing a pull_request.
I may be missing something, im not sure.

### To Reproduce

1. create a development branch
2. change files 
3. manually run the workflow using github actions UI
4. see that the diff is only from the last two commits instead of from the base branch i came out of.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

I would assume that the diff would be from the base branch i came out of.

### Relevant log output

```shell
Using local .git directory
  Running on a workflow_dispatch event...
  Retrieving changes between 6ac698bd2f5e4fd889f13f38add131427a5e9e3d (webapps-changed-files) → 39ddd7daed23f932527a56085cf893123d1c499b (webapps-changed-files)
  All Done!
changed-files-patterns
  All Done!

```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

not that i think its relevant, im using  self hosted runners.
this is my action code
```
  changed-dirs:
    runs-on: custom-runner-2
    outputs:
      matrix: ${{ steps.changed-dirs.outputs.all_changed_files }}
    steps:
      - name: Install git
        run: |
          sudo apt-get update && sudo apt-get install -y jq git git-lfs

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-dirs
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          dir_names: true
          files: "backend/webapps/**"

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @omri-shilton, for [workflow_dispatch](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch) event the GitHub context value for the last commit of the base branch used for comparison `github.event.pull_request.base.sha` is unset since this is limited to only pull requests events as such you’ll need to provide the `base_sha` via the input which can be the git sha of the last commit of the base branch or just the base branch name.


## Example
```

  changed-dirs:
    runs-on: custom-runner-2
    outputs:
      matrix: ${{ steps.changed-dirs.outputs.all_changed_files }}
    steps:
      - name: Install git
        run: |
          sudo apt-get update && sudo apt-get install -y jq git git-lfs

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-dirs
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          dir_names: true
          files: "backend/webapps/**"
          base_sha: main  # <- Add the target branch name here
```
