### ISSUE TITLE
[QUESTION] Files_ignore scope

### ISSUE THREAD

**Issue by tifennlegoff** [tj-actions/changed-files#2302]
Hi, I just have a question about settings for files_ignore, currently we're using the following configuration and the `files_ignore` looks to be ignored.

```      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.0
        with:
          dir_names: true
          files_yaml: |
            terraform:
              - '**/*.tf'
              - '**/*.jsonnet'
              - '**/*.libsonnet'
            jsonnet:
              - '**/*.jsonnet'
              - '**/*.libsonnet'
          files_ignore: |
              .github/**
              modules/**
              **/*module*/**
```

We use this output `${{ steps.changed-files.outputs.terraform_all_changed_files }}` for another job and we see with the debug that there is a folder who should be ignored.

```
##[debug]Set output terraform_all_changed_and_modified_files = global/dashboards/staging global/dashboards/modules
```

There is a way to have files_ignore in this configuration? Actually I tried in this way but I still have the same behavior.

```
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.0
        with:
          dir_names: true
          files_yaml: |
            terraform:
              - '**/*.tf'
              - '**/*.jsonnet'
              - '**/*.libsonnet'
            jsonnet:
              - '**/*.jsonnet'
              - '**/*.libsonnet'
          files_ignore_yaml: |
            terraform:
              - '.github/**'
              - 'modules/**'
              - '**/*module*/**'
            jsonnet:
              - '.github/**'
              - 'modules/**'
              - '**/*module*/**'
 ``` 

Thanks
