### ISSUE TITLE
[Feature] Get changed files in all commits in push

### ISSUE THREAD

**Issue by psychemedia** [tj-actions/changed-files#234]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

The current action seems to just find changed files in the last commit. If a push includes multiple commits, then changed files in all but the last commit will be ignored.

### Describe the solution you'd like?

The ability to list all changed files in all commits in a push that triggers the action.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solarmosaic-kflorence** [comment]
This would actually be really useful on a `pull_request` event as well -- basically I want the ability to "get all changed files since the previous HEAD commit". For example, let's say I create a PR and push a commit (`A`). Then I create a few more commits locally and push those (`B`, `C`). I would want to get only the files that changed after `A`, the previous HEAD commit, up to and including `C`, the new HEAD commit.

**Comment by jackton1** [comment]
Currently the design for pull requests is to look at the HEAD of the base branch I.e the branch that the pull request would be merged into and performs a diff against the current HEAD of the pull request.


The current limitation is with push events where the last commit is used as the reference, still need to give this some more thoughts but it would ideally require pulling all commits of the push branch and perform a diff using the last commit on the remote branch.

**Comment by jackton1** [comment]
@solarmosaic-kflorence This is now available using

```
      - name: Run changed-files with since_last_remote_commit set to true
        id: changed-files-since-last-remote-commit
        uses: tj-actions/changed-files@v11.4
        with:
          since_last_remote_commit: 'true'
```
