### ISSUE TITLE
[BUG] Bad JSON escape sequence

### ISSUE THREAD

**Issue by TimatGDC** [tj-actions/changed-files#2350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I was trying to run the workflow using your [matrix example](https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-example.yml):

```yml
name: 🕵️ Detect Credentials on PR

on:
  pull_request:

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          since_last_remote_commit: true
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-24.04
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo ${{ matrix.files }}
```

The goal is to list only the changed file in this PR.

My team uses Next.js, and as a convention, it generate folder with parenthesis. [See here](https://nextjs.org/docs/app/building-your-application/routing/route-groups#convention). But, when i test it, i ran into an issue:
`Bad JSON escape sequence`

### To Reproduce

1. Create a folder with parenthesis, for example `(auth)`
2. Create a file inside that folder, write on it and push it to activate the workflow
3. There will be a `Bad JSON escape sequence` error due to the escaped parenthesis in the path of the folder

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

In the list of changed files:

```
[".github/workflows/\(folder\)/testfile.txt",".github/workflows/other-test-file.txt",".github/workflows/plateform-auto-detect-credential-pr.yml"]
```

`.github/workflows/\(folder\)/testfile.txt"` should be `.github/workflows/(folder)/testfile.txt"`

### Relevant log output

```shell
# Log for "List All Changed Files"

[".github/workflows/\(folder\)/testfile.txt",".github/workflows/other-test-file.txt",".github/workflows/plateform-auto-detect-credential-pr.yml"]

# Error For Matrix Job

Error when evaluating 'strategy' for job 'matrix-job'. .github/workflows/plateform-auto-detect-credential-pr.yml (Line: 31, Col: 16): Error parsing fromJson,.github/workflows/plateform-auto-detect-credential-pr.yml (Line: 31, Col: 16): Bad JSON escape sequence: \(. Path '', line 1, position 22.,.github/workflows/plateform-auto-detect-credential-pr.yml (Line: 31, Col: 16): Unexpected value ''
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
