### ISSUE TITLE
[Feature] Provide flag to detect if anything in dir has changed

### ISSUE THREAD

**Issue by jtuchel** [tj-actions/changed-files#2404]
### Is this feature missing in the latest version?

- [x] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I just want to detect if anything in a given directory has changed ( file added, file removed, file renamed, ... )

When using this approach

```
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if anything in system directory has changed
        id: check_changed_files
        uses: tj-actions/changed-files@v45
        with:
            files: ${{ runner.name }}/**

    # usage: if: ${{ steps.check_changed_files.outputs.any_changed == 'true' }}
```

it won't detect deleted files for example.

### Describe the solution you'd like?

It would be nice to have a boolean flag like `output_anything_has_changed`

### Describe alternatives you've considered?

I'm not sure if this is possible with a combination of existing flags. I couldn't find a flag for deleted files.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @jtuchel, This already exists as an output.

If you want to detect if a file was  (added, deleted, renamed, ... ), you can use [`any_modified`](https://github.com/tj-actions/changed-files#output_any_modified) output; Alternatively, you can use a combination of [`any_deleted`](https://github.com/tj-actions/changed-files#output_any_deleted) and [`any_changed`](https://github.com/tj-actions/changed-files#output_any_changed) to achieve the same outcome.


### E.g

1. [`any_modified`](https://github.com/tj-actions/changed-files#output_any_modified)
```yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if anything in system directory has changed
        id: check_changed_files
        uses: tj-actions/changed-files@v45
        with:
            files: ${{ runner.name }}/**

    - name: Run step if any of the listed files above is modified
      if: steps.check_changed_files.outputs.any_modified == 'true' 
```

2. A combination of [`any_deleted`](https://github.com/tj-actions/changed-files#output_any_deleted) and [`any_changed`](https://github.com/tj-actions/changed-files#output_any_changed)
```yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if anything in system directory has changed
        id: check_changed_files
        uses: tj-actions/changed-files@v45
        with:
            files: ${{ runner.name }}/**

    - name: Run step if any of the listed files above is modified
      if: steps.check_changed_files.outputs.any_changed == 'true' || steps.changed-files-specific.outputs.any_deleted == 'true' 
```

If you would like more information on available outputs. See the [documentation](https://github.com/tj-actions/changed-files#outputs-)
