### ISSUE TITLE
Input argument to exclude deleted folders

### ISSUE THREAD

**Issue by rpuserh** [tj-actions/changed-files#2423]
### Is this feature missing in the latest version?

- [x] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Add option to exclude deleted folders.
For example if i have following file structure 

```
.
|-- ws1
|   |-- m1.tf
|   `-- m2.tf
`-- ws2
    `-- m.tf
```
and now if i delete following files 

```
.
|-- ws1
|   |-- m1.tf
|   `-- m2.tf (DELETE)
`-- ws2       (DELETE)
    `-- m.tf 
```
output id like to see is 

```
['./ws1']
```

### Describe the solution you'd like?

I'd like some new input that will exclude deleted folders from list `exclude_deleted_folders`

example 

```
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-dir-selector
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          json: true
          escape_json: false
          exclude_deleted_folders: true
          files: |
            **/*.tf
            *.tf
    outputs:
      any_modified: ${{ steps.changed-dir-selector.outputs.any_modified }}
```

Ill expect to have list of dirs that have added/changed/deleted files  in var  except dirs that were completely deleted

### Describe alternatives you've considered?

Alternative will be just to write bash script

### Anything else?

n/a

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
