### ISSUE TITLE
[BUG] Files input doesn't work when running with `act`

### ISSUE THREAD

**Issue by stevehipwell** [tj-actions/changed-files#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running this action with `act` (medium image) and providing a `files` input, the full list of modified files is returned rather than the a filtered list. 

### To Reproduce

1. Add action to repo as configured below
2. Add multiple changed files in commit, but only 1 with a _.yaml_ extension
2. Run action locally with `act`

```yaml
name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changes
        id: changes
        uses: tj-actions/changed-files@v11.6
        with:
          files: \.yaml$

      - name: Show changes
        shell: bash
        run: |
          set -euo pipefail

          for file in ${{ steps.changes.outputs.all_modified_files }}
          do
            echo "${file}"
          done
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The same output should happen with `act` and on GitHub.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
