### ISSUE TITLE
[BUG] wrong result of any_change output

### ISSUE THREAD

**Issue by kaslav** [tj-actions/changed-files#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

`any_changed` output is `false` even though a file supplied in `files` input has been modified.

### To Reproduce

These steps have to be defined:
```
- name: Check whether proto files have changed
  id: protos-changed
  uses: tj-actions/changed-files@v13
  with:
    files: |
      services.proto

- name: Run if proto file has changed
  if: steps.protos-changed.outputs.any_changed == 'true'
  run: echo proto files have changed
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Expected behaviour is to output `any_changed` as `true` if a file supplied in `files` input has been modified.

### Relevant log output

```shell
Getting diff...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: .github/workflows/build.yaml protobuf/src/main/protobuf/services/v1/services.proto
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: .github/workflows/build.yaml protobuf/src/main/protobuf/services/v1/services.proto
  All changed files: .github/workflows/build.yaml protobuf/src/main/protobuf/services/v1/services.proto
  All modified files: .github/workflows/deploy.yaml protobuf/src/main/protobuf/services/v1/services.proto
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
