### ISSUE TITLE
[BUG] Negating filter doesn't work

### ISSUE THREAD

**Issue by AdrianGarcia-StayWithReside** [tj-actions/changed-files#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Using a negation filter after another filter doesn't remove files from the modified file lists as expected. Instead, all .py files are included.

### To Reproduce

The output of this action should include all python files that _are not_ in the migrations folder.
``` YAML
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.1
      with:
        files: |
          '**.py'
          !backend/**/migrations/*
```
Except it outputs files in the migrations folder:
```
backend/core/migrations/0006_auto_20220127_1838.py
backend/core/models/some_model.py
backend/core/serializers/some_serializer.py
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Files that match the `!backend/**/migrations/*` will be removed from the file list as defined in the Github workflow syntax:
> Using an exclamation mark (!) in front of a pattern negates it. When a file matches a pattern and also matches a negative pattern defined later in the file, the file will not be included.

So the following file list is expected:
```
backend/core/models/some_model.py
backend/core/serializers/some_serializer.py
```

### Anything else?

I might just be an idiot and my patterns don't work. More details can be provided if needed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
