### ISSUE TITLE
[Feature] Add support for detecting changes in submodules

### ISSUE THREAD

**Issue by pkit** [tj-actions/changed-files#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

This action uses github API which will notice any submodule change as a change in `./submodule_name` "file" and nothing else.
Actual changes in actual files will go unnoticed

### To Reproduce

Run on any repo with a change in a submodule
See the following output:
```
Resolving repository path...
  Setting up 'temp_changed_files' remote...
  No 'temp_changed_files' remote found
  Creating 'temp_changed_files' remote...
  Getting HEAD info...
  Retrieving changes between 12345789abcdef (main) → 22345789abcdef (main)
  Getting diff...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: submodule_name
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: submodule_name
  All changed files: submodule_name
  All modified files: submodule_name
```

### What OS are you seeing the problem on?

all

### Expected behavior?

Actual subdirectories are checked (not only the Github API output)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@pkit Seems like this is a feature request as submodules aren't supported at the moment and can you also include the workflow configuration i.e what were you trying to do ?

Based on the current design all change detection is done locally via a git executable and no interactions to Github's API is performed.

**Comment by pkit** [comment]
> Based on the current design all change detection is done locally via a git executable and no interactions to Github's API is performed.

The github repo was checked out with all the submodules locally

I can see that call stack goes like that: `tj-actions/changed-files ->  tj-actions/glob@v6 -> actions/github-script@v5` which does call github API

Example workflow excerpt:
```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.BUILD_BOT_TOKEN }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.4
        with:
          files: |
            "submodule_name/**"
            "*.js"
```
