### ISSUE TITLE
[BUG] Using the fork point to detect file changes.

### ISSUE THREAD

**Issue by grzegorzkrukowski** [tj-actions/changed-files#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

We are experience a weird behaviour of changed files being returned on Pull Requests.

You can find my workflow runs here:
https://github.com/raycast/extensions/runs/5148147932?check_suite_focus=true#step:3:107
https://github.com/raycast/extensions/runs/5149182650?check_suite_focus=true#step:3:107

Both of them runs on the same PR and against same `main` - the only different is that on main there were 2 commits added meanwhile I was testing it, you can see it here:
<img width="822" alt="CleanShot 2022-02-11 at 00 28 42@2x" src="https://user-images.githubusercontent.com/1301068/153514269-d0605964-210c-4313-9ff5-f641f9eaad3e.png">

Goal of our PRs is to validate files added by PR - I want to get files that were modified in PRs - only those files.
But from time to time we are getting weird combination of files coming from changes done on `main` branch like you can see in first workflow run above.
Expected behaviour is to get just the list of changed files in given PR - so the correct one is the second run.

Our workflow is doing just this:
```
- name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.3
```

We have been playing with both:
```
base_sha: ${{ github.event.pull_request.base.sha }}
sha: ${{ github.event.pull_request.head.sha }}
```
and for some runs it helped, but it broke other PRs :/ it's a bit randomly behaving.

### To Reproduce

1. Use:
```
- name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.3
```

2. Create several PRs coming from forked repositories, meanwhile adding few commits in main repository
3. Observe how randomly sometimes commits from `main` are taken into account. Some commits on main can fix the problem or break it when you re-run existing checks on PRs.

### What OS are you seeing the problem on?

all

### Expected behavior?

I would expect consistency.

Goal is to always get just changed files in PR - ignoring any changes that happened on main.

### Relevant log output

Wrong:
https://github.com/raycast/extensions/runs/5148147932?check_suite_focus=true#step:3:107

Right:
https://github.com/raycast/extensions/runs/5149182650?check_suite_focus=true#step:3:107

Just re-runed after 2 commits were added.

### Anything else?

All repositories and workflows are public.
We have more runs like this happening:
https://github.com/raycast/extensions/runs/5143485235?check_suite_focus=true

Not sure if that's happening because of forking or what's the problem - if we are doing something wrong in our workflows, please advice.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grzegorzkrukowski** [comment]
I am afraid that doesn't work:

Here is failing run for Forked PR - it doesn't see a commit.

https://github.com/raycast/extensions/actions/runs/1833497844

But thanks I will ask on `checkout` repository

**Comment by jackton1** [comment]
@grzegorzkrukowski After testing this I found the source of the error and should be resolved in #358

**Comment by grzegorzkrukowski** [comment]
Thanks @jackton1 - so now should I use my original version or one with ‘ref’ ?

**Comment by jackton1** [comment]
@grzegorzkrukowski It should be available in the latest release [v14.6](https://github.com/tj-actions/changed-files/releases).

**Comment by grzegorzkrukowski** [comment]
Ok still - which version should be working now ? :) the one where I checkout merged commit or one with “ref” ?

**Comment by jackton1** [comment]
You need to upgrade the action which fixes usage of merge commits 

```yaml

 - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6

```

**Comment by grzegorzkrukowski** [comment]
Hey @jackton1 - I'm afraid it's still now working as it should:

Here is a run using code from your last message:
https://github.com/raycast/extensions/runs/5185457484?check_suite_focus=true

And here is a run when I tried to run with `ref` and `repository` to get PR repo:
https://github.com/raycast/extensions/runs/5185420161?check_suite_focus=true

**Comment by jackton1** [comment]
@grzegorzkrukowski Just to confirm using https://github.com/ad-m/github-push-action/issues/20#issuecomment-543139381 also doesn't solve the issue for you ??

**Comment by jackton1** [comment]
Can you also pass the head_ref to the action

```
- name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
   - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
      with:
         base_ref: ${{ github.head_ref }}
```
