### ISSUE TITLE
[Feature] `since_last_remote_commit` incorrect `on: push` of new branch

### ISSUE THREAD

**Issue by samm81** [tj-actions/changed-files#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

with `since_last_remote_commit: true` in a workflow that is `on: push` the very first push of a new branch will return no files changed

this is because [the _current_ sha is used as a default](https://github.com/tj-actions/changed-files/blob/32d6fb28f082f273420574e9de0a30be993bba58/action.yml#L130) when `github.event.before` is missing (which it is when a branch is first pushed)

but comparing to the current sha _always_ returns no files changed

I've solved this personally with an extra step to find the appropriate base sha (I use the parent of the sha of the first commit in the push, note that `github.event.commits` isn't available on all actions)

```yaml
jobs:
  preflight:
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # get entire repo history
    - name: find base sha
      id: find-base-sha
      run: |
        # `before` is what this ref pointed to before this push
        # if the branch is new, it will be zeros
        # in which case we'll compare to the parent commit of the first commit in this push
        # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
        if [[ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
          echo "::set-output sha=${{ github.event.before }}"
        else
          echo "::set-output sha=${{ github.event.commits[0]['id'] }}~1"
        fi
    - uses: tj-actions/changed-files@v15
      id: changed-files
      with:
        base_sha: ${{ steps.find-base-sha.outputs.sha }}
```

### To Reproduce

```yaml
on:
  [push]
jobs:
  preflight:
    outputs:
      should-run: ${{ steps.any-changed.outputs.any-changed }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v15
      id: changed-files
      with:
        since_last_remote_commit: true
    - id: any-changed
      run: echo "::set-output name=any-changed::${{ steps.changed-files.outputs.any_changed }}"
```

then create and push a new branch

`any-changed` will always be false

### What OS are you seeing the problem on?

all

### Expected behavior?

expect `any-changed` to be true if the new branch changed any files

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
