### ISSUE TITLE
How can I set the action to review all commits since the last workflow run?

### ISSUE THREAD

**Issue by caffeinatedMike** [tj-actions/changed-files#400]
I have the following workflow
```yaml
jobs:
  api_metadata_refresh:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: file-changes
        name: Get changed-files in step_two directory
        uses: tj-actions/changed-files@v14.3
        with:
          files: |
            **/step_two/*
      - id: auth
        if: ${{ steps.file-changes.outputs.any_changed == 'true' || steps.file-changes.outputs.any_modified == 'true' }}
        name: Authenticate
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - id: deploy
        if: ${{ steps.file-changes.outputs.any_changed == 'true' || steps.file-changes.outputs.any_modified == 'true' }}
        name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          ...
```
Which works great for the previous commit, but when I make multiple commits locally and push them at the end of the day the above workflow does not catch changes from the commits that aren't the last commit in the bunch.

How can I determine the last commit in which the workflow ran on and set that point as the starting point for the latest push's workflow job?
