### ISSUE TITLE
[BUG] Get all modified/deleted/added files from a Pull Request

### ISSUE THREAD

**Issue by Xat59** [tj-actions/changed-files#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hello team,

I am trying to list all files that have been modified / removed / added from the current pull request comparing to the target branch of the PR.

Here is what I tried : 

```yaml
---
name: Get all changed files from this PR

on:
  push:
    branches: 'bau/*'
  pull_request:
    branches: 'bau/*'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
          since_last_remote_commit: 'true'
```

Instead of returning the full list of files that have been changed in the PR, it returns only files regarding the **second to last** commit.
I can also see that the `INPUT_BASE_SHA` used is  the **second to last** SHA from the PR. That's probably the reason.

### To Reproduce

1. Have an existing repo with `main` default branch
2. Create the provided workflow
3. Create a new branch `bau/test` from `main`
4. Edit several files, commit them, and push to `bau/test` branch
5. From the same `bau/test` branch, edit a new file , commit it and push it in `bau/test`
6. The GH workflow runs, and `tj-actions/changed-files` only returns the latest changed file at step 5, but not files from step 4.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Regarding my workflow it should return all files removed/added/edited from the target branch, not only comparing the new commit with the **second to last**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
