### ISSUE TITLE
[BUG] Unexpected result

### ISSUE THREAD

**Issue by Xat59** [tj-actions/changed-files#412]
Hello guys,

I would like to list all files that have changed (by changed I mean removed, edited, added) from my PR.

When using this workflow, I get unexpected result : 

```yaml
---
name: Get all changed files from this PR

on:
  push:
    branches: 'bau/*'
  pull_request:
    branches: 'bau/*'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
```

This returns only 1 file while I have 3 modified files in my PR... : 

```
  Resolving repository path...
  Retrieving changes between 95635589e714fa8c58d7e0206a966ff8fd311216 (bau/chg0001) → 2c0046c6f49aceda59bc9cff304140445da4bb72 (bau/chg0001)
  Getting diff...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: .github/workflows/terragrunt.yml
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: .github/workflows/terragrunt.yml
  All changed files: .github/workflows/terragrunt.yml
  All modified files: .github/workflows/terragrunt.yml
```

Note `95635589e714fa8c58d7e0206a966ff8fd311216` is the second to last SHA in the PR, and  `2c0046c6f49aceda59bc9cff304140445da4bb72` is the last SHA in the PR.

So yeah of course between these 2 commits there are only 1 file, but that is not at all what I need.

I need to retrieve **all files from the PR**.

**Comment by jackton1** [comment]
@Xat59 That's because your action was triggered from a push event

```yml
on:
  push:
    branches: 'bau/*'
  pull_request:
    branches: 'bau/*'
```

```
Retrieving changes between 95635589e714fa8c58d7e0206a966ff8fd311216 (bau/chg0001) → 2c0046c6f49aceda59bc9cff304140445da4bb72 (bau/chg0001)
```

This line above says you pushed a change to your Pull Request and the push event triggered the action on your branch which wouldn't show you changes that have been made in your PR but only changes since the previous commit.


### Solution

Change the trigger above to 
```yml
on:
  pull_request:
    branches: 'main'
```

Remove the push entirely if you only want to list pull request files that have changed.

**Comment by Xat59** [comment]
@jackton1 I've other jobs that must be ran after retrieving the list of changed files.

I've did what you said : 

```
---
name: Get all changed files from this PR

on:
  push:
    branches: 'bau/*'
  pull_request:
    branches: ['main',’master']

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v17.2
```

But that still returns the last commit, not the full list of files.
