### ISSUE TITLE
failed to  Get list of files on pull request merge

### ISSUE THREAD

**Issue by rajeshwer** [tj-actions/changed-files#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hello 
I am trying to get the name of the file added after pull request is merged
below is my work flow which i am currently using 
```
name: CI

on:
  push:
    branches: [poc]
  pull_request:
    branches: [poc]
    types: [opened, synchronize, edited, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            **/*.json
      - name: validate access.json file
        run: |
          cat  ${{ steps.changed-files-specific.outputs.all_changed_files }}|jq
      - name: Read access.json
        id: readAccessFile
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ steps.changed-files-specific.outputs.all_changed_files }}
```

It works a expected by listing the newly added file name and reading when pull request is raised and pull request status is open .
But when pull request is merged It is not working as expected .
Output of github actions :

```
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
changed-files
  Resolving repository path...
  Retrieving changes between 307[82](https://github.com/myrepo/access/runs/5415320264?check_suite_focus=true#step:3:82)7b1f6e70f1f2ceb[92](https://github.com/myrepo/access/runs/5415320264?check_suite_focus=true#step:3:92)646800[94](https://github.com/myrepo/access/runs/5415320264?check_suite_focus=true#step:3:94)ffd610535d (security_poc) → 307827b1f6e70f1f2ceb9264680094ffd610535d (test1)
  Getting diff...
  Input files pattern: accessRequest/2022-02-23-12:04:54-0800-access.json|accessRequest/acc.json
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: 
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: 
  All changed files: 
  All modified files:
```
I want it to work for all  actions 
pull_request:[opened, synchronize, edited, closed]

### To Reproduce

use workflow which i am using .
create a pull request to any file in repo with extension .json.
Reading newly modified/added file name can be read.
but when the PR is merged unable to read the file name 
```
  Getting diff...
  Input files pattern: accessRequest/2022-02-23-12:04:54-0800-access.json|accessRequest/acc.json
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: 
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: 
  All changed files: 
  All modified files:
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Expecting to read the file name with extension **/*.json from pull request merge 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
