### ISSUE TITLE
[BUG] File names with non ascii characters results in octal escape sequence output

### ISSUE THREAD

**Issue by nathangiusti** [tj-actions/changed-files#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have a file called bad-char-é.txt

When I do a get changed files character is not decoded correctly 

![image](https://user-images.githubusercontent.com/6363879/158672739-eac2bb23-adef-4286-94f3-4a83bc679e2d.png)

### To Reproduce

- Create a file called bad-char-é.txt
- Modify the file
- Run `tj-actions/changed-files` on the branch, example workflow

```yaml
name: workflow
on: [pull_request]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.2
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```

### What OS are you seeing the problem on?

all

### Expected behavior?

Filename should be passed out as bad-char-é.txt

### Relevant log output

```shell
Run tj-actions/changed-files@v18.2
  with:
    token: ***
    separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: 9b9e2bd41fe87a55f0318f0e239e34664a847454
    since_last_remote_commit: false
    use_fork_point: false
Run # "Set base sha..."
  # "Set base sha..."
  if [[ -n "" ]]; then
    echo "::set-output name=base_sha::"
  elif [[ "false" == "true" && "" != "0000000000000000000000000000000000000000" ]]; then
      echo "::set-output name=base_sha::"
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: nathangiusti/Deserialize-Power-BI-Report
    GITHUB_BASE_REF: main
    GITHUB_HEAD_REF: bug-test
    GITHUB_ACTION_PATH: /home/runner/work/_actions/tj-actions/changed-files/v18.2
    INPUT_SHA: 9b9e2bd41fe87a55f0318f0e239e34664a847454
    INPUT_BASE_SHA: 
    INPUT_TOKEN: ***
    INPUT_PATH: 
    INPUT_USE_FORK_POINT: false
changed-files-diff-sha
  Resolving repository path...
  Setting up 'temp_changed_files' remote...
  No 'temp_changed_files' remote found
  Creating 'temp_changed_files' remote...
  Getting HEAD SHA...
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
  From https://github.com/nathangiusti/Deserialize-Power-BI-Report
   * [new branch]      main       -> main
   * [new branch]      main       -> temp_changed_files/main
  Verifying commit SHA...
Run tj-actions/glob@v7.8
  with:
    files-separator: 
  
    excluded-files-separator: 
  
    base-sha: 70e93c14ca1f49f991518b9fa41c8b19daca84fb
    sha: 9b9e2bd41fe87a55f0318f0e239e34664a847454
    include-deleted-files: true
    separator: |
    files-from-source-file-separator: 
  
    excluded-files-from-source-file-separator: 
  
    follow-symbolic-links: true
    strip-top-level-dir: true
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/Deserialize-Power-BI-Report/Deserialize-Power-BI-Report
/usr/bin/git diff --diff-filter=D --name-only 70e93c14ca1f49f991518b9fa41c8b19daca84fb 9b9e2bd41fe87a55f0318f0e239e34664a847454

Warning: No match found for specified patterns. Ensure that subdirectory patterns a prefixed with "**/". See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
changed-files
0s
Run for file in "bad-char-\303\251.txt"; do
  for file in "bad-char-\303\251.txt"; do
    echo "$file was changed"
  done
  shell: /usr/bin/bash -e {0}
bad-char-\303\251.txt was changed
```

### Anything else?

https://github.com/nathangiusti/Deserialize-Power-BI-Report/runs/5575418851?check_suite_focus=true

Example of the bad run

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
