### ISSUE TITLE
[Feature] Get changes from all commits from a single push

### ISSUE THREAD

**Issue by grzegorzkrukowski** [tj-actions/changed-files#447]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

In one of my repositories we have a situation that users are pushing multiple commits in a single push.
I am running one action on each push and I would like to get the changes from all commits that were added by this action.

### Describe the solution you'd like?

At the moment it's just getting changes from the latest commit and commit before it.
I would like to have an option to use "last commit existing before push" as a BASE_SHA.

### Anything else?

Here is the example of the use-case I am talking about:
https://github.com/raycast/extensions/commits/main

The exact two commits are visible here:
<img width="1206" alt="CleanShot 2022-03-24 at 11 32 43@2x" src="https://user-images.githubusercontent.com/1301068/159897644-570d60d4-34dd-47a6-a4c0-4c01591b0625.png">

In my case the changes from the first one without Action were missing and never caught by my actions due to that problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@grzegorzkrukowski This feature is available  using


```yml
      - name: Run changed-files using the last commit on the remote branch
        id: changed-files-since-last-remote-commit
        uses: tj-actions/changed-files@v18.4
        with:
          since_last_remote_commit: "true"

         ``` 

You can check out the README for more examples.
