### ISSUE TITLE
[BUG] Fails in Self-Hosted Runner

### ISSUE THREAD

**Issue by martindevnow** [tj-actions/changed-files#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

A simple job, on a self-hosted runner (Linux) fails, with the following error:

```
Run tj-actions/changed-files@v19
Run # "Set base sha..."
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
  Resolving repository path...
  Setting up 'temp_changed_files' remote...
  No 'temp_changed_files' remote found
  Creating 'temp_changed_files' remote...
  fatal: not a git repository (or any of the parent directories): .git
```

### To Reproduce

Create a simple job:

```
name: 'Test Check Files Changed Action'

on:
  push:
    branches: [my-feature-branch]

jobs:
  check_base_image_changed:
    name: Check Files Changed
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            Dockerfile
            package*.json
```

Use a self-hosted runner

Push a change to the branch

See the error

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04, ubuntu-18.04

### Expected behavior?

I expect the job to be successful, and for me to be able to inspect the outputs of this step

### Relevant log output

```shell
Run tj-actions/changed-files@v19
  with:
    files: Dockerfile
  package*.json
  
    token: ***
    separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: 92887a4c13c1fa2edd08a94368c60f69dddd1a52
    since_last_remote_commit: false
    use_fork_point: false
    quotepath: true
Run # "Set base sha..."
  # "Set base sha..."
  if [[ -n "" ]]; then
    echo "::set-output name=base_sha::"
  elif [[ "false" == "true" && "3be99cac35cadc74839f3525b3ba9fa603af48df" != "0000000000000000000000000000000000000000" ]]; then
      echo "::set-output name=base_sha::3be99cac35cadc74839f3525b3ba9fa603af48df"
  fi
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: org/repo
    GITHUB_BASE_REF: 
    GITHUB_HEAD_REF: 
    GITHUB_ACTION_PATH: /tmp/_actions/tj-actions/changed-files/v19
    INPUT_SHA: 92887a4c13c1fa2edd08a94368c60f69dddd1a52
    INPUT_BASE_SHA: 
    INPUT_TOKEN: ***
    INPUT_PATH: 
    INPUT_USE_FORK_POINT: false
changed-files-diff-sha
  Resolving repository path...
  Setting up 'temp_changed_files' remote...
  No 'temp_changed_files' remote found
  Creating 'temp_changed_files' remote...
  fatal: not a git repository (or any of the parent directories): .git
  Error: Process completed with exit code 128.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
