### ISSUE TITLE
[Feature] Handle Pipeline Error

### ISSUE THREAD

**Issue by BenjaminKlatt** [tj-actions/changed-files#500]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

We use the action to identify changes in a specific module and trigger subsequent deployments only if need.
Now, in case of an error in the subsequent process, there is no chance to rerun the pipeline as the file change filter does not detect any files changed.

Example
````
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v20.2
        with:
          files: |
            submodule/**
      - name: Setup Node
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
````

### Describe the solution you'd like?

Maybe just a matter of an existing configuration we could not figure out:
How to setup the pipeline, to not filter subsequent processes wich were not successful before?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
