### ISSUE TITLE
[BUG] "Unable to locate the current sha" when using `use_fork_point `

### ISSUE THREAD

**Issue by dmohns** [tj-actions/changed-files#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Running `changed-files` action one a large mono repo "sometimes" yields

```
 Warning: Unable to locate the previous sha: 
  Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
```

in an un-reproducible way. Sometimes rebasing and force-pushing fixes it, sometimes merging main fixes it. But also sometimes neither of them does.

The configuration I use is

```
jobs:
  sqlfluff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          use_fork_point: "true"
```

Note how `previous sha` is empty. Unfortunately this happens in private repos and I cannot share the exact workflow run.

### To Reproduce

Unfortunately, I couldn't find a way to reproduce this error 100% of the time.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

`changed-files` should work on every workflow run.

### Relevant log output

```shell
Resolving repository path...
  Getting HEAD SHA...
  Getting fork point...
  From https://github.com/***
   * [new branch]            main       -> main
  Verifying commit SHA...
  Warning: Unable to locate the previous sha: 
  Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
  Error: Process completed with exit code 1.
```

### Anything else?

PS: Converted from a comment in https://github.com/tj-actions/changed-files/issues/458 as I think it's a different issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
