### ISSUE TITLE
[BUG] Separator removing double-quotes

### ISSUE THREAD

**Issue by SiddhantSadangi** [tj-actions/changed-files#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The separator parameter is stripping out escaped double quotes

### To Reproduce

GitHub Actions Steps:

```yaml
    - name: Get changed notebooks
      id: changed-notebooks
      uses: tj-actions/changed-files@v23.1
      with:
        separator: "\", \""
        files: |
          **/*.ipynb
    - name: List all changed notebooks
      id: output
      if: steps.changed-notebooks.outputs.any_changed == 'true'
      run: |
        echo -e "Separator: \", \""
        echo -e "Output: ${{ steps.changed-notebooks.outputs.all_changed_files }}"
        echo -e "JSON format: {\"path\":[\"${{ steps.changed-notebooks.outputs.all_changed_files }}\""]}"
        echo -e "::set-output name=changed_notebooks::{\"path\":[\"${{ steps.changed-notebooks.outputs.all_changed_files }}\""]}"
        echo -e "Valid JSON? ${{toJSON(needs.get-notebooks.outputs.changed_notebooks)}}"
```

Result:
```bash
Separator: ", "
Output: fail.ipynb, pass.ipynb
JSON format: {"path":["fail.ipynb, pass.ipynb"]}
echo -e ::set-output name=changed_notebooks::{"path":["fail.ipynb, pass.ipynb"]}
JSON: null
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

```bash
Separator: ", "
Output: fail.ipynb", "pass.ipynb
JSON format: {"path":["fail.ipynb", "pass.ipynb"]}
echo -e ::set-output name=changed_notebooks::{"path":["fail.ipynb", "pass.ipynb"]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
