### ISSUE TITLE
[BUG] Will output all changed files if not file matches the `**/*.sql` pattern

### ISSUE THREAD

**Issue by ecmadao** [tj-actions/changed-files#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

If the `files` pattern contains `**/*.sql`, and it didn't match any changed files in the pull request, will print a warning:

> No match found for specified patterns. Ensure that subdirectory patterns are prefixed with "**/" and all multi line string patterns are specified without quotes. See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

And the action will output all changed files, seems this doesn't make sense.

### To Reproduce

1. Create a workflow like:

```yml
on: [pull_request]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    name: Changed files
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24.1
        with:
          files: |
            **/*.sql 
      - name: Echo files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
        shell: bash
```

**Note: the `files` must has the pattern: `**/*.sql`**

2. Make some changes (not change any SQL files)
3. Create the pull request and check the action.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The action should return empty as no changed files can match the `**/*.sql` pattern.

### Anything else?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
