### ISSUE TITLE
[BUG] dir_names = true not returning directories with changed files

### ISSUE THREAD

**Issue by discordianfish** [tj-actions/changed-files#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Using:
```
      - name: Get changed files
        id: changed-files
        with:
          files: dir
```

It correctly detects the following changed files:
```
dir/foo/script.py
dir/bar/script.py
```

But setting `dir_names = true` returns no changed files. Also tried `dir_names = "true"` without it making a difference.

### To Reproduce

Should be reproducable using these steps:
```
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        with:
          files: dir
          dir_names: "true"
        uses: tj-actions/changed-files@v29.0.0
```
and then modifying files in dir/<something>/file

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expect steps.changed-files.outputs.all_changed_files to be set to:
- dir/foo
- dir/bar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@discordianfish Have you tried  using 

```yml

      - name: Get changed files
        uses: tj-actions/changed-files@v29.0.0
        id: changed-files
        with:
          files: dir/**
          dir_names: "true"

```

**Comment by arthurk** [comment]
I have the same problem. Upgrading from v28 to v29 it stopped working in my workflow. I'm also using `dir_names: "true"`.

```yaml
      - name: Get changed helm chart files
        id: changed-files-helm
        uses: tj-actions/changed-files@v29.0.0
        with:
          base_sha: ${{ steps.last_successful_commit.outputs.commit_hash }}
          dir_names: 'true'
          files: |
            helm-charts/**
```
