### ISSUE TITLE
[Feature] Get all changes on current branch against a base_sha

### ISSUE THREAD

**Issue by boranliu** [tj-actions/changed-files#599]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Currently I am trying to get all the modified files from a PR when I push a single commit (with potentially multiple commits pushed earlier), and would like to see all modified files (including all modified files from previously pushed commits) against a different base_sha other than the last commit from the same remote branch.

This should be similar to `since_last_remote_commit` but with the ability to input a base_sha. 

Use case for this will be something like branching out from a base branch and trying to check all modified files from the current branch to the base branch (with multiple commits pushed to a PR)

### Describe the solution you'd like?

The ability to list all changed files in all commits in current branch that triggers the actions against another branch (base_sha)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
By default using 

```yml

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.0

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```


By default, the diff is based on the last commit SHA on the Target branch of the pull request and the current pushed commit SHA of the current branch

Can you elaborate on the difference in your use case?

**Comment by boranliu** [comment]
> @boranliu By default using
> 
> ```yaml
> on:
>   pull_request:
>     branches:
>       - '**'
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     name: Test changed-files
>     steps:
>       - uses: actions/checkout@v3
>         with:
>           fetch-depth: 0
> 
>       - name: Get changed files
>         id: changed-files
>         uses: tj-actions/changed-files@v29.0.0
> 
>       - name: List all changed files
>         run: |
>           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
>             echo "$file was changed"
>           done
> ```
> 
> The diff is based on the last commit SHA on the Target branch of the pull request and the current pushed commit SHA of the current branch
> 
> Can you elaborate on the difference in your use case?

Thanks for the quick response.

My use case is for **on push** event and one example can be illustrated as below:
- Create a branch B which is branched off branch A
- PR on branch B
- Push several commits (in individual commands, so multiple pushes) to branch B
- Lets assume the last commit on branch A has sha 123

So I would like to get all changes files on the current branch B against branch A (essentially sha 123) for every new push (which means that not only from the current commit that I pushed, but all the commits pushed earlier). Right now the behavior I spotted is that diff is only calculated between each new commit I pushed on branch B and the commit with sha 123 (from branch A). 

One example could be:
On branch B:
- Push a commit with file1.txt changed
- Push another commit with file2.txt changed

Now the expected behavior I am trying to achieve is that for the second commit, `all_modified_files` should return both `file1.txt` and `file2.txt`

**Comment by jackton1** [comment]
@boranliu In that case I'll suggest using 

```yml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.1
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
```
