### ISSUE TITLE
Looping over files with spaces.

### ISSUE THREAD

**Issue by preritdas** [tj-actions/changed-files#609]
Hi, I've been looking through #216 and related information, including the use of `IFS` in BASH. Unfortunately, after countless attempts, I can't seem to get it to work with this action. I'm not sure if it's an issue with this action, a behavior of GitHub actions, or an error in my implementation. 

I'm opening this issue because I tried the same script on my Ubuntu server and it worked like a charm. 

## Attempt
```yml
name: pdf render

on:
  push:
    paths:
      - '**/**.md'


jobs:
  render:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: "**/**.md"
          separator: ","

      - name: List all changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          IFS=","
          echo ".$IFS."
          for file in ${{ steps.changed-files.outputs.all_changed_files }}
          do echo $file was changed
          done
          unset IFS
```

## Response

```
Folder/Sub Folder/First Markdown File.md,Folder/Other Subfolder/Another Markdown File.md
.,.
Folder/Sub was changed
Folder/First was changed
Markdown was changed
File.md was changed
Folder/Other was changed
Subfolder/Another was changed
Markdown was changed
File.md was changed
```

## Expected

```
Folder/Sub Folder/First Markdown File.md,Folder/Other Subfolder/Another Markdown File.md
.,.
Folder/Sub Folder/First Markdown File.md was changed
Folder/Other Subfolder/Another Markdown File.md was changed
```

It seems the IFS is being changed because when I `echo ".$IFS."` after setting `IFS=","`, the shell prints `.,.` as expected. But when I loop, no change. 

As I mentioned earlier, I tried this on my own Ubuntu server and it worked

```shell
output="Folder/Sub Folder/First Markdown File.md,Folder/Other Subfolder/Another Markdown File.md"
IFS=","
for file in $output
do echo $file
done
unset IFS
```

Which outputted...
```
Folder/Sub Folder/First Markdown File.md was changed
Folder/Other Subfolder/Another Markdown File.md was changed
```

Here is a shell recording of this working on WSL Ubuntu.

[![asciicast](https://asciinema.org/a/MD6Bj8DhN5rKwPnalrGNgBskp.svg)](https://asciinema.org/a/MD6Bj8DhN5rKwPnalrGNgBskp)

I apologize if I missed something basic and opened an issue when unnecessary. That said, I've tried countless variations of the script and looked through pretty much every mention of "space" and "IFS" in this repo and codebase, and haven't been able to resolve the issue. When the same script worked on my Ubuntu server, I decided it best to open this "issue." Thanks sincerely for any help.

**Comment by jackton1** [comment]
@preritdas Can you try using `IFS=$','` instead ?

**Comment by preritdas** [comment]
Didn't work, sadly. Same code but `IFS=$','` instead of `IFS=","`.

Output:

```
Folder Space/Sub Folder/File With Spaces.md
.,.
Folder was changed
Space/Sub was changed
Folder/File was changed
With was changed
Spaces.md was changed
```

**Comment by jackton1** [comment]
Can you also put quotes around the output 

```yml
…
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: "**/**.md"
          separator: ","

      - name: List all changed files
        run: |
          echo ‘${{ steps.changed-files.outputs.all_changed_files }}‘
          IFS=$','
          for file in “${{ steps.changed-files.outputs.all_changed_files }}“
          do echo “$file was changed”
          done
          unset IFS
```
