### ISSUE TITLE
[Feature] Improve docs related to "files"

### ISSUE THREAD

**Issue by SimenHolmestad** [tj-actions/changed-files#629]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

The syntax for "files" is different here than when using "on" and "paths" with github workflows.

With github workflows, you would typically write:
```
on:
  pull_request:
    paths:
      - "path1/**"
      - "path2/**"
```

But with this library, the syntax is:

```
      - name: Check for changed integration test files related to last remote commit
        id: changed-files-related-to-integration-tests
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            path1/**
            path2/**
```

Note that this syntax __does not use quotes__.

I did a direct copy without removing the quotes (only removing the hyphens) and used several hours to debug that the problem was missing quotes. 

The only feedback i got was that the `check-integration-test-files-changed.outputs.any_changed` was set to an empty string, which was not very helpful.

### Describe the solution you'd like?

Maybe add to the docs somewhere that the "files" should not be quoted.

### Describe alternatives you've considered?

It would also be possible to give an error message or warning when this happens, but changing the docs is probably enough.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
