### ISSUE TITLE
[BUG] Add support for pull request close event with merge set to true

### ISSUE THREAD

**Issue by flexwang2** [tj-actions/changed-files#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I want to achieve that - when I create a pull request from a non-master branch and then merge it into master and then print all the files changed.

### To Reproduce

I used below config
```
name: CI

on:
  pull_request:
    types:
      - closed
    paths:
      - "serving/data/**"

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # OR "2" -> To retrieve the preceding commit.
      
      # Example 2
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v29
        with:
          files: |
            serving/cdpush/data/**

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
```

### What OS are you seeing the problem on?

all, macos-latest or macos-10.15

### Expected behavior?

Echo all the files changed

### Relevant log output

```shell
Verifying git version...
  Valid git version found: (2.37.3)
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
  Error: Similar commit hashes detected: previous sha: 63cd1ed2db57eb1d08505186c190d19f11454014 is equivalent to the current sha: 63cd1ed2db57eb1d08505186c190d19f11454014
  Error: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
  Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
