### ISSUE TITLE
[BUG] Can't get all changed files after pushing new commit

### ISSUE THREAD

**Issue by okorepanov** [tj-actions/changed-files#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I want to get all changed files over entire PR after each push event (after adding new commit as well). But i always get changed files from the last commit only. I guess, that i am doing something wrong, so, could you please direct me in a right way

### To Reproduce

name: Echo Pull Request

on:
  push:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    name: Echo Changed Files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Expect to iterate over all changed files in a PR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@okorepanov To achieve that you’ll need to use.

```yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```

You can also checkout the examples for more information on each input
