### ISSUE TITLE
Similar commit hash detected. You seem to be missing fetch-depth:0

### ISSUE THREAD

**Issue by aseem-heg** [tj-actions/changed-files#656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I deploy branch1 to master, then immediately I rebase branch2 on master and deploy branch2 to master. 
Both deployments have GHA functionality where they check for file changes using this GHA `changed-files` functionality.
I have set `fetch-depth: 0`

branch1 always gets error -  Similar commit hash detected. screen shot attached
![Screenshot from 2022-09-28 23-40-40](https://user-images.githubusercontent.com/86262107/192942576-54767183-2128-4dd9-998a-20b518944670.png)

#### Observations:
* This runs fine when just 1 branch is deployed to master at a time. 
* When I rerun failed job manually - it works fine without having to rebase or modify this branch.

### To Reproduce

Create branch1 from master. 
Then create branch2 from master. 
Add some unique changes to both branches.
Write some GHA code job as below:
```
jobs:
  seed_data_changed:
    name: Check if seed data files changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history of all branches

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29
```

Deploy branch1. Then immediately deploy branch 2. Assuming there is no conflict. 
When both branches have `changed-files` running simultaneously on them - we get this error

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

No error should be shown. 
We should see file changes as usual.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
