### ISSUE TITLE
Relative path from a working directory

### ISSUE THREAD

**Issue by okbel** [tj-actions/changed-files#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hello!

`diff_relative` this directive is not returning the relative path from the folder I'm in.

```
    with:
      diff_relative: "true"
      files: |
        web/**
```
returns paths with `web` prefixed. Is this expected?

Apologies if I misunderstood the functionality of `diff_relative`. I've also tried using a boolean, non-string like value. (true) I couldn't find the example to get the relative path within a specific folder.

Thank you!

### To Reproduce

Running this part within a GH action
```
    with:
      diff_relative: "true"
      files: |
        web/**
```

### What OS are you seeing the problem on?

macos-11

### Expected behavior?

To return paths only relative to the working folder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
