### ISSUE TITLE
[BUG] Auto-Merge not working properly on Change-Detection for PRs

### ISSUE THREAD

**Issue by fdc-viktor-luft** [tj-actions/changed-files#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Instead of failing, I get as output for the "all_modified_files" this: 
```
::error::Failed to get changed files between: 0903c9c360a0a00c60e6d03e50129edac363f85d...b16e131872126cf3dd0201883f7a6ad547a94413
```
Expecting a list of space separated file names, this was causing a severe issue skipping several checks in our CI.

### To Reproduce

I'm using the action in a very basic way. Example workflow:

```yaml
name: PR

on:
  pull_request:

jobs:
  prepare-targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
        uses: tj-actions/changed-files@v34.0.0
      - run: echo "${{ steps.files.outputs.all_modified_files }}"
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

In version `v29.0.7` everything still worked fine.

### Anything else?

I'm not sure if the above issue was caused by some Auto-Merge as I had to fast react and rollback the change, but...

I also tried `v32.1.2`. In that version is already another issue. Whenever the Auto-Merge runs the "all_modified_files" contains also all touched files from Auto-Merge instead of only files touched in the PR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
