### ISSUE TITLE
[BUG] diff-sha.sh results in "fatal: ambiguous argument '': unknown revision or path not in the working tree."

### ISSUE THREAD

**Issue by valberg** [tj-actions/changed-files#750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After upgrading to v34 we are getting the following error:

```
Run tj-actions/changed-files@v34
  with:
    separator:
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:
    files_separator:

    files_ignore_separator:

    sha: 52004b3ba66167433ca31d01bd6e6de226a21f10
    path: .
    quotepath: true
    dir_names: false
    json: false
    max_fetch_depth: 300
  env:
    ...
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ...
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: ...
    GITHUB_BASE_REF:
    GITHUB_HEAD_REF:
    GITHUB_WORKSPACE: /home/runner/work/...
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA:
    GITHUB_EVENT_BEFORE:
    GITHUB_EVENT_FORCED:
    INPUT_SHA: 52004b3ba66167433ca31d01bd6e6de226a21f10
    INPUT_BASE_SHA:
    INPUT_SINCE:
    INPUT_UNTIL:
    INPUT_PATH: .
    INPUT_MAX_FETCH_DEPTH: 300
changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.38.1)
  Running on a push event...
  fatal: ambiguous argument '': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: Process completed with exit code 128.
```

### To Reproduce

In our job we have the following:

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.publish_release.outputs.tag }}

      - name: Check if base image files have changed
        id: changed-files
        uses: tj-actions/changed-files@v34
```

The `${{ needs.publish_release.outputs.tag }}` comes from a step from a previous job which is used to create a tag. This looks like so:

```yaml
      - name: Get tag
        id: tag
        run: echo "tag=$(date '+%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push origin --tags
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I was expecting the error not to happen.

### Anything else?

My first guess is that the `base_sha` is not being found and thus is an empty string?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
