### ISSUE TITLE
[BUG] Action failing on PR with "Unable to find merge-base in shallow clone. Please increase 'max_fetch_depth' to at least 340."

### ISSUE THREAD

**Issue by Flydiverny** [tj-actions/changed-files#755]
### Is there an existing issue for this?
* [x]  I have searched the existing issues

#737 seems very related

### Does this issue exist in the latest version?
* [x]  I'm using the latest release

### Describe the bug?

We updated to v34 recently and had PRs working fine but started seeing failures after what we belive is v34.0.5 release.

> Error: Unable to find merge-base in shallow clone. Please increase 'max_fetch_depth' to at least 340.
> Error: Process completed with exit code 1.

Pinning our version to v34.0.2 tag allows the same job to run and detect the related changes (versions between 34.0.2 and 34.0.5 are unconfirmed).
We can see a significant time increase in the run on 34.0.5, or step runs for 9 seconds as opposed to previous ~1 seconds.
The step seems to be pulling a lot more git data.

### What OS are you seeing the problem on?
ubuntu-latest or ubuntu-20.04

### Expected behavior?
We did a significant version bump from v23 to v34 and have been running fine on both of those versions until v34.0.5 rolled out as far as we can tell.

### Relevant log output

```
Download action repository 'tj-actions/changed-files@v34' (SHA:12633630aba2ab48ec2ad8a3344dd736d61a7b89)
```
which appears to be the sha where this fix was introduced. So I'm confused 😄 

Maybe we have missed something I'm not sure 😄 

Log snipper from todays PR on v34 (including v34.0.5)  (not working)

```
Run tj-actions/changed-files@v34
  with:
    separator:  
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: a12aae3dd683269964f99361c3f016a00d179516
    path: .
    quotepath: true
    dir_names: false
    json: false
    max_fetch_depth: 300
  env:
    TITLE: Terraform Report
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TITLE: Terraform Report
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: <redacted>
    GITHUB_BASE_REF: main
    GITHUB_HEAD_REF: cleanup-moved
    GITHUB_WORKSPACE: /home/runner/work/<redacted>/<redacted>
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA: 228384633192b21accbe336022ce16d93b39c3d8
    GITHUB_EVENT_BEFORE: 794bf3864162b849a8dda56d5c230d30320e5d84
    GITHUB_EVENT_FORCED: 
    INPUT_SHA: a12aae3dd683269964f99361c3f016a00d179516
    INPUT_BASE_SHA: 
    INPUT_SINCE: 
    INPUT_UNTIL: 
    INPUT_PATH: .
    INPUT_MAX_FETCH_DEPTH: 300

changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.38.1)
  Running on a pull request event...
  remote: Enumerating objects: 145, done.        
  remote: Counting objects:   0% (1/145)        
  ...     
  remote: Counting objects: 100% (145/145), done.        
  remote: Compressing objects:   1% (1/76)        
  ...      
  remote: Compressing objects: 100% (76/76), done.        
  remote: Total 101 (delta 75), reused 37 (delta 18), pack-reused 0        
  Receiving objects:   0% (1/101)
  ...
  Receiving objects: 100% (101/101), 20.31 KiB | 10.16 MiB/s, done.
  Resolving deltas:   0% (0/75)
  ...
  Resolving deltas: 100% (75/75), completed with 33 local objects.
  From https://github.com/<redacted>
   * [new branch]      main       -> main
   * [new branch]      main       -> origin/main
  remote: Enumerating objects: 809, done.        
  remote: Counting objects:   0% (1/744)        
  ...        
  remote: Counting objects: 100% (744/744), done.        
  remote: Compressing objects:   0% (1/337)        
  ...
  remote: Compressing objects: 100% (337/337), done.        
  Receiving objects:   0% (1/594)
  ...
  Receiving objects:  92% (547/594)
  remote: Total 594 (delta 422), reused 382 (delta 227), pack-reused 0        
  ...
  Receiving objects: 100% (594/594), 116.05 KiB | 4.46 MiB/s, done.
  Resolving deltas:   0% (0/422)
  ...
  Resolving deltas: 100% (422/422), completed with 85 local objects.
  remote: Enumerating objects: 1885, done.        
  remote: Counting objects:   0% (1/1792)        
  ...      
  remote: Counting objects: 100% (1792/1792), done.        
  remote: Compressing objects:   0% (1/784)        
  ...
  Resolving deltas: 100% (2767/2767), completed with 213 local objects.
```

Looking at some of our other jobs it seems like we have jobs with this latest action version that also succeeds.

log snippet from v34.0.2 (working)
```
Run tj-actions/changed-files@v34.0.2
  with:
    separator:  
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: 46638d8545ca2f9eecfdeee4fb9be93bda7662a7
    path: .
    quotepath: true
    dir_names: false
    json: false
    max_fetch_depth: 140
  env:
    TITLE: Terraform Report
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TITLE: Terraform Report
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: <redacted>
    GITHUB_BASE_REF: main
    GITHUB_HEAD_REF: cleanup-moved
    GITHUB_WORKSPACE: /home/runner/work/<redacted>/<redacted>
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA: 228384633192b21accbe336022ce16d93b39c3d8
    GITHUB_EVENT_BEFORE: 2480af8eab084b8b8dfdbc575c5db486af79c13d
    GITHUB_EVENT_FORCED: 
    INPUT_SHA: 46638d8545ca2f9eecfdeee4fb9be93bda7662a7
    INPUT_BASE_SHA: 
    INPUT_SINCE: 
    INPUT_UNTIL: 
    INPUT_PATH: .
    INPUT_MAX_FETCH_DEPTH: 140

changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.38.1)
  Running on a pull request event...
  remote: Enumerating objects: 769, done.        
  remote: Counting objects:   0% (1/769)        
  ...     
  remote: Counting objects: 100% (769/769), done.        
  remote: Compressing objects:   0% (1/385)        
  ...       
  remote: Compressing objects: 100% (385/385), done.        
  Receiving objects:   0% (1/664)
  ...
  remote: Total 664 (delta 464), reused 421 (delta 245), pack-reused 0        
  ...
  Receiving objects: 100% (664/664), 127.67 KiB | 6.08 MiB/s, done.
  Resolving deltas:   0% (0/464)
  ...
  Resolving deltas: 100% (464/464), completed with 80 local objects.
  From https://github.com/<redacted>
   * [new branch]      main       -> main
```

Added the clone logs, ignoring % changes. The new version appears to be pulling _a lot_ more objects.
The new version the action step takes 9 seconds for us before failing and the old version 34.0.2 takes 1s and succeeds.

Our job
```yaml
jobs:
  targets:
    name: get targets
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.changed-targets.outputs.result }}
    steps:
      - uses: actions/checkout@v3

      - name: List available targets
        id: targets
        run: |
          targets=`make targets-json`
          echo "targets=$targets" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.0.2 # fails on v34 see https://github.com/tj-actions/changed-files/issues/737

      - name: Select targets
        uses: actions/github-script@v6
        id: changed-targets
        with:
          script: |
            const files = `${{ steps.changed-files.outputs.all_modified_files }}`.split(' ')
            const targets = ${{ steps.targets.outputs.targets }}

            const deduceTargets = require('./.github/workflows/deduce-targets.js')

            return deduceTargets({ files, targets, glob })
```

_Originally posted by @Flydiverny in https://github.com/tj-actions/changed-files/issues/737#issuecomment-1301919684_
