### ISSUE TITLE
How can I let the workflow to detect the changes only in the certain micro service?

### ISSUE THREAD

**Issue by MemphisMeng** [tj-actions/changed-files#766]
I am having a monorepo-like repo but it's not fully configured so it's a combination of several folders. Each subfolder has its own Dockerfile and my idea is to only let docker build the Dockerfile of the folder where there are new changes. Currently, I am working on a dev branch that already has an open pull request, the changes can be introduced by either git-push or pull request merge once the development is complete and the branch is merged.

It seems like whatever I committed to GitHub, this toolbox always compares it with what's in the target branch. This causes an issue and my expectation is that as long as any difference exists between the current commit and the last commit, it can be discovered.

Workflow yaml file:
```
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      env:
        CLOUD_FORMATION_ROLE: my-role
     steps:
     - name: ECS_TASK_DEFINITIONCheckout
       uses: actions/checkout@v3
    - name: Get SHA of the prior commit
       id: prior-commit-sha
       run: |
         echo "pre=$(git rev-parse $GITHUB_SHA^1)" >> $GITHUB_ENV
    - name: Get changed files
       id: changed-files-specific
       uses: tj-actions/changed-files@v34
       with:
         fetch_depth: 1
         files: |
           my-directory/**
         base_sha: ${{ env.pre }}
```

Error trackrace:
```
Resolving repository path: /home/runner/work/my-repo/my-repo/.
  Retrieving changes between target-branch-SHA (poc-api) → source-branch-SHA (vendor-api)
  grep: : No such file or directory
  /home/runner/work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 66: echo: write error: Broken pipe
  Error: Process completed with exit code 1.
```
In the case above, I wasn't going to compare changes between target branch and source branch yet, instead, the current commit and the previous commit. How can I work around?

**Comment by jackton1** [comment]
Hi @MemphisMeng, in order to give you an accurate answer can you enable debug logging and update the trace to include all information generated by the changed-files action.

**Comment by jackton1** [comment]
At first glance, I’ll also suggest you simplify your workflow file to use 

```yaml
on:
  workflow_dispatch:
  push:
     branches: '**'

jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      env:
        CLOUD_FORMATION_ROLE: my-role
     steps:
     - name: ECS_TASK_DEFINITIONCheckout
       uses: actions/checkout@v3
    - name: Get changed files
       id: changed-files-specific
       uses: tj-actions/changed-files@v34
       with:
         files: |
           my-directory/**
```
