### ISSUE TITLE
[BUG] Similar commit hashes detected: previous sha: abc123 is equivalent to the current sha: abc123 on PR merge

### ISSUE THREAD

**Issue by robgutsopedra** [tj-actions/changed-files#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Using version v34 I didn't have any issues - I created a PR, merged it, and on the merge of the PR I used this action to verify some files, like this: 
```
name: "Create issue"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-issue:
    name: Initial comment on PR
    if: github.event.pull_request.merged == true
    runs-on: preemptible-runners
    permissions:
      contents: "read"
      id-token: "write"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    ##Comprobar que solo haya UN fichero .md añadido
    - name: List all added files and some info
      id: file_content
      run: |
        aux=0
        for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "$file was added"
          if [[ $file =~ \.md$ ]]; then
            rfc_file=$file
            echo "rfc_file=$file" >> $GITHUB_ENV
            aux=$(($aux+1))
          fi
        done
```

As of this morning, it started to fail due to: 

![image](https://user-images.githubusercontent.com/101654801/200304279-3083b1df-1aaf-4f1c-8331-103e78cb416b.png)

I tried several options as per the docs, issues, comments... But nothing worked.

To fix it, I downgraded the version to 34.0.0 and everything went back to normal. 
I'm assuming with the release that happened some hours ago, something stopped working/I'm missing something/I was doing something luckily right that has been fixed. 

I'd love to know more about this issue!

I'm using self-hosted runners - Ubuntu 20

### To Reproduce

1. IMPORTANT - it only fails when merging the PR, not with pushes or when opening a PR
2. Use version v34 or v34.3.0 in the workflow
3. Open a new PR (in my case I was adding a new file)
4. Merge the PR (I tried with and without squased, same error)

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I'd expect the minor update to keep working as before

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
