### ISSUE TITLE
Detected dubious ownership in repository error when running the action

### ISSUE THREAD

**Issue by AbianG** [tj-actions/changed-files#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

In an already existing CI pipeline, using the action for testing purposes exactly as described in the readme:
```
      - name: Test to list changed files
        id: changed-source-files
        uses: tj-actions/changed-files@v34.3.0

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-source-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```
After running I get the error: 
```
changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.36.3)
  Running on a pull request event...
  Fetching remote refs...
  fatal: detected dubious ownership in repository at '/__w/cloudops-docs/cloudops-docs'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/cloudops-docs/cloudops-docs
  Error: Process completed with exit code 128.
```

### To Reproduce

1. Existing github actions file that runs on `ubuntu-latest`
2. Copy the code based on the example

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Action should list the changed files

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbianG** [comment]
Using `actions/checkout@v3` with either `fetch-depth: 0` or `fetch-depth: 2` changes nothing, still getting the error.

**Comment by jackton1** [comment]
@AbianG The `safe.directory` config is done by the checkout action which you are required to use with this action. Noting that this doesn't have anything to do with the fetch-depth setting.

See: https://github.com/actions/checkout#usage

**Comment by romintomasetti** [comment]
Hey there!
I also see this happening with
```yaml
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  set-safe-directory: true
            - name: Get changed files in the docs folder
              id: changed-files-specific
              uses: tj-actions/changed-files@v34
              with:
                  files: |
                      <...>
```
I checked that the `checkout` action indeed performs the `safe.directory`, and I does...
(I'm running in a custom Docker image on a self-hosted runner)
