### ISSUE TITLE
[BUG] Action compares only two latest commits on push

### ISSUE THREAD

**Issue by Ferror** [tj-actions/changed-files#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The way I understand READMe and this action is that I am able to get all changed files in PR. But the simple example below does only compare the two latest commits when pushed. Also the first example does not provide any additional clue https://github.com/tj-actions/changed-files#examples

What am I doing wrong? Shouldn't it work? Is it a bug?

### To Reproduce

The Pipeline

```yaml
name: CI

on:
  push: ~

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v34
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The pipeline does read changes from the first commit of branch and the latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jallen-frb** [comment]
@jackton1 How would this work for push events where you want to compare your commit to the initial branch commit?

For example: I checkout a branch based on MAIN (call it A). I then make a bunch of commits B,C,D,E. In commit C, I change a file. I want a stage to execute based on that changed file in commit C. This means that if I pushed D the CI would run that stage. The same would trigger in commit E if it was pushed.

**Comment by jackton1** [comment]
That's the default for push events @jallen-frb since there's no concept of a base branch for comparing changes with the last pushed remote commit and the current HEAD you can set `since_last_remote_commit: true`

**Comment by jallen-frb** [comment]
@jackton1 I do not get this behavior. I have to change the file on every push.

**Comment by Ferror** [comment]
> @jallen-frb You don’t have to use the setting if you don’t want to simply using
> 
> ```yaml
> name: CI
> 
> on:
>   push:
> 
> jobs:
>   ci:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout Code
>         uses: actions/checkout@v3
>         with:
>           fetch-depth: 0
> 
>       - name: Get changed files
>         id: changed_files
>         uses: tj-actions/changed-files@v34
> ```
> 
> should be enough

That wont work. The `pull_request `  is required

**Comment by jackton1** [comment]
See: https://github.com/tj-actions/demo3/blob/main/.github/workflows/ci.yml

**Comment by varenyatessell** [comment]
So for fetching file change in a PR with action trigger on `push` event, when there are multiple commits present. I need to use `since_last_remote_commit: true` or is it updated now in current release.

```
- name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          since_last_remote_commit: true
          files: |
```
