### ISSUE TITLE
[BUG] Please verify that the previous sha is valid, and increase the fetch_depth to a number higher than 40.

### ISSUE THREAD

**Issue by genieai-vikas** [tj-actions/changed-files#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hello, I was using `v17.3` and it was working now. Now I started using version `34.3.3` but now my pipeline is failing. 
I am getting this error:

```
  Error: Unable to locate the previous sha: 8f8bbe6058594a7b820988956de59faba3f1b1bc
  Error: Please verify that the previous sha is valid, and increase the fetch_depth to a number higher than 40.
  Error: Process completed with exit code 1.
```

Basically, I have created a PR(develop <- feature/xxx) now every time I push github CI triggered the build because of synchronization. I compare (current - 1) to current commit of my feature branch and build only certain parts of code as per the changes

### To Reproduce

```
      - name: check if MS changed
        uses: tj-actions/changed-files@v34.3.3
        id: changed-files-specific-1
        with:
          base_sha: ${{needs.previous_commit.outputs.PREVIOUS_GITHUB_SHA}}
          files: |
            src/microservices/A/**
            src/microservices/B/**
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

It should compare the previous commit with the current commit and if any files are changed then it should return true or false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@genieai-vikas can you include the configuration for the checkout action?

**Comment by genieai-vikas** [comment]
@jackton1 Thanks for the help. here is the checkout action

```
    steps:
      - uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 2
```

**Comment by jackton1** [comment]
Okay, I'll recommend using 

```yaml
      - name: check if MS changed
        uses: tj-actions/changed-files@v34.3.3
        id: changed-files-specific-1
        with:
          base_sha: ${{needs.previous_commit.outputs.PREVIOUS_GITHUB_SHA}}
          since_last_remote_commit: true
          files: |
            src/microservices/A/**
            src/microservices/B/**
```

**Comment by genieai-vikas** [comment]
@jackton1 tried but still getting the same error

![image](https://user-images.githubusercontent.com/86361824/200653219-e605623e-ea3b-46d7-9f84-d3718886ba52.png)

**Comment by jackton1** [comment]
@genieai-vikas Can you include the full log output with debugging enabled this can be done by rerunning the workflow

**Comment by jackton1** [comment]
@genieai-vikas Closing this for now as I’ll need more information to reproduce the bug. Please include more information on your workflow file and provide the related log output in order to reopen the issue. Thanks

**Comment by rainabba** [comment]
@jackton1 I your suggest above, can you explain the referenced "previous_commit" job? `needs.previous_commit.outputs.PREVIOUS_GITHUB_SHA`

I'm getting the same depth error in some runs, but not others.

**Comment by jackton1** [comment]
@rainabba I'm not entirely sure how the workflow is implemented. i.e where the `needs.previous_commit.outputs.PREVIOUS_GITHUB_SHA` so I can't provide any direction in that regard. I'll recommend using the provided inputs.

> Note: This can be achieved by setting the `since_last_remote_commit` to `true`

E.g

```yaml
      - name: check if MS changed
        uses: tj-actions/changed-files@v34
        id: changed-files-specific-1
        with:
          since_last_remote_commit: true
          files: |
            src/microservices/A/**
            src/microservices/B/**
```
