### ISSUE TITLE
[BUG] Specfic File Bug in v33 / v34 - grep: : No such file or directory

### ISSUE THREAD

**Issue by TurtIeSocks** [tj-actions/changed-files#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

With the workflow below, I'm able to successfully run it on V32 and below of this action, but V33 and V34 are failing when I have a single file in the files to check list.

### To Reproduce

```yml
jobs:
  sync:
    name: Check for config changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            server/src/configs/default.json
      - name: Setup Node.js environment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Run script
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          yarn config-check
      - name: Commit and push changes
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Sync character count for config ref file
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I'm expecting it to not fail and report if the single file has changed.

### Relevant log output

```shell
Run tj-actions/changed-files@v34
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
Run tj-actions/glob@v16
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/RepoName/RepoName
/usr/bin/git diff --diff-filter=D --name-only 847b2faabaed1776a0b45c98861a1d3b0490709c..8d3a2959f97f5fbfef7d523c4f40531d60eedf41
Run bash $GITHUB_ACTION_PATH/get-changed-paths.sh
changed-files
  Resolving repository path: /home/runner/work/RepoName/RepoName/.
  Retrieving changes between 847b2faabaed1776a0b45c98861a1d3b0490709c (branch-name) → 8d3a2959f97f5fbfef7d523c4f40531d60eedf41 (branch-name)
  grep: : No such file or directory
  grep: : No such file or directory
  grep: : No such file or directory
  grep: : No such file or directory
  /home/runner/work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 66: echo: write error: Broken pipe
  Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@TurtIeSocks can you provide the full log output using the download button as this output is missing a number of valuable information.

**Comment by staticaland** [comment]
Same here.

**Comment by staticaland** [comment]
```yml
          files: |
            dev/**
```

Works.

```yml
          files: |
            dev/**.tf
```

Does not work.

**Comment by jackton1** [comment]
@staticaland See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

I believe `dev/*.tf` is what you want or an alternative to match subdirectories `dev/**/*.tf`

**Comment by dlopeza** [comment]
Same problem here with files: tests/**.js

As a workaround I used version v32

**Comment by jackton1** [comment]
Have you tried using `test/**/*.js‘

**Comment by staticaland** [comment]
Reading [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths), I don't really see how `dev/**.tf` is wrong. I believe it was working fine for `on.push.paths`.

> The `**` wildcard matches any character including slash (/). This is the default behavior when you don't use a path filter.

> `**.js` Matches all .js files in the repository.

**Comment by jackton1** [comment]
After reaching out to the support team I discovered that there are differences in Implementation of the native workflow globstar matching and the https://github.com/isaacs/minimatch library used by this action an example of such differences can be seen below

- https://github.com/tj-actions/glob/actions/runs/3500893688/jobs/5864022728#step:6:3
- https://github.com/tj-actions/glob/actions/runs/3500893688/jobs/5864022728#step:8:3

**Comment by roflcoopter** [comment]
I am having the same issue when specifying two absolute paths.
Problem appeared when upgrading from a pretty old version of changed-files
How is this not working?
```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            requirements.txt
            docker/Dockerfile.wheels
``` 

This does not work either
```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/requirements.txt
            **/docker/Dockerfile.wheels
```

**Comment by kenji-miyake** [comment]
@jackton1 I encountered the same problem.
https://github.com/tier4/autoware_launch/actions/runs/3672177618/jobs/6208132030#step:6:116

```
changed-files
  Resolving repository path: /__w/autoware_launch/autoware_launch/.
  Retrieving changes between c896f3f1aa80f822756ff0838a9f967522433441 (awf-latest) → e6d48f92311d87d7a7ff973342bc6d3b3f4afd09 (use-xml-for-system-monitor)
  grep: : No such file or directory
```

I guess this occurs when `$INPUT_FILES_PATTERN_FILE` or something else is empty, due to the target files don't exist as said in https://github.com/tj-actions/changed-files/issues/795#issuecomment-1322298657.
https://github.com/tj-actions/changed-files/blob/ba5abef332cb868a398ef4b51675bb75cc192995/get-changed-paths.sh#L189

```console
$ grep -x -E -f ""
grep: : No such file or directory
```

How about adding an empty check in `get-changed-paths.sh` or `action.yml`?
For example, add `if: ${{ steps.glob.outputs.paths-output-file != '' }}` to the job below.
https://github.com/tj-actions/changed-files/blob/ba5abef332cb868a398ef4b51675bb75cc192995/action.yml#L208-L209

Thank you.

**Comment by roflcoopter** [comment]
The files that are in my pattern do exist so it seems to be something else going on as well

**Comment by jackton1** [comment]
@roflcoopter without the logs there’s not much to find a resolution in this case.

**Comment by kenji-miyake** [comment]
@jackton1 Thank you for your quick reply!

I guess using a custom container is okay. For example, in the workflow run below, `changed-files` has succeeded.
https://github.com/autowarefoundation/autoware.universe/actions/runs/3681614685/jobs/6228836994#step:6:114

Though the image name is different, the workflow structure is almost the same.

```yaml
  clang-tidy-differential:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:humble-latest-cuda
```

What do you think?

> I can add a check to verify the existence of the file and mark the step as failed when missing.

Oh, will you mark it as failed? I personally think it's okay to mark it as success when there is no target file found.
