### ISSUE TITLE
Unable to locate a common ancestor between production_migration and HEAD

### ISSUE THREAD

**Issue by vinothgitkumar** [tj-actions/changed-files#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

My github workflow triggered using PR creation event. Once the workflow triggered the action throws below error and workflow failed.

  Error: Unable to locate a common ancestor between production_migration and HEAD
  Error: Process completed with exit code 1.

I am using checkout action v3 with depth 0 and tj-actions/changed-files@v34

### To Reproduce

I Encouter this issue now only and not able to reproduce but it may occur sometime later.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

tj-actions/changed-files@v34 action needs to complete the execution and provide the putout as files in PR.

### Relevant log output

```shell
changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.38.1)
  Running on a pull request event...
  Fetching remote refs...
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
  branch 'production_migration' set up to track 'origin/production_migration'.
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/org1/dataeng-enterprise
   * branch            production_migration -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  Error: Unable to locate a common ancestor between production_migration and HEAD
  Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jarojasm95** [comment]
I'm also running into this issue, here's a snippet of the workflow:
```yaml
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
    ref: ${{ github.event.pull_request.head.sha }}
- id: files
  uses: tj-actions/changed-files@v34.3.0
  with:
    separator: ","
    base_sha: ${{ github.event.pull_request.base.sha }}
    sha: ${{ github.event.pull_request.head.sha }}
```

**Comment by jackton1** [comment]
Hi, @jarojasm95 have you tried upgrading? I believe the change was introduced in [v34.4.0](https://github.com/tj-actions/changed-files/releases/v34.4.0)

**Comment by stof** [comment]
I get a similar issue using v34 (which is v34.4.0 right now). `tj-actions/changed-files` runs for ~15min (apparently fetching lots of git objects) and then fails with `Unable to locate a common ancestor between master and HEAD`

**Comment by tsigouris007** [comment]
> I get a similar issue using v34 (which is v34.4.0 right now). `tj-actions/changed-files` runs for ~15min (apparently fetching lots of git objects) and then fails with `Unable to locate a common ancestor between master and HEAD`

Hi @stof I am facing the same issue and opened a similar case.
It seems to be working if you use the `actions/checkout@v3` with `fetch-depth: 0`.
Can you try this too?

**Comment by vinothgitkumar** [comment]
Hi 
I am using actions/checkout@v3 with fetch depth:0. 

What change do I need to do in the action "tj-actions/changed-files" to avoid this error?

**Comment by ViacheslavKudinov** [comment]
Hi,
eh, same issue with 34.4.0.
We use it as part of reusable workflow. This part looks like:
```
    steps:
      - name: "Checkout for Push event (full history)"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed dirs
        id: get_changes
        uses: tj-actions/changed-files@94e6fba8d802f0fa80db51937e8752e9c165ee26 # tag v34.4.0
        with:
          dir_names: ${{ inputs.dir_names }}
          files_ignore: ${{ inputs.excluded_folders }}
          files: ${{ inputs.included_folders }}
```
Didn't face the issue with 34.1.1.
