### ISSUE TITLE
[BUG] Infinite loop on v34.4.0

### ISSUE THREAD

**Issue by tsigouris007** [tj-actions/changed-files#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The step gets stuck in an infinite loop while checking out.
I am using it to get changed files to scan with Semgrep on a Pull Request.
Changing my step to version 34.3.4 does not raise the same issue.
The loop gets stuck as seen in the attached image:
 
![ksnip_20221115-113140](https://user-images.githubusercontent.com/10864434/201883338-e9ff3439-ca75-4a7a-996d-6cc03aa4e1a7.png)

### To Reproduce

```yaml
name: Semgrep (JS) - JS, Python, Go Security Scan
on:
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '.github/workflows/semgrep-js.yml'
  workflow_dispatch:
jobs:
  semgrep:
    # Skip job if draft
    if: github.event.pull_request.draft == false
    name: Semgrep run
    runs-on: ubuntu-latest
      # Check out current branch if PR
      - name: Check out (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
      # Skip changed files and filtering on PR
      - name: Get changed files (PR)
        if: ${{ github.event_name == 'pull_request' }}
        id: changed-files
        uses: tj-actions/changed-files@v34.3.4 # Test
        with:
          files: |
            **.js
            **/**.js
            **.jsx
            **/**.jsx
      # Show changed files on PR and push them to environment as CHANGED_FILES
      - name: Show changed files (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ALL_CHANGED_FILES=$(echo ${{ steps.changed-files.outputs.all_changed_files }})
          echo "Got changed files: $ALL_CHANGED_FILES"
...
```
Skipped the rest as the execution does not continue any further anyways.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

To work properly.

### Relevant log output

```shell
See attached image.
Stuck on:

From repo
* branch master -> FETCH_HEAD
* branch HEAD   -> FETCH_HEAD
```
```


### Anything else?

Nope 😄 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tsigouris007** [comment]
If I use with `fetch-depth: 0` it does seem to work.
```
      - name: Check out (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files (PR)
        if: ${{ github.event_name == 'pull_request' }}
        id: changed-files
        uses: tj-actions/changed-files@v34.4.0
        with:
          files: |
            **.js
            **/**.js
            **.jsx
            **/**.jsx
```
This does increase run times but if we cannot move further I guess I can leave it like this.

**Comment by jackton1** [comment]
@tsigouris007 I'll like to point out that the patterns you highlighted aren't valid. You can take a look at the [patterns to match file paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths) for more information.

**Comment by tsigouris007** [comment]
Hi @jackton1 apart from the patterns the infinite loop did not stop.
But also, why are they not valid?
I have been using them for quite some time on a production environment and have been used for more than 15k runs without a problem and producing right results. What am I not doing right?

**Comment by tsigouris007** [comment]
Unfortunately this is not solved.

![ksnip_20221116-120620](https://user-images.githubusercontent.com/10864434/202151516-4df9f150-6448-432d-b731-222156e69eab.png)

Using 34.4.0 version runs for more than 6 minutes without any proper result.
Reverting to 34.3.4 it works.

The step used for this is:
```yaml
      - name: Get changed files (PR)
        id: changed-files
        uses: tj-actions/changed-files@v34.4.0
        with:
          files: |
            **.js
            **.jsx
```
