### ISSUE TITLE
[BUG] Looking for __init__.py is failing

### ISSUE THREAD

**Issue by giladlevy7** [tj-actions/changed-files#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I'm trying to use this GH workflow to verify whether a specific __init__.py file was modified or not.
I've tried to use regex, specific paths, and other options as well but it keeps failing with the following error:
![image](https://user-images.githubusercontent.com/12347667/207981817-4c45a953-a585-4bdc-8b1b-9e8afa6b51ca.png)

Step content:
`      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.1
        with:
          files: |
            commons/__init__.py`

### To Reproduce

Add the following step:
```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.1
        with:
          files: |
            commons/__init__.py
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

To succeed

### Relevant log output

```shell
grep: : No such file or directory
  grep: : No such file or directory
  grep: : No such file or directory
  grep: : No such file or directory
  /home/runner/work/_actions/tj-actions/changed-files/v34.6.1/get-changed-paths.sh: line 91: echo: write error: Broken pipe
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@giladlevy7 Does the file exists in the repo ?

**Comment by giladlevy7** [comment]
@jackton1 yes, it exist (but it should work even if it doesn't, right?)

**Comment by jackton1** [comment]
@giladlevy7 Can you also include your configuration of the https://github.com/actions/checkout?

**Comment by giladlevy7** [comment]
@jackton1 of course, thanks for helping.
```
     - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
```

```
      matrix:
        python-version: [ 3.10.0 ]
```

```
    runs-on: ubuntu-20.04
```

**Comment by jackton1** [comment]
@giladlevy7 Can you upgrade actions/setup-python@v2 to v3

**Comment by jackton1** [comment]
@giladlevy7 Closing this issue, for now, since a new version has been released. Let me know if the issue persists and I can reopen the issue. I also recommend that you enable debugging and post the entire log output i.e including the checkout and the changed files actions steps

**Comment by giladlevy7** [comment]
@jackton1 
I would still appreciate your assistance 
this is what I'm using now:
```
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.base.ref == 'main' }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [ 3.10.0 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        # First, we verify that init file was changed
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.1
        with:
          files: |
            __init__.py
```
and unfortunately it still fails:

```
  Resolving repository path: /home/runner/work/rivery_commons/rivery_commons/.
  Retrieving changes between 3b5505aff40fd730ffaa9df6f346de0c591ff9ba (main) → 6db88282523513365b8f565651a6ae2e7253c41f (fix/gilad/linter-issue)
  grep: : No such file or directory
  grep: : No such file or directory
  grep: : No such file or directory
  grep: : No such file or directory
  /home/runner/work/_actions/tj-actions/changed-files/v34.6.1/get-changed-paths.sh: line 91: echo: write error: Broken pipe
```

is it working for you with finding __init__.py file?

i don't think it's the code checkout since if I'm looking for another file - it works, or without any filter - also works
failing only on __init__
