### ISSUE TITLE
How to see the changed files after the PR is merged ?

### ISSUE THREAD

**Issue by DimasAdinugroho** [tj-actions/changed-files#874]
I have a github action that running after the PR is closed and merged. But how do I see the changed files between the target branch (devel) before merged and the last commit of the source branch ? This is my current yaml file:

```
name: test

on:
  pull_request:
    types: [ closed ]
    branches:
      - devel

jobs:
  check_pr:
    runs-on: ubuntu-latest    
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-models
        uses: tj-actions/changed-files@v34
        with:
          files: |
              my-directory/**
```

**Comment by kahochoi** [comment]
I'm also meeting the same problem. the error message is as below.
![image](https://user-images.githubusercontent.com/63641734/208058149-be4366b3-c70a-4ef1-a25a-f47f795492cd.png)

When a PR is closed and the feature branch is merged to the main branch, the workflow listing the change file fails.
the yaml is as below.

```
name: deployment

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Get changed py files in the docs folder
        id: changed-py-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            python_files/**/*.py
          separator: ";"

```

**Comment by jackton1** [comment]
@DimasAdinugroho I believe the setup you have is correct this would show all changes between the target branch and the PR branch you can optionally use 

```
on:
  push:
    branches:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-models
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
              my-directory/**
```

Main last remote commit A..B (Latest commit which includes changes from the Pull Request)


See: https://github.com/tj-actions/changed-files/blob/main/.github/workflows/test.yml and https://github.com/tj-actions/changed-files#examples for more examples
