### ISSUE TITLE
pipeline failed in tj-action

### ISSUE THREAD

**Issue by prabha-912** [tj-actions/changed-files#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

![image](https://user-images.githubusercontent.com/45986663/209080717-a7111915-a608-42df-91e4-d246c1a9ebc2.png)

### Describe the bug?

![image](https://user-images.githubusercontent.com/45986663/209077196-ed8d7068-ae5d-4e1e-9d5d-012768279b7e.png)

While running the pipeline with the below code, it is getting error.

`
![image](https://user-images.githubusercontent.com/45986663/209077317-1a667a5b-f125-4b40-9097-9871488572a1.png)
`

### To Reproduce

-

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Pipeline should be passed without failure

### Relevant log output

```shell
-
```

### Anything else?

https://github.com/orgs/community/discussions/42354

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@prabha-912 I’ll suggest you add the following 

```yml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
```
