### ISSUE TITLE
[BUG] write_output_files: true -> double escapes json content in generated files

### ISSUE THREAD

**Issue by neerup** [tj-actions/changed-files#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Finally got around to change change my workflow from:
```yaml
      - name: Create change set
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: true

      - name: Build
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" >> "$HOME/all_changed_files.json"
```
Which generates a file with this content (the escaped special character is a danish Ø)
```json
["QSRVSRC/ES0ABCCA","QSRVSRC/ES0ABCRE.BND","\"QSRVSRC/ES0ABCR\\303\\230.BND\""]
```

To 
```yaml
      - name: Create change set
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: true
          write_output_files: true

```
But this generates af file with this content
```json
[\"QSRVSRC/ES0ABCCA\",\"QSRVSRC/ES0ABCRE.BND\",\"\\\"QSRVSRC/ES0ABCR\\\\303\\\\230.BND\\\"\"]
```
 

### To Reproduce

1. Run the 2 workflows and see the resulting files.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Expected the 2 workflows generate the same content to the file

### Relevant log output

```shell
##[debug]Loading env
Run tj-actions/json2file@v1
  with:
    outputs: {
    "added_files": "[\\\"QSRVSRC/ES0ABCCA\\\"]",
    "copied_files": "[]",
    "deleted_files": "[\\\"QSRVSRC/ES0ABCRB.BND\\\"]",
    "modified_files": "[\\\"QSRVSRC/ES0ABCRE.BND\\\"]",
    "renamed_files": "[\\\"\\\\\\\"QSRVSRC/ES0ABCR\\\\\\\\303\\\\\\\\230.BND\\\\\\\"\\\"]",
    "type_changed_files": "[]",
    "unmerged_files": "[]",
    "unknown_files": "[]",
    "all_changed_and_modified_files": "[\\\"QSRVSRC/ES0ABCCA\\\",\\\"QSRVSRC/ES0ABCRB.BND\\\",\\\"QSRVSRC/ES0ABCRE.BND\\\",\\\"\\\\\\\"QSRVSRC/ES0ABCR\\\\\\\\303\\\\\\\\230.BND\\\\\\\"\\\"]",
    "all_changed_files": "[\\\"QSRVSRC/ES0ABCCA\\\",\\\"QSRVSRC/ES0ABCRE.BND\\\",\\\"\\\\\\\"QSRVSRC/ES0ABCR\\\\\\\\303\\\\\\\\230.BND\\\\\\\"\\\"]",
    "all_modified_files": "[\\\"QSRVSRC/ES0ABCCA\\\",\\\"QSRVSRC/ES0ABCRB.BND\\\",\\\"QSRVSRC/ES0ABCRE.BND\\\",\\\"\\\\\\\"QSRVSRC/ES0ABCR\\\\\\\\303\\\\\\\\230.BND\\\\\\\"\\\"]",
    "outputs_extension": "json"
  }
    directory: .github/outputs
    skip_missing_keys: true
    keys: added_files
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
