### ISSUE TITLE
[Feature] Specify base branch, not just base-sha

### ISSUE THREAD

**Issue by djfinnoy** [tj-actions/changed-files#941]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I want the `base-sha` option to poin to the latest commit in the base branch:

```
      - id: changed-files
        uses: tj-actions/changed-files@3b6c057cd82d1dafab565df2ba9fa489574a03b8  # v34.6.1
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
```

However, there is a problem with Github Actions where `github.event.pull_request.base.sha` does not necessarily refer to the latest commit of the base branch: https://github.com/community/community/discussions/39880

### Describe the solution you'd like?

It would be super great if this tool supported a `base-branch` option, instead of relying on the user to figure out the correct sha for the base branch.

### Describe alternatives you've considered?

Wait for GitHub to fix `github.event.pull_request.base.sha` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
