### ISSUE TITLE
Comparing differences between tags/releases

### ISSUE THREAD

**Issue by dhpalan** [tj-actions/changed-files#949]
I have a GitHub workflow that runs when creating a GitHub release/tag in a repository.

```yaml
on:
  # Triggers the workflow for release tags
  push:
    tags:
      - v[1-9].[0-9].[0-9]+
      # Sample: v1.0.0 or v9.9.10
```

Will I be able get the changed files list by comparing two tags?

An example from this repo:
https://github.com/tj-actions/changed-files/compare/v35.4.0...v35.4.1
How can i fetch the modified file list here? There are 6 modified files, and 10 commits.
