### ISSUE TITLE
[BUG] Action is evaluating branch instead of sha

### ISSUE THREAD

**Issue by djfinnoy** [tj-actions/changed-files#957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After upgrading from `v35.4.1` to `v35.4.3`, my workflows are failing with the following error:

```
  fatal: couldn't find remote ref <BRANCH NAME>
  Error: Process completed with exit code 128.
```

The reason git can't find this ref, is because my repository is configured to delete HEAD branches after merging.
The `changed-files` action is configured to use the sha of the HEAD branch, rather than the ref.
This worked fine until upgrading. It would appear that something has changed which makes the action look for the ref instead of using the sha. 

### To Reproduce

My use case is described in #944. To reproduce, use this workflow and merge a pull request in a repository that deletes HEAD branches:

```
name: example

on:
  pull_request: {}

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: changed-files
        uses: tj-actions/changed-files@v35.4.3
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          json: true

```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The workflow code referenced above should work like, like it did in `v35.4.1`, where it is able to fetch the HEAD sha, despite the branch having been deleted.

### Relevant log output

```shell
# The failing log outputs look like this

  Verifying git version...
  Valid git version found: (2.39.1)
  Running on a pull request event...
  Fetching remote refs...
  fatal: couldn't find remote ref <BRANCH NAME>
  Error: Process completed with exit code 128.


# The log outputs from a successful run after rolling back to `v35.4.1` looks like this:

  Verifying git version...
  Valid git version found: (2.39.0)
  Running on a pull request event...
  Fetching remote refs...
  From https://github.com/<ORG>/<REPO>
   * [new ref]         refs/pull/1808/head -> <BRANCH NAME>
```

### Anything else?

Thank you for a very useful GitHub action.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
