### ISSUE TITLE
[BUG] Unable to ignore the top-level/root directory when dir_names="true"

### ISSUE THREAD

**Issue by 0x0I** [tj-actions/changed-files#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When attempting to detect unique directories which have changed from a commit, the Github Action results in the following error if the top-level directory (represented by `.`) is specified as a directory to ignore using the `ignore_files` input property:

```
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/containers/containers
/usr/bin/git diff --diff-filter=D --name-only ccecf3fe3c741e028264707bd98319b7065bd91f..09a3feaed99eae19565cbc92d72fdc363ddb9ebd
Error: No paths found using the specified patterns
```

### To Reproduce

1. Set the following step in a workflow:
```yml
      - name: Identify changed application subdirectories
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          files_ignore: .github,.
          files_ignore_separator: ","
```
2. Modify a file at the top-level/root of the repository and trigger the following workflow.
3. Observe that the workflow fails at the above step.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The expected behavior is that the `.` current directory entry is ignored and not returned in the action's output when set to ignore.

### Relevant log output

```shell
Run tj-actions/changed-files@v35
  with:
    dir_names: true
    dir_names_max_depth: 1
    files_ignore: .github,.
    files_ignore_separator: ,
    separator:  
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:  
    files_separator: 
  
    path: .
    quotepath: true
    json: false
    json_raw_format: false
    fetch_depth: 50
    since_last_remote_commit: false
    write_output_files: false
    output_dir: .github/outputs
    match_directories: true
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: 0x0I/containers
    GITHUB_REF: refs/pull/7/merge
    GITHUB_SHA: 09a3feaed99eae19565cbc92d72fdc363ddb9ebd
    GITHUB_WORKSPACE: /home/runner/work/containers/containers
    GITHUB_EVENT_HEAD_REPO_FORK: false
    GITHUB_EVENT_PULL_REQUEST_NUMBER: 7
    GITHUB_EVENT_PULL_REQUEST_BASE_REF: main
    GITHUB_EVENT_PULL_REQUEST_HEAD_REF: test_ignore_toplevel_dir
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA: ccecf3fe3c741e028264707bd98319b7065bd91f
    GITHUB_EVENT_PULL_REQUEST_HEAD_SHA: 287b5789a3d0f0e6beb475f8c38b8671ab4563ba
    GITHUB_EVENT_PULL_REQUEST_COMMITS: 1
    GITHUB_EVENT_BEFORE: 
    GITHUB_EVENT_FORCED: 
    GITHUB_REFNAME: 7/merge
    INPUT_SHA: 
    INPUT_BASE_SHA: 
    INPUT_SINCE: 
    INPUT_UNTIL: 
    INPUT_PATH: .
    INPUT_FETCH_DEPTH: 50
    INPUT_SINCE_LAST_REMOTE_COMMIT: false
changed-files-diff-sha
Run tj-actions/glob@v16
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/containers/containers
/usr/bin/git diff --diff-filter=D --name-only ccecf3fe3c741e028264707bd98319b7065bd91f..09a3feaed99eae19565cbc92d72fdc363ddb9ebd
Error: No paths found using the specified patterns
```

### Anything else?

The current use-case is if there is a monorepo of sorts with which I only want my CI workflows to execute against subdirs which share a similar structure and represent various related apps/services. For example, each subdir has a Dockerfile (corresponding to the app its meant to encompass) whereas the top-level root dir won't. If i modify a file at the top level (e.g. the repo's main README), then my logic will fail without ignoring the root since the root won't and isn't really expected to be tested against or contain this expected structure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@0x0I I believe this didn't work because the `files_ignore` input requires each pattern to be separated by a newline character

Example
```yml
      - name: Identify changed application subdirectories
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          files_ignore: |
              .github
              .
          files_ignore_separator: ","
```

But this setup wouldn't solve the problem you highlighted since the glob patterns are parsed by a separate action which returns absolute paths and the dir name output of `.` is generated after matching the patterns to the changed files.

I've added a PR that would work for you use case i.e You'll now have a new input that should exclude `.` entirely from the dir name output.

**Comment by 0x0I** [comment]
> @0x0I I believe this didn't work because the `files_ignore` input requires each pattern to be separated by a newline character
> 
> Example
> 
> ```yaml
>       - name: Identify changed application subdirectories
>         id: changed-dirs
>         uses: tj-actions/changed-files@v35
>         with:
>           dir_names: "true"
>           dir_names_max_depth: "1"
>           files_ignore: |
>               .github
>               .
>           files_ignore_separator: ","
> ```
> 
> But this setup wouldn't solve the problem you highlighted since the glob patterns are parsed by a separate action which returns absolute paths and the dir name output of `.` is generated after matching the patterns to the changed files.
> 
> I've added a PR that would work for you use case i.e You'll now have a new input that should exclude `.` entirely from the dir name output.

Hey @jackton1, ah I thought that the `files_ignore_separator` would change the default of newline to the character that is specified. In the case mentioned, this would be `,`.

Anyway, that's awesome - thanks! Will check it out.

**Comment by jackton1** [comment]
Oh you are correct I must have missed that in your earlier post `files_ignore_separator` would solve that.

**Comment by jackton1** [comment]
@0x0I This should now be available in the latest release.

Example
```yml
      - name: Identify changed application subdirectories
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          files_ignore: ".github"
          dir_names_exclude_root: "true"
```
