### ISSUE TITLE
Is it possible to get unstaged / modified files?

### ISSUE THREAD

**Issue by shinebayar-g** [tj-actions/changed-files#983]
I've an use case like this. `cdk8s` cli generates yaml files based on source code change. I'm running `cdk8s` command on each commit to master branch to ensure there's no configuration drift. Is it possible to use this action to know which files are modified?
Based on the commit I may or may not get any changed files. If this action is able to detect which files are changed, that'd be helpful. Right now it looks like it's not detecting changed files during the workflow. My workflow looks like this:

```yaml
- uses: actions/checkout@v3
  with:
    fetch-depth: 2

- run: cdk8s synth

- name: Is there a change?
  id: detect-manifest-change
  uses: tj-actions/changed-files@v35
  with:
    files: manifests/**
```

Currently even though `cdk8s synth` is modifying files in `manifests/` folder, action isn't seeing the change.
