### ISSUE TITLE
[Feature] Watch multiple paths

### ISSUE THREAD

**Issue by enahsor** [tj-actions/changed-files#993]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I want to be able to detect changes for a range of paths.

### Describe the solution you'd like?

I want to be able to pass a list of paths to the `files` input eg.
```
- name: Get changed files
   id: changed-files
   uses: tj-actions/changed-files@latest
   with:
       files: ["src/**", "package.json", ...etc] // something like this
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
