### ISSUE TITLE
[BUG] Running on PR doesn't get the correct head sha

### ISSUE THREAD

**Issue by velkovb** [tj-actions/changed-files#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

```
    GITHUB_SHA: c7244d8bab762360f5e7069010cd933337263a8d
    GITHUB_EVENT_BASE_REF: 
    GITHUB_EVENT_HEAD_REPO_FORK: false
    GITHUB_EVENT_PULL_REQUEST_NUMBER: 95
    GITHUB_EVENT_PULL_REQUEST_BASE_REF: main
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA: 5c19b27520a0664fe9cdead51559c743ef2
    GITHUB_EVENT_PULL_REQUEST_HEAD_SHA: af59c1e0fece3b2aa37b4072aa39eb0d191b093e
```

### To Reproduce

```yaml
on:
  pull_request:

      - name: Run changed-files with the commit of the last successful test workflow run on main
        id: changed-files-base-sha-pull-request
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true
          since_last_remote_commit: true
```

This should run changes between base and head sha but actually runs changes between base and GITHUB_SHA which in the case of a PR is non-existant.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

When running on PR shouldn't look at GITHUB_SHA but at GITHUB_EVENT_PULL_REQUEST_HEAD_SHA

### Relevant log output

```shell
I don't think there is any logs needed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
