### ISSUE TITLE
[Feature] Add support for listing deleted submodules

### ISSUE THREAD

**Issue by jckimble** [tj-actions/changed-files#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Delete variables empty.

I see that git diff --diff-filter=D in the main log shows the file but the return values are empty. Been playing with it for hours now trying to see if it's something I have wrong on configuration but with two different versions it still returns empty

### To Reproduce

```yml
steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - id: config
        uses: ./.github/actions/load-config
      - name: Get deleted files
        id: deleted-files
        uses: tj-actions/changed-files@v35.5.6
        with:
          files_ignore: .github/**
          json: true
          json_raw_format: true
          match_directories: false
```

with both match_directories and on. Both versions are supplied in the log output. 

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Should return deleted file pcsxr in list

### Relevant log output

https://github.com/jckimble/pkgbuilds/actions/runs/4269228333/jobs/7432286093

https://github.com/jckimble/pkgbuilds/actions/runs/4269246138/jobs/7432347193

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
